### ISSUE TITLE
Assignment issues with head number when using s=0 or s=1

### ISSUE THREAD

**Issue by hpingel** [davidgiven/fluxengine#102]
Impact of this issue is unclear, maybe only a display issue (cosmetic).
### s=0
In summary chart, dots are in section with head 1, not in section with head 0.
```
C:\Users\hp\Downloads\fluxengine(1)>fluxengine.exe read ibm -o "test4.d81" --revolutions=3 -s":d=0:t=17,19:s=0"
Reading from: :d=0:s=0:t=17,19
 17.0: 588 ms in 227456 bytes
       60 records, 30 sectors; 1.99us clock (503kHz);
       logical track 17.1; 5120 bytes decoded.
 19.0: 588 ms in 227520 bytes
       60 records, 30 sectors; 1.99us clock (502kHz);
       logical track 19.1; 5120 bytes decoded.
Autodetecting output geometry
H.SS Tracks --->
0. 0 XXXXXXXXXXXXXXXXXXXX
0. 1 XXXXXXXXXXXXXXXXXXXX
0. 2 XXXXXXXXXXXXXXXXXXXX
0. 3 XXXXXXXXXXXXXXXXXXXX
0. 4 XXXXXXXXXXXXXXXXXXXX
0. 5 XXXXXXXXXXXXXXXXXXXX
0. 6 XXXXXXXXXXXXXXXXXXXX
0. 7 XXXXXXXXXXXXXXXXXXXX
0. 8 XXXXXXXXXXXXXXXXXXXX
0. 9 XXXXXXXXXXXXXXXXXXXX
1. 0 XXXXXXXXXXXXXXXXX.X.
1. 1 XXXXXXXXXXXXXXXXX.X.
1. 2 XXXXXXXXXXXXXXXXX.X.
1. 3 XXXXXXXXXXXXXXXXX.X.
1. 4 XXXXXXXXXXXXXXXXX.X.
1. 5 XXXXXXXXXXXXXXXXX.X.
1. 6 XXXXXXXXXXXXXXXXX.X.
1. 7 XXXXXXXXXXXXXXXXX.X.
1. 8 XXXXXXXXXXXXXXXXX.X.
1. 9 XXXXXXXXXXXXXXXXX.X.
Good sectors: 20/400 (5%)
Missing sectors: 380/400 (95%)
Bad sectors: 0/400 (0%)
writing 20 tracks, 2 heads, 10 sectors, 512 bytes per sector, 200 kB total

```

### s=1
Here the head shown is 0.

```
C:\Users\hp\Downloads\fluxengine(1)>fluxengine.exe read ibm -o "test4.d81" --revolutions=3 -s":d=0:t=17,19:s=1"
Reading from: :d=0:s=1:t=17,19
 17.1: 588 ms in 227584 bytes
       60 records, 30 sectors; 2.00us clock (500kHz);
       logical track 17.0; 5120 bytes decoded.
 19.1: 588 ms in 227584 bytes
       60 records, 30 sectors; 1.99us clock (502kHz);
       logical track 19.0; 5120 bytes decoded.
Autodetecting output geometry
H.SS Tracks --->
0. 0 XXXXXXXXXXXXXXXXX.X.
0. 1 XXXXXXXXXXXXXXXXX.X.
0. 2 XXXXXXXXXXXXXXXXX.X.
0. 3 XXXXXXXXXXXXXXXXX.X.
0. 4 XXXXXXXXXXXXXXXXX.X.
0. 5 XXXXXXXXXXXXXXXXX.X.
0. 6 XXXXXXXXXXXXXXXXX.X.
0. 7 XXXXXXXXXXXXXXXXX.X.
0. 8 XXXXXXXXXXXXXXXXX.X.
0. 9 XXXXXXXXXXXXXXXXX.X.
Good sectors: 20/200 (10%)
Missing sectors: 180/200 (90%)
Bad sectors: 0/200 (0%)
writing 20 tracks, 1 heads, 10 sectors, 512 bytes per sector, 100 kB total

```

**Comment by davidgiven** [comment]
Interesting. Can you duplicate this with a flux file? If so, can you attach it?

**Comment by hpingel** [comment]
The above example is still an attempt to read Commodore 1581. In the other issue I wrote in the first posting that the Linus floppy driver tweak contains "swapsides". My understanding of this keyword is that it works out "upside down". I forgot this detail and I'm wondering if Fluxengine just does the right thing here. Don't ask me how Fluxengine does the trick. You should know it! :-)

I did a quick comparison with an Amiga disk. There, it looks all fine.

As the Amiga format is already known to Fluxengine, the summary diagram also contains 80 tracks/columns. My ibm custom 1581 approach has the line "Autodetecting output geometry". Therefore it doesn't show all the 80 columns above that will be displayed in case of the Amiga.

Any comments are welcome - and please feel free to close this issue if my understanding was correct.

**Comment by davidgiven** [comment]
FluxEngine (mostly) trusts the sector IDs in each sector record, and so doesn't care where the sectors are. The above log clearly shows that the sectors are reported as head 0 when read one way, and head 1 when read the other, which indicates that something's wrong at my end.

Can you do `fluxengine read ibm --just-read --retries=0 --write-flux=d81.flux` and attach the resulting flux file? (Unless there's anything confidential, of course.) Then I can have a look and try and find out what it is.

**Comment by hpingel** [comment]
Flux file attached to #95.

**Comment by davidgiven** [comment]
Thanks. Reproduced. And, yes, you were right, this is completely normal due to the device putting the data on the wrong sides; I'd misread the diagram.

This isn't a bug, it's WAI, but if you want you can use `--ignore-side-byte=true` to force the sectors on physical side 0 to appear on logical side 0. This will probably produce a garbage image, though.
