### ISSUE TITLE
Report: Reading of CMD FD-2000 HD disks successful

### ISSUE THREAD

**Issue by hpingel** [davidgiven/fluxengine#107]
Hi David,

This is not so much an issue, just some feedback. As I don't own a FD-2000 disk drive from Creative Micro Designs (CMD) I have written a d2m image file (downloaded from the internet) to a 3.5" HD disk using my ancient Linux box tweaking the disk drive in there as follows:

```
mknod /dev/fd0cmdfd2m b 2 124
setfdprm /dev/fd0cmdfd2m HD DS sect=10 ssize=1024 cyl=81 swapsides

time fdformat /dev/fd0cmdfd2m
time dd if=Downloads/dummy.fd2 of=/dev/fd0cmdfd2m count=1620 bs=1024
```
The FD-2000 HD disk format (a DD format can also be written by the drive) seems to have 81 tracks and 10 sectors of 1024 bytes per track. It stores 1620 KB of end-user data.

> CMD FD2000 disk drive, a third party floppy disk drive for the
> Commodore line of computers with double of the capacity:
> "CMDFD2M":
>  DS HD sect=10 cyl=81 ssize=1024 fmt_gap=100 gap=12 swapsides
> 

As it wants to be downward compatible to the Commodore 1581 drive, it also swaps the sides (=swapsides).

FluxEngine parmeters used:
`fluxengine read ibm --revolutions=2 -s ":d=0:t=0-80:s=0-1"`

Ressources:
https://web.archive.org/web/20060622053148/http://www.cmdweb.de/fd.htm
https://www.c64-wiki.de/wiki/FD-2000
http://www.unusedino.de/ec64/technical/formats/d2m-dnp.html
https://cbm8bit.com/articles/user-contributions/howto_d1m_d2m_d4m
Visualisation:
![fd2000](https://user-images.githubusercontent.com/646865/64913938-b02f8700-d749-11e9-9391-16ca08974cc5.png)

The only thing missing from FluxEngine is support for the image file extension "d2m" or even "d4m" for the CMD FS-4000.

**Comment by davidgiven** [comment]
(belatedly) Good news --- thanks for the report.
