### ISSUE TITLE
convert fluxtoscp - Invalid rpm or tracklen

### ISSUE THREAD

**Issue by davehope** [davidgiven/fluxengine#110]
I have a flux file from an ADFS 800K disk, created as follows:

fluxengine read adfs -s :d=0 -o victorian-d1-hd.img --write-flux=victorial-d1-hd.flux --hd

This resulted in an img file that works correctly.

I need to use the flux data to ultimately produce an APD file (for use in ADFFS in RiscOS). My method to do this unfortunately involves several (potentially lossy!) conversions. The first is to use fluxengine to write an SCP file:

fluxengine.exe convert fluxtoscp victorian-d1-hd.flux victorian-d1-hd.scp

> Writing 96 tpi double sided SCP file containing 160 SCP tracks
> FE track 0.0, SCP track 0: 195.395 ms in 94524 bytes
> FE track 0.1, SCP track 1: 195.755 ms in 85438 bytes
> ...
> FE track 79.1, SCP track 159: 196.294 ms in 74558 bytes
> Writing output file...

My next step is then to convert the SCP file to Kryoflux *.raw format using [HxCFloppyEmulator](http://Hxc2001.free.fr/floppy_drive_emulator/).  However, when loading the SCP file, HxCFloppyEmulator complains about invalid data in the SCP file:

> WARNING: Non-conventionnal index perdiod ! (39 ms)
> ERROR  : Invalid rpm or tracklen (1571 RPM, 3818887)...
> ERROR  : Invalid rpm or tracklen (4608 RPM, 750)...
> ERROR  : Invalid rpm or tracklen (4608 RPM, 750)...
> ERROR  : Invalid rpm or tracklen (4608 RPM, 750)...
> ERROR  : Invalid rpm or tracklen (4608 RPM, 750)...

This is repeated for each track, ultimately completing with:

> INFO 1 : track file successfully loaded and encoded!?

HxCFloppyEmulator does output the raw files, however they seem to be garbage (various tools fail to process them). 

Are the warnings & errors to be expected when loading an SCP file output by fluxengine? I'm trying to determine if the problem I'm facing lies with the SCP file produced by fluxengine, or the Kryoflux RAW files produced by HxCFloppyEmulator.

**Comment by davehope** [comment]
Should have said, I'm using Windows client version 186.

**Comment by davidgiven** [comment]
I haven't had the chance to test the scp generator other than round-tripping it back through fluxengine, so I'm not particularly surprised the files are invalid. That said, they look much more invalid than I was really expecting (scptoflux can read third-party SCP files, so if it can read fluxtoscp's SCP files I don't expect them to be _that_ wrong). OTOH there are problems with converting fluxengine to SCP due to semantic mismatches in the data format, so perhaps that's causing issues.

Sadly my time to investigate this will be limited until December due to other commitments, but if you're up to looking at it yourself, the conversion code's all in src/fe-fluxtoscp.cc.

What was the HxC tool you were using to convert SCP to Kryoflux?

**Comment by davehope** [comment]
> Sadly my time to investigate this will be limited until December due to other commitments, but if you're up to looking at it yourself, the conversion code's all in src/fe-fluxtoscp.cc.

Thanks for even replying, really appreciated.

> What was the HxC tool you were using to convert SCP to Kryoflux?

http://hxc2001.free.fr/floppy_drive_emulator/

Download link:

https://hxc2001.com/download/floppy_drive_emulator/HxCFloppyEmulator_soft.zip

**Comment by davidgiven** [comment]
I mean, what _specific_ tool? I wasn't aware HxC had utilities that did this. (All I can find inside the zipfile is a pile of Windows GUI binaries.)

**Comment by davehope** [comment]
Inside the zip file I linked there's a "Windows" directory containing "HxCFloppyEmulator.exe".

Launching this allows you to open various different formats of source image (.e.g SCP/Kryoflux etc). To do this you use the "Load" button. Before loading, you can enable logging by using the Log option (Log -> Log, click "Info/Warning/Error" and "Debug") to get better visibility of what's going on.

Once loaded, you can use the "Track Analyzer" to visualise what's going on. You can also "Export" to convert to any number of formats by clicking the "Export" button. In my case, I'm selecting "KF Stream file (*.raw)", using the file name "track" and clicking "Save".

Of course, this would be needless of fluxengine could write KryoFlux files natively :)

**Comment by davidgiven** [comment]
Ugh, I was hoping for a command line tool and not a GUI --- they're so much harder to script...

KryoFlux export's a possibility, but the format's amazingly annoying to work with. Hopefully I'll be able to get back to this in December.

**Comment by davidgiven** [comment]
I believe this should be fixed now in the latest version; or at least, it should be better. If you're still working on this, PTAL?

**Comment by jfdelnero** [comment]
> Ugh, I was hoping for a command line tool and not a GUI --- they're so much harder to script...
> 
> KryoFlux export's a possibility, but the format's amazingly annoying to work with. Hopefully I'll be able to get back to this in December.

FYI The HxC Floppy Emulator tool is of course available in command line too : 

https://hxc2001.com/download/floppy_drive_emulator/HxCFloppyEmulator_soft_beta.zip

This is the "hxcfe.exe" program, which is a pure command line version.

source available there : 

https://sourceforge.net/p/hxcfloppyemu/code/HEAD/tree/HxCFloppyEmulator/HxCFloppyEmulator_cmdline/trunk/
