### ISSUE TITLE
Building fluxengine on MacOS

### ISSUE THREAD

**Issue by tamberg** [davidgiven/fluxengine#116]
Building the _fluxengine_ client on MacOS with (ninja) _make_ I get the following error:

	... lib/usb.cc:7:10: fatal error: 'libusb.h' file not found
	#include <libusb.h>
        	 ^~~~~~~~~~
	1 error generated.

After changing lib/usb.cc
	
	//#include <libusb.h>
	#include <libusb-1.0/libusb.h>

I get a new (unrelated) warning:

	src/fe-fluxtoscp.cc:88:5: warning: array index 3 is past the end of the array (which contains 3 elements) [-Warray-bounds]
	fileheader.file_id[3] = 0x18; /* Version 1.8 of the spec */
	^                  ~ 
	src/scp.h:6:5: note: array 'file_id' declared here char file_id[3]; // file ID - 'SCP' 
	^ 
	1 warning generated. 

After changing src/fe-fluxtoscp.cc

    //fileheader.file_id[3] = 0x18; /* Version 1.8 of the spec */
    fileheader.version = 0x18; /* Version 1.8 of the spec */

I get 

	g++ -Os  -o .obj/bitaccumulator-test-debug .obj/libbitaccumulator-test.a .obj/libbackend.a .obj/libfmt.a  
	Undefined symbols for architecture x86_64:
	  "_compress", referenced from:
	      Bytes::compress() const in libbackend.a(bytes.o)
	  "_compressBound", referenced from:
	      Bytes::compress() const in libbackend.a(bytes.o)
	  "_inflate", referenced from:
	      Bytes::decompress() const in libbackend.a(bytes.o)
	  "_inflateEnd", referenced from:
	      Bytes::decompress() const in libbackend.a(bytes.o)
	  "_inflateInit_", referenced from:
	      Bytes::decompress() const in libbackend.a(bytes.o)
	ld: symbol(s) not found for architecture x86_64
	clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any ideas how to fix this?

**Comment by davidgiven** [comment]
Re the scp file_id warning: wow. I can't believe I did that. Fixing. (It should actually generate the right data even with the out-of-bounds access, but it still needs to be fixed.)

Re the package errors: the client is known to build on OSX and I can prove it by pointing you at the CI logs: https://travis-ci.org/davidgiven/fluxengine/jobs/624316680 

I suspect that you don't have libusb and zlib installed via `pkg-config`, which means that the right flags haven't been added, hence the need to modify the makefiles manually. Unfortunately OSX has like a million different ways of getting packages so all I can do is to run `pkg-config` and hope they show up there. The CI system used Homebrew, but anything else which supports `pkg-config` should work. What is your setup?

Strictly it should be an error if the Makefile spots that the packages aren't there, to prevent confusing build failures like you're seeing.

**Comment by tamberg** [comment]
Thanks for the quick reply. I use Homebrew. After _brew install libusb_ and _brew install zlib_ the (new) error is:

    FAILED: .obj/compression-test-debug 
    g++ -Os  -o .obj/compression-test-debug .obj/libcompression-test.a .obj/libbackend.a .obj/libfmt.a  
    Undefined symbols for architecture x86_64:
      "_compress", referenced from:
          Bytes::compress() const in libbackend.a(bytes.o)
      "_compressBound", referenced from:
          Bytes::compress() const in libbackend.a(bytes.o)
      "_inflate", referenced from:
      Bytes::decompress() const in libbackend.a(bytes.o)
      "_inflateEnd", referenced from:
          Bytes::decompress() const in libbackend.a(bytes.o)
      "_inflateInit_", referenced from:
          Bytes::decompress() const in libbackend.a(bytes.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by davidgiven** [comment]
Can you update from head of git and try again? There should be some more diagnostics if the packages can't be found. Also, please do `pkg-config --list-all` and let me know the results?

What setup do you have?

**Comment by tamberg** [comment]
mac:fluxengine tamberg$ pkg-config --list-all
    -bash: pkg-config: command not found

**Comment by tamberg** [comment]
Ok, after calling _brew install pkg-config_ everything works fine. Thanks a lot.

**Comment by davidgiven** [comment]
Good to know. I'll update the documentation.

**Comment by tamberg** [comment]
Just to confirm: Updated to newest HEAD. Everything builds fine now.
