### ISSUE TITLE
Reading 5.25 HD IBM Floppy

### ISSUE THREAD

**Issue by Trekinfo** [davidgiven/fluxengine#125]
Hi,

i had issues reading 5.25 HD Disks.
Reading with "fluxengine read ibm --hd" creates a lot errors at a reading Rate of ~0.9us.
If i Inspect the Disk with "fluxengine inspect -s :t=1:s=0" it tells me a optimal rate of 1.92-2.00us

It seems that Fluxengine guess the wrong timing. How can i set them manually?

Greets Trekinfo

**Comment by davidgiven** [comment]
That's normal, but unintuitive. IBM disks use MFM, which emits pulses at half clock intervals provided they're not closer together than one clock --- so it can emit a pulse at T+0 and T+1.5 and then T+2.5. This confuses the (very simple) autodetection logic in `inspect` so it thinks the clock is twice what it is.

You can set the clock rate in `inspect` with `--manual-clock-rate-us`. (But this doesn't affect `read`, which uses a different clock detection algorithm.)
