### ISSUE TITLE
HD 5.25" disks don't appear to read successfully

### ISSUE THREAD

**Issue by Trekinfo** [davidgiven/fluxengine#126]
Hello David, 

does the FluxEngine set the HD Flag in Pin 2 with the --hd Command?

It seems to me, that the reading Problems on the 5.25 HD Floppy are the result of an non existing HD Flag in Pin 2.

Therefore the Drive don't Switch from DD to HD. This would be the reason why DD Disks works 100% and HD not. 

Greets Trekinfo

**Comment by davidgiven** [comment]
Yes, it should (and I've verified the pin is actually set correctly), but I haven't observed it to have any effect. You're right in the HD disks do seem to be problematic and I've never quite figured out why. Sadly both my 5.25" drives have failed so my ability to test is kinda minimal right now. If you have any ideas, I'd love to know...

If you look at the schematic in PSoC Creator you should be able to see that pin 2 is wired to DENSITY_REG. If you then wire that to the debug LED you should be able to see exactly what it's set to by looking at whether the LED lights up or not. (You should be able to find the LED somewhere on the schematic; it's usually hooked up somewhere. P1[2], I think.)

**Comment by davidgiven** [comment]
Context due to renaming the bug: yes, there does seem to be something wrong with reading HD disks on 5.25" drives, in general. I suspect I'm not driving the disk correctly; not working in HD mode does seem to be the most plausible explanation --- but I'm pretty sure it's wired up correctly, so _something_ weird is wrong, which needs investigation.

**Comment by davidgiven** [comment]
I just had reported to me that 3.5" HD disks didn't read either, and have found and fixed a generic bug with reading IBM HD disks. Could you update from head of git or install release 270 or later and let me know whether this still fails for 5.25" HD disks, please? You should _not_ need to reprogram the firmware; it's a client side fix.

Thanks!

**Comment by Trekinfo** [comment]
Hmm,
The Client crashes at 20-30% of reading the Disk on a TEAC FD-55
TEAC FD-505 (Dual Drive) reads the Disk without Problems.

**Comment by davidgiven** [comment]
That's really interesting.

Previously you were reporting bad reads on the FD-505, right? That is, the read would complete but it would be full of bad sectors?

**Comment by Trekinfo** [comment]
Yes indeed, 

it seems that the FD-505 is better for HD and the FD-55 for DD. Maybe it's a issue with the jumpering of the FD-55.

I wired PIN2 to the debug LED and it lit even with no Power on PoSC. Very confusing, i need more research.

**Comment by davidgiven** [comment]
I've just found and fixed a nasty memory corruption issue in the firmware which was causing bad reads of HD disks (and may have been causing the crashes). Could you try release 279 or later and seeing if that's any better? https://github.com/davidgiven/fluxengine/releases Thanks!

**Comment by Trekinfo** [comment]
OK,

first no more crashes. 
I wired PIN2 to Debug LED.
If HD Option is on the LED is off. Without HD Option the LED is on. It seems, if they are invertet.
Without Power on the USB of the PoSC then the Debug LED ist very low. I comes backward from the drive.

**Comment by davidgiven** [comment]
Excellent news, thanks.

FDD signals are active low, so when the light's off and the logic level is 0 then the HD signal to the drive is _active_ --- that's correct. Are you seeing any difference in behaviour?

**Comment by Trekinfo** [comment]
The TEAC FD-505 works in HD Mode like Charm. 
The TEAD FD-55 make lots of read errors. (Maybe a Jumper Issue. I must test different Jumper settings)

FD-505 in DD Mode works also like Charn.
FD-55 here also Errors (I think its an Issue with the I and IS Jumper witch toogles the Drive RPM via the Signal on PIN2. At the moment the Drive is set to Dual Mode)

FD-505 on C64 Mode also no Problems

**Comment by davidgiven** [comment]
Do you know that the FD-55 actually works (i.e., do you have a PC you can plug it in to to test)? Both my 5.25" drives died more or less simultaneously and it took a long time before I realised it was actually a hardware fault.

**Comment by Trekinfo** [comment]
You're right.
The Drive is broken. I found another FD-55 (this was mounted in an Amiga 2000 and Modified).
Remove the Modification and it works like Charm 100% Error free

**Comment by davidgiven** [comment]
Good to know it works. Thanks for the bug report, and I'm sorry for the problems (I should have noticed that...).
