### ISSUE TITLE
Mac 800k disks

### ISSUE THREAD

**Issue by m6502** [davidgiven/fluxengine#13]
Hi, I can format a few 800k Mac disks and send them to you :-)

**Comment by davidgiven** [comment]
That's awesome, I'd love one! I've written a decoder using a Kryoflux dump but I want a real disk to test with.

Where are you geographically? If outside Europe it probably makes no sense (I can probably find one closer).

**Comment by m6502** [comment]
I'll drop you an e-mail :-)

**Comment by davidgiven** [comment]
Belatedly, thanks very much --- closing bug for cleanup.
