### ISSUE TITLE
GND confusion

### ISSUE THREAD

**Issue by bidblog** [davidgiven/fluxengine#142]
Hi David.

This is a cool project, and I am going to build one for my self. 

But I am confused about the Grounding description.

_"If you’re using a connector, the simplest thing to do is to bend up one of the unconnected pins and solder a short piece of wire to a GND pin on the board. Alternatively you’ll need to splice it into your drive’s power supply cable somehow. (The black one.)"_

If I solder a wire  between GND on the Cypress board and one of the unused pins on the 34 pin connector (the row that is not attached to the board i guess) how will this be grounded with the floppy drive?

I would really like to avoid to have to split the power supply cable for the floppy drive :-)

Cheers. 

Henrik

**Comment by davidgiven** [comment]
At the drive end of the cable, all the odd-numbered pins are connected to the power supply ground. So by connecting the Cypress board to one, you ensure they have a common ground.

There should be a reasonably clarifying diagram here: http://cowlark.com/fluxengine/doc/building.html#technical-details

**Comment by bidblog** [comment]
Thanks. I just noticed that your diagram shows pin 33 connected to GND.

This is a really cool project. Thank you for making this available.
