### ISSUE TITLE
Amiga Write Support

### ISSUE THREAD

**Issue by aquarius1974** [davidgiven/fluxengine#147]
In Version 354 and 350 the amiga write command produces Error messages like:
0.0: Error: data transfer failed: Pipe error
0.0: Error: failed to receive command reply: Input/Output Error

[Issue_Amiga_ADF_fluxengine_340.zip](https://github.com/davidgiven/fluxengine/files/4396951/Issue_Amiga_ADF_fluxengine_340.zip)

I downgraded to 340 and the write command is working, but the resulting disk is not booting in my real amiga. The interesting thing is that it boots partially in the Amiga Forever Emulator.

I attach two ADFs:
1) advanced_analyse.adf is read from the working Amiga Disk
2) Advanced_Analyse_reread_28_03_2020_11022291.adf is No.1 written back to disk and then reread again with the fluxengine

No. 1 is working in the emulator, but No.2 has Read Errors and is only partialy booting.

Comparing the files I see a perfect match until Position 723FF. After that there are no matching bytes.

**Comment by aquarius1974** [comment]
> After that there are no matching bytes.

What I wrote is not exact. I compared the files again - there are only two sections that are different.

![image](https://user-images.githubusercontent.com/40863758/77845442-47709f00-71af-11ea-8c21-c13b04ef4f33.png)

![image](https://user-images.githubusercontent.com/40863758/77845357-979b3180-71ae-11ea-83e3-c9b7d903dd20.png)

**Comment by davidgiven** [comment]
You may be running into an outstanding bug where there's a buffer overrun in the firmware causing corrupt reads on some disks --- if you try reading the disk again and get a different result, then that's most likely it. I have a fix in the works which should show up Real Soon. Thanks for testing this!

**Comment by aquarius1974** [comment]
I need to build the .exe myself to test this, right?

**Comment by davidgiven** [comment]
Once the fix hits trunk there'll be a precompiled binary. If you want to try it yourself, you'll need to check out the sixbit branch and build it yourself; sorry about that. I wouldn't recommend it right now as there are still a few bugs that I need to sort out (but if you're interested in testing it that would be awesome).

**Comment by aquarius1974** [comment]
I will test it, when the next release is ready.

**Comment by aquarius1974** [comment]
The writing process is giving no errors with Version 369.

Rereading the testdisk gives still differences, but less:
![image](https://user-images.githubusercontent.com/40863758/78153427-553a5480-743b-11ea-9a0a-1997989389e6.png)

**Comment by aquarius1974** [comment]
The testdisk is sadly not bootable.

**Comment by aquarius1974** [comment]
Another disk as well not bootable.

I have prepared a Gotek to boot .adf-Files directly from USB-Stick, so the Amiga Write support in the Fluxengine is not urgent anymore for me.

I will have a new try when new versions come out.

**Comment by davidgiven** [comment]
I've just merged the fixed firmware and client. Unfortunately there seems to be something else not quite right which needs investigation. Would it be possible for you to test something for me, please?

If so, I'd like text logs of: a disk formatted on the Amiga; a disk written by FluxEngine and then read back again. I don't need the image or the flux file. (I want to see the clock rate reported for each track.)

Thanks!

**Comment by aquarius1974** [comment]
There you go:

1) Reading of an empty freshly formated disk with Workbench 1.3 systemtools.

[Fluxengine_389_read_amiga_empty_formated.txt](https://github.com/davidgiven/fluxengine/files/4458439/Fluxengine_389_read_amiga_empty_formated.txt)

**Comment by aquarius1974** [comment]
2. ReReading the Disk #1 

[Fluxengine_389_REread_amiga_empty_formated.txt](https://github.com/davidgiven/fluxengine/files/4458471/Fluxengine_389_REread_amiga_empty_formated.txt)

**Comment by davidgiven** [comment]
Thanks very much!

**Comment by davidgiven** [comment]
I believe this to be obsolete now?
