### ISSUE TITLE
Is OSX build working ok for you?

### ISSUE THREAD

**Issue by david-schmidt** [davidgiven/fluxengine#15]
I pulled the most recent osx branch (and also the master branch) - and now `fe-readbrother` is giving me floating point errors of some sort:
```
$ .obj/fe-readbrother -s /tmp/240k/
Reading from: /tmp/240k/:d=0:s=0:t=0-81
  0.0: 1086 ms in 143504 bytes
       0.00 us clock; Floating point exception: 8
$
```
Doing `--just-read` is working ok:
```
$ .obj/fe-readbrother --just-read -s /tmp/240k/
Reading from: /tmp/240k/:d=0:s=0:t=0-81
  0.0: 1086 ms in 143504 bytes
  1.0: 1097 ms in 148946 bytes
...
  80.0: 1139 ms in 99020 bytes
  81.0: 1139 ms in 96609 bytes
--just-read specified, halting now
$
```
Is it still successful for you?  Using code from yesterday, I got actual results.

**Comment by davidgiven** [comment]
Sorry, that one's my fault.

It's now doing much more robust clock detection (so reads should be more accurate). However, I forgot to take into account the case when it can't detect a clock at all, which is what you're seeing here. You obviously have much less reused disks than I have.

Incidentally, I've also done a tonne of refactoring and bugfixing, including finding some nasty Kryoflux stream reading bugs which causes single-bit errors. If your reads had occasional bad sectors, this will probably fix them. You may want to rescan any Kryoflux dumps you have.

It should now be fixed --- PTAL. (Also, I've finally remembered to merge the osx branch.)

**Comment by david-schmidt** [comment]
Nice!  My first 240k disk works now.  My 120k instance is a hot mess, still.   Are you interested in looking at some fluxes of that?

**Comment by davidgiven** [comment]
Good here. Re flux files for the 120kB disks: yes, please!

(What does FluxEngine report when you show it the disk? Are you using `-s :t=0-79x2`?

**Comment by david-schmidt** [comment]
Here's the final output from trying to read using `-s :t=0-79x2`:
```
H.SS Tracks --->
0. 0 ...XXX.BXBXX....XXX..BXX...XX....XX....
0. 1 ...XX.B.XXXX.....X...BXX....X.....X....
0. 2 ...XX..BXXXX..........XX....X.....B....
0. 3 ..BXX...XXXXB..B.B....XX....XB....BX...
0. 4 ...XX.B..XXXB...X.....XX...BX....B.....
0. 5 ..BXXBBBXBXX....XX....XX....X.....B....
0. 6 ...XX.B.XXXXB....B...XXX...BX..........
0. 7 ...XXB.BBBXX....B.B...XX...XX.....X....
0. 8 ...XXB..XXBX.....BB...XX....X.....BX...
0. 9 ...XXB..XXXX....B.....XX....X....X.....
0.10 ..BXXX..XXXX....BB....XX....XB....B....
0.11 ...XX....XXX..........XX...BX....X.....
0.12 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.13 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.14 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.15 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.16 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.17 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.18 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.19 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.20 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.21 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.22 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.23 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.24 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.25 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.26 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.27 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.28 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.29 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.30 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.31 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.32 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.33 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.34 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.35 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.36 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.37 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.38 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.39 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.40 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.41 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.42 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.43 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.44 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.45 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.46 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.47 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.48 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.49 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.50 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.51 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.52 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.53 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.54 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.55 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.56 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.57 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.58 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.59 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.60 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.61 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.62 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.63 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.64 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.65 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.66 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.67 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.68 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.69 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.70 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.71 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.72 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.73 XXXXXXXXXXXXBXXXXXXXXXXXXXXXXXXXXXXXXXX
```

I'll send you a zip to the email on your website.

**Comment by davidgiven** [comment]
Thanks for the dumps --- I'll take a look.

Re the sector map: oo, that's interesting. I've actually seen that before and thought it was a bad disk. (I should certainly add sanity checking so that it doesn't think that sector 73 is valid.)

B means a CRC mismatch; X means that sector is missing completely. The vertical stripes suggest that a problem with the track spacing --- the one I saw before had 78 logical tracks spread through 79 physical tracks and during the capture you could see one track repeated. (The decode process will tell you the logical track for every physical track. You should be able to see a mismatch.)

Apparently many Brother word processors have misaligned heads, but for them I'd expect the track spacing to be right, just to get poor-quality captures because the data isn't directly under the head.

Anyway, thanks; I'll investigate.

**Comment by davidgiven** [comment]
Aha, fixed. There were two things wrong here:

- your disk actually has the data tracks on _odd_ tracks, not _even_, so by using 0-79x2 you were reading the gaps between the tracks rather than the tracks themselves, which is why the data quality was terrible;

- there was a bug at my end where if the same sector was seen more than once in different tracks, the last one would win, even if it had a CRC error and the first one was good.

I've fixed the last; you can now get a clean read (100% good sectors) of a 120kB disk by just doing `fe-readbrother -s 120k/`, without needing any parameters any more. It'll hoover up all sectors and assemble them into an image.

**Comment by david-schmidt** [comment]
That is simply splendid.  Each one of these crazy things seems to be its very own special unicorn.

**Comment by davidgiven** [comment]
I love finding bugs where I did something really stupid --- they're so easy to fix! Also, without your weird disks there would have been several lurking bit errors and random corruption bugs for a good while, so thank _you_. Do let me know if you have any more issues!

**Comment by david-schmidt** [comment]
I tried out my Brother-supplied software disks, and even those read without trouble.  Off to fix up my tooling for all this new Brother goodness...
https://github.com/RetroFloppy/transformenator

**Comment by davidgiven** [comment]
...you have _software_ disks? Things like the demo/typing tutor disk that was supposed to run on the machines in the showroom?

Can I have a copy, please? I've been wanting to get my hands on those for ages; I want to reverse engineer the file format and run my own programs on the typewriter. I've found one office supplier _in the world_ who claim to have that disk in stock, and it's in French, they're in the US, and aren't answering my email...

**Comment by david-schmidt** [comment]
Certainly, I will give you what I have.  I don't think either is a demo; it's the spreadsheet software and a few other apps from the WP-85/WP-95 models.

**Comment by davidgiven** [comment]
Thanks --- sadly, it doesn't work. I made my Swiss LW-30 read it and the documents will load, but it won't run the program, instead complaining in German that it's not a program disk.

Is this a image of the original disk or a reconstruction? I had to flip the media bytes in the file system header from 0xF0 to 0x58 before it would read.

**Comment by david-schmidt** [comment]
Here's the unadulterated versions of the two disks I have, with snapshots of the disk faces.
[Brother-sw.zip](https://github.com/davidgiven/fluxengine/files/2896509/Brother-sw.zip)

**Comment by davidgiven** [comment]
Those don't work either --- the word processor reads them fine, but again claims they're not program disks. Obviously they're just not compatible with my LW-30. (I will admit, though, that the thrill of writing a disk image to a disk and then having my typewriter _read_ it doesn't get old.)

Can I keep these images for my collection or would you rather I erased them?

**Comment by david-schmidt** [comment]
They're all yours!
