### ISSUE TITLE
Bug : fluxengine read amiga -- generating a file bigger than 901120

### ISSUE THREAD

**Issue by ourIThome** [davidgiven/fluxengine#154]
I know I emailed over this issue over the weekend -- suspecting I might have done something silly.  

After some testing with the latest build 382, and rolling back to 369 ... I have done another test and can confirm maybe this has been happening for a while?  Figured I should raise this in github... as I dont believe I am doing anything wrong.

fluxengine read amiga

Generates a file that is 901136 bytes in size
it should be 901120 -- 512 * 11 * 2 * 80.

Let me know if you want any flux files / adf generated.  Happy for you to email directly.

**Comment by tingox** [comment]
FWIW, I can confirm this:
```
tingo@kg-core1$ ll 35_amiga_dd*
-rw-r--r--  1 tingo  tingo  - 901136 Apr  6 22:42 35_amiga_dd_1942setup.adf
-rw-r--r--  1 tingo  tingo  - 901136 Apr  6 22:45 35_amiga_dd_pgp_1.adf
-rw-r--r--  1 tingo  tingo  - 901136 Apr  6 22:38 35_amiga_dd_storage1.adf
-rw-r--r--  1 tingo  tingo  - 901136 Apr  6 22:08 35_amiga_dd_storage10.adf
-rw-r--r--  1 tingo  tingo  - 901136 Apr  6 22:03 35_amiga_dd_storage11.adf
-rw-r--r--  1 tingo  tingo  - 901136 Apr  6 21:51 35_amiga_dd_storage12.adf
-rw-r--r--  1 tingo  tingo  - 901136 Apr  6 20:48 35_amiga_dd_storage13.adf
-rw-r--r--  1 tingo  tingo  - 901136 Apr  6 22:32 35_amiga_dd_storage2.adf
-rw-r--r--  1 tingo  tingo  - 901136 Apr  6 22:30 35_amiga_dd_storage3.adf
-rw-r--r--  1 tingo  tingo  - 901136 Apr  6 22:28 35_amiga_dd_storage4.adf
-rw-r--r--  1 tingo  tingo  - 901136 Apr  6 22:25 35_amiga_dd_storage5.adf
-rw-r--r--  1 tingo  tingo  - 901136 Apr  6 22:20 35_amiga_dd_storage6.adf
-rw-r--r--  1 tingo  tingo  - 901136 Apr  6 22:17 35_amiga_dd_storage7.adf
-rw-r--r--  1 tingo  tingo  - 901136 Apr  6 22:13 35_amiga_dd_storage8.adf
-rw-r--r--  1 tingo  tingo  - 901136 Apr  6 22:11 35_amiga_dd_storage9.adf
-rw-r--r--  1 tingo  tingo  - 901136 Apr  6 22:48 35_amiga_dd_update_3.x-1.adf
```
Unfortunately, I don't know more about ADF format than what the Amiga Disk File FAQ tells. Currently using latest from master:
```
tingo@kg-core1$ git log -1
commit 8dbd2a72a705b81f57d0a8432724d53113d67c61 (HEAD -> master, tag: FluxEngine-Windows-client-version-382, origin/master, origin/HEAD)
Merge: 2007ff7 c29e131
Author: David Given <dg@cowlark.com>
Date:   Fri Apr 3 23:54:29 2020 +0200

    Merge pull request #150 from davidgiven/sixbit
    
    Fix the new sampler and sequencer

```
HTH

**Comment by davidgiven** [comment]
.adf is an alias for .img, so what you're seeing there is completely impossible...

**Comment by tingox** [comment]
FWIW, the .adf images appears to work well:
```
tingo@kg-core1$ xdftool personal/projects/PSoC/fluxengine/tmp/35_amiga_dd_storage1.adf info
total:        1760  880Ki        901120
used:         1759  879Ki        900608  99.94%
free:            1  512Bi           512   0.06%
tingo@kg-core1$ xdftool personal/projects/PSoC/fluxengine/tmp/35_amiga_dd_storage13.adf info
total:        1760  880Ki        901120
used:         1745  872Ki        893440  99.15%
free:           15  7.5Ki          7680   0.85%

```

**Comment by tingox** [comment]
Here is another one
```
tingo@kg-core1$ ls -l 35_amiga_dd_datatypes_1.adf
-rw-r--r--  1 tingo  tingo  901136 Apr  6 23:59 35_amiga_dd_datatypes_1.adf
tingo@kg-core1$ xdftool 35_amiga_dd_datatypes_1.adf info
total:        1760  880Ki        901120
used:          175   87Ki         89600   9.94%
free:         1585  792Ki        811520  90.06%
tingo@kg-core1$ xdftool 35_amiga_dd_datatypes_1.adf list
DataTypes_1                                      VOLUME  --------  03.05.1994 23:34:10.11  DOS1:ffs #512
  Ams.lha                                         16131  ----rw-d  03.05.1994 21:38:32.02  
  jpg1dt.lha                                      34571  ----rw-d  12.08.1993 22:28:55.10  
  Pic-DataT_42_1.Lha                               9801  ----rw-d  11.12.1993 17:42:09.42  
  PicDT_42_1.lha                                  10240  ----rw-d  19.10.1993 20:44:52.23  
  TPD.lha                                          6471  ----rw-d  04.09.1993 12:46:20.35  
  ZGIFDT39.7.lha                                   5965  ----rw-d  18.09.1993 22:26:01.41  
sum:           172   86Ki         88064
data:          165   82Ki         84480  95.93%
fs:              7  3.5Ki          3584   4.07%
```
I don't know why there are more bytes than it should be

**Comment by ourIThome** [comment]
I was thinking this morning (good cup of coffee to help) ... 

If 901136 is being generated, and normally most ADF files are 901120 ... this is a difference of 16 bytes that I am seeing.

Tin foil hats on ... thinking aloud ... pinch of salt and all of that...

http://cowlark.com/fluxengine/doc/disk-amiga.html

mentions if you want the header stuff, you need to use b=528

528 - 512 = 16 bytes.

Could the first part of decoding to ADF be forcing 528 for the first sector, when decoding to adf?  Sorry if im not using the right terminology.

I did try reading just t=30,s=0 and from what I can tell, all the adf at the start is blank, as well as the end of the data from 30 onwards appears blank ... so possibly isolated to the decoding to adf?

Ill try and find a disk in this collection, where I can compare to a TOSEC file.

**Comment by ourIThome** [comment]
Quickly found a box I did from a previous capture with a Kryoflux.
Imaged the disk now with fluxengine with the defaults so :

fluxengine read amiga "photon paint"

I did a hex compare of the two files, and it looks like there are 16bytes of 00 being appended tt the end of the fluxengine generated file.

**Comment by ourIThome** [comment]
> .adf is an alias for .img, so what you're seeing there is completely impossible...

I thought I would add another test for fluxengine read ibm ...

writing 80 tracks, 2 heads, 18 sectors, 512 bytes per sector, 1440 kB total

80 × 2 × 18 × 512 = 1,474,560 bytes

I can confirm for IBM HD img that was generated, that it correctly generated a file :

1,474,560 ibm.img

So IBM works, but not ADF.  Thought id at least do a test to see if IBM disks was any different.

Let me know if you need anything from me.

Cheers everyone.

**Comment by davidgiven** [comment]
Yep, duplicated --- it's really silly, when it writes each sector it writes the entire 512+16 data payload, but unless you actually ask for the metadata with -o :s=528 then the metadata is overwritten by the next sector... except for the last. Fixed.
