### ISSUE TITLE
Wrong USB product ID/vendor ID on macOS using prebuilt binary

### ISSUE THREAD

**Issue by andlabs** [davidgiven/fluxengine#158]
Hi. I just built a fluxengine and flashed it using the prebuilt firmware from client version 389, and also a version of the fluxengine CLI from the same commit (3c54a663b87629b57907c8b691cb268b6f80a1d5) built for macOS. However, no matter what I try to do, I get

```
Error: cannot find the FluxEngine (is it plugged in?)
```

`system_profiler SPUSBDataType` (the equivalent of `lsusb` on macOS) says:

```
    USB 3.0 Bus:

      Host Controller Driver: AppleUSBXHCIPPT
      PCI Device ID: 0x1e31 
      PCI Revision ID: 0x0004 
      PCI Vendor ID: 0x8086 

        Cypress KitProg:

          Product ID: 0xf139
          Vendor ID: 0x04b4  (Cypress Semiconductor)
          Version: 2.14
          Serial Number: 14081023012A8400
          Speed: Up to 12 Mb/sec
          Manufacturer: Cypress Semiconductor
          Location ID: 0x14100000 / 9
          Current Available (mA): 500
          Current Required (mA): 400
          Extra Operating Current (mA): 0
```

which is definitely not the PID/VID in protcool.h.

So I'm not sure; did I do something wrong here?

The host machine is a MacBook Pro (15-inch, Mid-2012) running macOS Sierra 10.12.6 (16G2136). The firmware was flashed using a Windows 7 VM running in VMware Fusion 11.5.3 (15870345), using Cypress PSoC Programmer 3.27.1.3121. It had me update the PSoC's own firmware to version 2.20 before continuing. I will say that at first when flashing the firmware the device disconnected and reconnected repeatedly, causing VMware to eventually think it was a new device and ask me what to connect to, meaning the initial steps failed to find the device partway in; afterward, however, it worked flawlessly, even after reboots (of both the OS and the VM). I even had it do a Verify step just now and that passed.

Thanks!

**Comment by davidgiven** [comment]
Try the other end!

That looks like you have it connected to the debugger port (the male USB connector on the small board). To actually use the device you'll need the port on the main board (the small silver micro-USB connector; you'll need to remove the plastic). I tend to have them both plugged in at the same time.

If you _do_ have them both plugged in, possibly the flash didn't work, but that seems unlikely given you verified it.

**Comment by andlabs** [comment]
OK! I noticed the plastic foil but didn't notice that was another USB lead there :D Will do so tomorrow.

In the meantime is there a better place to ask about current support for 3.5" MSX/MSX2 disks and 5.25" PC-88 disks? Would `ibm` suffice? I keep seeing mentions about the former using 256-byte sectors???

**Comment by davidgiven** [comment]
Chances are IBM will work fine --- everything ought to be autodetected. There is one command line option which might need to be used if sector IDs start at 0 (like Acorn does), but that seems to be pretty rare. Let me know how it works and if you have any problems.

**Comment by andlabs** [comment]
All right, well it does work, thanks! I haven't been able to test drive support yet, because I don't have a spare 5.25" disk to test the orientation of my red line-less cable with, and I bent the pins on the connector before I was able to test the 3.5" drive :D But this issue is resolved; thanks.

(A command similar to OpenCBM's `cbmctrl status` command would be useful just for checking that everything is oriented correctly, since flipping the 5.25" drive's cable on the FluxEngine side did nothing to the TEAC FD-55GFR; it just stood still.)

**Comment by davidgiven** [comment]
`fluxengine rpm` and `fluxengine test voltages` should help with testing --- sadly, PC FDDs are so dumb that there's no real way to talk to them without actually spinning the disk for real...

**Comment by andlabs** [comment]
Ah, oh well :/ Thanks in the meantime!
