### ISSUE TITLE
Brother SVG tracks possibly laid out backwards?

### ISSUE THREAD

**Issue by flimshaw** [davidgiven/fluxengine#161]
I've been using fluxengine to troubleshoot a Brother WP floppy drive and I'm getting some odd behavior from the SVG dump. 

<img width="632" alt="Screen Shot 2020-05-10 at 12 52 35 PM" src="https://user-images.githubusercontent.com/157224/81505464-4c039980-92bd-11ea-95cd-c36280ed3571.png">

My WP drive's issue is that it fails to format disks: it starts at the outside but never seems to succeed and move inward. But the SVG debug of a failed format shows track 0 as the innermost track.

**Comment by flimshaw** [comment]
if this is indeed a bug and I'm not just fundamentally misunderstanding something (very possible!) I submitted a pr: https://github.com/davidgiven/fluxengine/pull/162

**Comment by davidgiven** [comment]
Yes, that's a bug! Thanks very much for both the report and the fix. I've commented on your PR.
