### ISSUE TITLE
Problem reading TRS-80 model 1 single density disks

### ISSUE THREAD

**Issue by vanbogaertetienne** [davidgiven/fluxengine#166]
When reading the disks from my fathers TRS-80 model 1, I get the following errors on logical track 17. This is reproducible on all disks. 

```
34.0: 210 ms in 62656 bytes
       154 records, 77 sectors; 3.38us clock (296kHz); 
       Failed to read sector -1 (present but no data found); 
       Failed to read sector 0 (present but no data found); 
       Failed to read sector 1 (present but no data found); 
       Failed to read sector 2 (present but no data found); 
       Failed to read sector 3 (present but no data found); 
       Failed to read sector 4 (present but no data found); 
       Failed to read sector 5 (present but no data found); 
       Failed to read sector 6 (present but no data found); 
       Failed to read sector 7 (present but no data found); 
       Failed to read sector 8 (present but no data found); 
       giving up
       logical track 17.0; 0 bytes decoded.
```

All other tracks read without error, and when looking at the files in a hex editor, I see the data that is supposed to be there, except track 17.

The disks have 35 tracks, I use the following command to read them:
```fluxengine read ibm -o trsdos.img -s :t=0-69x2:s=0 --write-flux trsdos.flux --write-svg trsdos.svg```

I tried giving the option --read-fm=true as I'm told in the trs-80 docs, but I get the following error: 
  ```Error: unknown flag '--read-fm'; try --help```

Am I doing something wrong, or is this possibly a different type of encoding for track 17?

**Comment by vanbogaertetienne** [comment]
This is an image of one of the disks, including the fluxfile generated by the command above. 

[disk.zip](https://github.com/davidgiven/fluxengine/files/4668749/disk.zip)

**Comment by vanbogaertetienne** [comment]
After some troubleshooting, we found an error in the ibm decoder.

In file arch/ibm/decoder.cc, line 159, you have 
```
  /* 
 * TRS80DAM2 record:
 * flux:   XXXX-X-X-XX-XXX- = 0xf56c
 * clock:  X X - - - X X X  = 0xc7
 * data:    X X X X X - X - = 0xfa
 */
  const FluxPattern FM_TRS80DAM2_PATTERN(16, 0xf56c)
```

This should be 
```
  /* 
 * TRS80DAM2 record:
 * flux:   XXXX-X-X-XX-XXX- = 0xf56e
 * clock:  X X - - - X X X  = 0xc7
 * data:    X X X X X - X - = 0xfa
 */
  const FluxPattern FM_TRS80DAM2_PATTERN(16, 0xf56e)
```

After changing this, and recompiling, the disks decode correctly.

**Comment by davidgiven** [comment]
Nice catch --- thanks for the report and the fix (I don't have any TRS-80 disks myself to test with).
