### ISSUE TITLE
DVK MX read error "terminate called after throwing an instance of 'std::out_of_range'"

### ISSUE THREAD

**Issue by VasylSamoilov** [davidgiven/fluxengine#169]
I'm sampling a bunch of DVK MX type floppies (with greaseweazle), and while everything is more or less fine, one floppy image crashes fluxengine.
I tried resampling with 2 revs, 3 revs and 5 revs multiple times - it crashes on the same spot.
Image in question:
https://drive.google.com/drive/folders/1sja9IU6N1-4CZhgBtkLADJ32wxyoYQaO?usp=sharing

When I convert scp to flux it seems to be not quite right
78.0:  991.307 ms in 497700 input bytes and 250490 output bytes
78.1:  991.639 ms in 497744 input bytes and 250501 output bytes
79.0:  991.454 ms in 497758 input bytes and 250493 output bytes
79.1:  987.256 ms in 694678 input bytes and 347354 output bytes
80.0:  991.698 ms in 504312 input bytes and 252237 output bytes
80.1:  991.46 ms in 504316 input bytes and 252237 output bytes
81.0:  988.006 ms in 647988 input bytes and 361248 output bytes
81.1:  988.461 ms in 624298 input bytes and 354297 output bytes

c:\tools\gw>fluxengine.exe read mx -s fastiv-graphics-dvk3-5rev.flux -o fastiv-graphics-dvk3-5rev.img
Reading from: fastiv-graphics-dvk3-5rev.flux:d=0:s=0-1:t=0-79
  0.0: 993 ms in 252183 bytes
       11 records, 11 sectors; 3.97us clock (252kHz);
---skipped---
 78.0: 991 ms in 250490 bytes
       11 records, 11 sectors; 4.00us clock (250kHz);
       logical track 78.0; 2816 bytes decoded.
 78.1: 991 ms in 250501 bytes
       11 records, 11 sectors; 4.00us clock (250kHz);
       logical track 78.1; 2816 bytes decoded.
 79.0: 991 ms in 250493 bytes
       11 records, 11 sectors; 3.99us clock (251kHz);
       logical track 79.0; 2816 bytes decoded.
 79.1: 987 ms in 347354 bytes
terminate called after throwing an instance of 'std::out_of_range'
  what():  byte access out of range

**Comment by davidgiven** [comment]
That sounds very much like it's successfully reading data but provoking a bug in the decoder. I'll take a look when I get the chance (I'm currently immersed in another project) --- thanks for the report (and the scp file).

**Comment by davidgiven** [comment]
Confirmed, and fixed the crash --- it was very simple. The cause was the decoder not being able to find any data at all on track 79.1, which it wasn't expecting. However, I'm someone disturbed by the fact that every other track on the disk reads cleanly, except for 79.1, which contains nothing. Looking at the bit pattern I can see that there's data there but the track header is corrupt, and because the MX format only has one such header per track, that renders the track unreadable. At least the track seems to be blank. Is this readable on anything else?

**Comment by VasylSamoilov** [comment]
I'm not quite sure about actual hardware, as it's long gone, and it's drives and media was not top quality at the fist place. All other floppies decoded just fine.

**Comment by davidgiven** [comment]
Okay --- I think you were just unlucky with that disk. Let me know if there any more problems. Also, don't get rid of the flux files, as we may get a new (better) decoder soon, which may be able to read that last disk.
