### ISSUE TITLE
Issues with generated SCP files

### ISSUE THREAD

**Issue by keirf** [davidgiven/fluxengine#173]
I converted the Flux file here (https://github.com/kristomu/flux-analyze/blob/master/tracks/MS_Plus_disk3_warped_track.flux) to SCP using `fluxengine convert`.

The resulting image had two issues:

1. According to the SCP image spec (https://www.cbmstuff.com/downloads/scp/scp_image_specs.txt) bytes 0xC-0xF inclusive in the file header should contain a checksum when FLAGS bit 4 is clear (read-only image). It is not indicated that this can be skipped by writing a zero to this field. 

2. The INDEX flag is set, yet the first revolution of track data is not cued to the index mark. Either the partial revolution should be clipped, or the INDEX flag should be cleared.

**Comment by keirf** [comment]
My expectation is that I should be able to pass the resulting SCP file to `disk-analyse --format=ibm_mfm_hd` (https://github.com/keirf/Disk-Utilities) without it having kittens.

**Comment by davidgiven** [comment]
Yeah, the SCP exporter is completely borked (it's on my list of things to fix, see #134). Your tool will be useful for testing with, thanks --- up until now the only thing I knew of which would consume scp files was HxC, which is a fat GUI tool... I should have a fix shortly.

**Comment by keirf** [comment]
I don't currently respect the INDEX flag but I will commit a fix to do so.

**Comment by keirf** [comment]
Now done.

**Comment by davidgiven** [comment]
The scp branch should contain a fix. You have to specify the `--indexed` flag to set the INDEX bit and discard data up to the first index mark. This appears to generate SCP files which decode properly:

```
$ ./fluxengine convert fluxtoscp --indexed msplus.flux out.scp
$ LD_LIBRARY_PATH=~/src/Disk-Utilities/libdisk ~/src/Disk-Utilities/disk-analyse/disk-analyse -c ~/src/Disk-Utilities/disk-analyse/formats  --format=ibm_mfm_hd out.scp out.img
T0.0-4.0: Unformatted
T4.1: IBM-MFM HD (21 512-byte sectors, 10752 bytes)
T5.0-79.1: Unformatted*
T80.0-83.1: Unformatted
** WARNING: 150 tracks are damaged or unidentified!
```

**Comment by keirf** [comment]
Seems to work! I was surprised with `--indexed` that the generated SCP still has five revolutions. Is this a fixed value? What if the input flux doesn't have five revolutions (though I assume it did in this case)? Anyway, this looks much happier already, thanks!

**Comment by davidgiven** [comment]
The input flux file has huge amounts of data --- it looks like about 10000ms, so 50 revolutions (I've just fixed a bug where the counter overflows and it used to say -2147ms). As SCP files can only contain five revolutions, the converter just emits the first five it sees. That's not great but I'm not sure what else I can do.

**Comment by keirf** [comment]
Ah, yes, that makes sense! It was a huge flux file indeed.

Regarding SCP max revolutions, despite it being explicitly stated somewhere in the spec, elsewhere it indicates it "can vary from image to image", and in another place it states "etc etc" after the 5th revolution's TDH longwords. Plus there's really no good reason to artificially limit the format to five revolutions, I think it's another snafu in the spec. Personally I stuff more revolutions into SCP images quite happily.

**Comment by davidgiven** [comment]
Seems reasonable, but as that will require me to rewrite the export code to handle variable sizes track headers I'm going to hold off on that for now.
