### ISSUE TITLE
Remove KitProg possible?

### ISSUE THREAD

**Issue by morfeus2** [davidgiven/fluxengine#176]
I have a question (and the answer maybe could then be copied to the section "Frequently asked questions" to guide other users).
I would like to brake the board in two on the perforated line, in order to remove the KitProg and make the board the exact size as the floppy drive (it would match perfectly, without it).
If I understand correctly, by adding M-F headers it can be connected again in future, in case I need to update the firmware, but looking carefully I saw some additional tiny traces that they do not connect to the headers, so I started looking online and found this, that seems to corroborate my hipothesys:

https://community.cypress.com/thread/44280?start=0&tstart=0

So, my final question is: do you have any plan to use (in this project) other functions apart from programming? If not I suppose I can safely cut it.

**Comment by davidgiven** [comment]
Yes, there are extra traces --- it's a multilayered board. The most important is the UART, which I use for debugging. If you're just _using_ a FluxEngine then you don't need to worry about this, but if you do want to make that work you'll need to manually connect the Rx and Tx pins on the PSoC board to pins 12.6 and 12.7 on the KitProg (or possibly the other way round). See the pinout table in section A.1.3 here: https://www.cypress.com/file/157966/download
