### ISSUE TITLE
Request : Amiga : CRC Validation

### ISSUE THREAD

**Issue by ourIThome** [davidgiven/fluxengine#179]
I know we spoke previously (last year) around Amiga disks / header / CRC tables that contain the sector / CRC values for each side.  And at the time, I believe you mentioned that CRC handling would be a nightmare, as every disk format out there, does CRC handling / validation differently.

I would like to at least place this as a future future future request to see if this is possible.
Or until another tool could be used to check / validate adding to my workflow.

**Comment by ourIThome** [comment]
I dont know if this project would help in decoding header / sector CRC checksum values : 

https://github.com/RobSmithDev/ArduinoFloppyDiskReader
http://amiga.robsmithdev.co.uk/

hth.

**Comment by tingox** [comment]
Would [xdftool](https://amitools.readthedocs.io/en/latest/tools/xdftool.html) from [amitools](https://github.com/cnvogelg/amitools) help? (it verifies / reads the data, so if you are explicitly looking for CRCs it might not be useful for your usecase).

**Comment by ourIThome** [comment]
Yeah I've looked at the amitools ... I know one of the tools was good for verifying file level ... Would say something like which track was broken ... But doesn't work for non dos Amiga disks.

**Comment by davidgiven** [comment]
Belatedly: the Amiga doesn't actually have CRC checks. It's got a homegrown XOR-based checksum which can be easily fooled if there are two flipped bits in the same sector. It's terrible. https://www.techtravels.org/2010/06/re-examining-xor-data-checksum-used-on-amiga-floppies/
