### ISSUE TITLE
There's no sense retrying if you're reading a flux stream

### ISSUE THREAD

**Issue by david-schmidt** [davidgiven/fluxengine#18]
I find myself doing my Kryoflux stream reads, and then ctrl-C'ing them because I see it retrying 5 times to read the same file.  No sense doing that.  So if we find ourselves reading a flux stream off of a disk file, retries should always be 0.

**Comment by davidgiven** [comment]
Yes, they should --- I just haven't got round to adding the logic for that yet. In the meantime, try `--retries=0`.

**Comment by david-schmidt** [comment]
I do, but always after forgetting I need to do it and then starting over. :-)
