### ISSUE TITLE
zlib1g-dev required to build the client on ubuntu 18.04

### ISSUE THREAD

**Issue by pgleghorn** [davidgiven/fluxengine#190]
Hi, I think https://github.com/pgleghorn/fluxengine/blob/master/doc/building.md#building-the-client needs a small tweak in the instructions for building the client on linux.  These packages are listed:

ninja-build, libusb-1.0-0-dev, libsqlite3-dev

but I also needed zlib1g-dev (I'm using ubuntu 18.04).

(PS. Thank you for sharing this amazing project)

**Comment by Icekhaos** [comment]
Why did you clone this? I'm honestly wondering.
