### ISSUE TITLE
Add a 'read whole disk without decoding' command

### ISSUE THREAD

**Issue by davidgiven** [davidgiven/fluxengine#195]
It's not very user friendly having to specify a disk format which is then completely ignored. There should be a dedicated command for this.

**Comment by andrewferguson** [comment]
I've wondered about this. It's a bit of a pain to specify all the options based upon the type of disk, before the disk is read. With unknown disks, it's even more of a problem (even if 99% of the time you can correctly guess that disks of unknown origin are IBM PC).

Having the ability to generate a completely raw (not decoded) file and then run the client on that raw file, would be really useful. It may even be possible to automate this by writing a script that tries every possible disk format on the raw file, and from the output of this identifies what format the disk is. (Or am I over-thinking this?)

**Comment by davidgiven** [comment]
Regarding generating a raw file and running the client on it: you can do that right now. The --write-flux= option writes a copy of the raw flux data as a side effect of doing the decode.

The problem is that you can't reliably read a disk _without_ knowing the format, because you may get transient errors and have to retry, and the only way to detect these errors is via a data checksum of some kind. This was why I never added a just-read command in the first place. (This is what Kryoflux calls a 'guided read'.)

So, if you just want a flux file, you tell it to do a read of some random format, and ignore the decoded output. This turns out in practice to be incredibly confusing, hence this conversation!

**Comment by davidgiven** [comment]
There is now a proper command available --- `fluxengine rawread`.
