### ISSUE TITLE
CPM disks with 10 sectors

### ISSUE THREAD

**Issue by dallday** [davidgiven/fluxengine#196]
The actual fluxengine is working and the instructions on setting it up were well documented.

My problem is I have some CPM discs that have 10 sectors per track. using the IBM format reads the discs and says that there is 5120 byte decoded, but when writing out the .img file it seems to only output 9 sectors. Is there a way I can get it to output the 10 sectors.

Thanks
David

**Comment by davidgiven** [comment]
This is most likely because the standard IBM format uses sectors 1-9 and the CP/M format uses 0-9 --- FluxEngine can't distinguish between a sector which is missing because it shouldn't be there and a sector which is missing because of a disk error, so it has to guess. Try `--ibm-sector-id-base=0'.

**Comment by dallday** [comment]
Thanks - the answer was so simple when you know :)
process now works as I had hoped.
Well done on providing a useful tool.
