### ISSUE TITLE
Problem while compiling on Ubuntu 12.04 LTS

### ISSUE THREAD

**Issue by damonsisk** [davidgiven/fluxengine#197]
I have given up trying to get Fluxengine to work on my windows 7 box, and have moved on to Ubuntu 12.04 LTS.  But since there are no binaries, I am trying to compile it.
So far, I have found that gcc/g++ 6 gets the farthest along, and only errors out about 1/3 of the way through the ~278 files, when trying to compile through the Makefile with 'CXX lib/usb/usb.cc', and (among other things) says "lib/usb/usb.cc:37:44: error: 'libusb_strerror' was not declared in this scope".
I did install the dependencies listed as: ninja-build, libusb-1.0-0-dev, libsqlite3-dev, and they seem to be fine.
Sorry, this may be a noob error, but I have done a fair bit of coding in several languages, including c and many variants.  But compiling on Ubuntu is new to me.  Any ideas?  Thank you!

**Comment by davidgiven** [comment]
Ubuntu 12 is pretty old --- it was end-of-life'd three years ago... probably your version of libusb is too old. Is there any way you can try on a newer distribution?
