### ISSUE TITLE
Unable to write 10 sectors per track Atari ST disks

### ISSUE THREAD

**Issue by keithclark** [davidgiven/fluxengine#201]
Hi. I'm built a flux engine so I can archive and recover data from my ageing Atari ST and Amiga disk collections. At the moment I'm focusing on the Atari Stuff. The hardware/software works well and I've managed to image several different disks. What I'm struggling with is writing those images back to disk. Disks I've read with fluxengine load in an emulator but when I use fluxengine write these images back to a physical floppy disk, they don't work.

Disks are various formats (9-10 sectors per track, 80/82 tracks). Disks with executable boot sectors (demos) start loading so the first 512 bytes are writing correctly, but fail right after that. The stdout dumped when writing doesn't seem to make sense to me — I'm expecting to see a linear list of sectors being written to the disk but data seems out of order.

Am I missing something obvious?

**Comment by davidgiven** [comment]
What command line arguments are you using when writing? FluxEngine is unable to detect the disk parameters, so you have to explicitly tell it (`--preset-720` or similar). The out-of-order sectors is actually normal; they're not stored in linear order on the disk. Look up 'interleave'.

It's interesting that the first sector loads. That suggests it's _nearly_ working. It might be a side or track spacing problem, but AFAICR the Atari ST uses pretty vanilla 720kB IBM scheme disks, the same as the PC.

**Comment by keithclark** [comment]
My test file `ibm.img` is a 2 side, 80 track, 10 sector, 512 byte per sector disk image, which was extracted by flux engine.

I've tried:

```
fluxengine write ibm --ibm-preset-720 -i ibm.img
```

Flux engine logs the following to the terminal:

```
reading 80 tracks, 2 heads, 9 sectors, 512 bytes per sector, 720 kB total
Writing to: :d=0:s=0-1:t=0-79
```

This is obviously wrong as the source image is 10 sectors per track. The boot sector executes but the FAT is missing entries, which I assume is because those entries are on sector 10. The BIOS Parameter Block of the disk still reports 10 sectors per track.

Next I tried specifying the input format:
```
fluxengine write ibm --ibm-preset-720 -i ibm.img:c=80:h=2:s=10:b=512
```

This produces what I was expecting:

```
reading 80 tracks, 2 heads, 10 sectors, 512 bytes per sector, 800 kB total
Writing to: :d=0:s=0-1:t=0-79
```

The missing files now appear on the disk but it still won't run. The Atari reports it is unable to read the disk. This happens for any disk I attempt to write.

**Comment by keithclark** [comment]
I've just re-run my test. Here's the output at various stages. Hopefully this helps narrow down the issue.

### Reading original disk

The original disk is 80 tracks, 2 sides, 10 sectors, 512 bytes per sector. It has two bad sectors but still works. I'm reading it with:

```
fluxengine read ibm -s:d=0:s=0-1:t=0-79
```

Which produces:

```
Reading from: :d=0:s=0-1:t=0-79
Measuring rotational speed... 200ms

  0.0: 249.838 ms in 68608 bytes
       24 records, 12 sectors; 1.99us clock (502kHz); 
       logical track 0.0; 5120 bytes decoded.
  0.1: 249.86 ms in 65792 bytes
       24 records, 12 sectors; 2.00us clock (500kHz); 
       logical track 0.1; 5120 bytes decoded.
  1.0: 249.539 ms in 71168 bytes
       26 records, 13 sectors; 1.99us clock (502kHz); 
       logical track 1.0; 5120 bytes decoded.
  1.1: 249.544 ms in 70208 bytes
       25 records, 12 sectors; 2.01us clock (499kHz); 
       logical track 1.1; 5120 bytes decoded.
  2.0: 249.512 ms in 70272 bytes

  ...

Autodetecting output geometry
H.SS Tracks --->
0. 0 ................................................................................
0. 1 ................................................................................
0. 2 ................................................................................
0. 3 ................................................................................
0. 4 ................................................................................
0. 5 ................................................................................
0. 6 ................................................................................
0. 7 ................................................................................
0. 8 ................................................................................
0. 9 ................................................................................
1. 0 ................................................................................
1. 1 ................................................................................
1. 2 ................................................................................
1. 3 ................................................................................
1. 4 ...............................................................................B
1. 5 ........................................................................B.......
1. 6 ................................................................................
1. 7 ................................................................................
1. 8 ................................................................................
1. 9 ................................................................................

Good sectors: 1598/1600 (99%)
Missing sectors: 0/1600 (0%)
Bad sectors: 2/1600 (0%)
writing 80 tracks, 2 heads, 10 sectors, 512 bytes per sector, 800 kB total
```

This disk loads perfectly in an emulator.


### Writing the disk

I'm using:
```
fluxengine write ibm --ibm-preset-720 -i ibm.img:c=80:h=2:s=10:b=512 
```

Which produces:

```
reading 80 tracks, 2 heads, 10 sectors, 512 bytes per sector, 800 kB total
Writing to: :d=0:s=0-1:t=0-79

  0.0: 00000 : a1 a1 a1 fb 60 1e 90 49 42 4d 20 20 ad a3 e9 00  : ....`..IBM  ....
00010 : 02 02 01 00 02 80 00 40 06 f9 03 00 0a 00 02 00  : .......@........
00020 : 00 00 00 00 42 b9 00 ff 82 40 42 b9 00 ff 82 44  : ....B....@B....D
00030 : 42 b9 00 ff 82 48 42 b9 00 ff 82 4c 4e 71 4e 71  : B....HB....LNqNq
00000 : a1 a1 a1 fb f9 ff ff ff 4f 00 05 60 00 07 80 00  : ........O..`....
00010 : 09 a0 00 0b c0 00 0d e0 00 0f 00 01 11 20 01 13  : ............. ..
00020 : 40 01 15 60 01 17 80 01 19 a0 01 1b c0 01 1d e0  : @..`............
00030 : 01 1f 00 02 21 20 02 23 40 02 25 60 02 27 80 02  : ....! .#@.%`.'..
00000 : a1 a1 a1 fb 15 57 81 15 59 a1 15 5b c1 15 5d e1  : .....W..Y..[..].
00010 : 15 5f 01 16 61 21 16 63 41 16 65 61 16 67 81 16  : ._..a!.cA.ea.g..
00020 : 69 a1 16 6b c1 16 6d f1 ff 6f 01 17 71 21 17 73  : i..k..m..o..q!.s
00030 : 41 17 75 61 17 77 81 17 79 a1 17 7b c1 17 7d e1  : A.ua.w..y..{..}.
00000 : a1 a1 a1 fb c2 2a ad e2 2a ff 0f 2b ff 2f 2b b3  : .....*..*..+./+.
00010 : 42 2b b5 62 2b b7 82 2b b9 a2 2b bb c2 2b bd e2  : B+.b+..+..+..+..
00020 : 2b bf 02 2c c1 22 2c c3 42 2c c5 62 2c c7 82 2c  : +..,.",.B,.b,..,
00030 : c9 a2 2c cb c2 2c cd e2 2c cf 02 2d d1 22 2d d3  : ..,..,..,..-."-.
00000 : a1 a1 a1 fb f9 ff ff ff 4f 00 05 60 00 07 80 00  : ........O..`....
00010 : 09 a0 00 0b c0 00 0d e0 00 0f 00 01 11 20 01 13  : ............. ..
00020 : 40 01 15 60 01 17 80 01 19 a0 01 1b c0 01 1d e0  : @..`............
00030 : 01 1f 00 02 21 20 02 23 40 02 25 60 02 27 80 02  : ....! .#@.%`.'..
00000 : a1 a1 a1 fb 15 57 81 15 59 a1 15 5b c1 15 5d e1  : .....W..Y..[..].
00010 : 15 5f 01 16 61 21 16 63 41 16 65 61 16 67 81 16  : ._..a!.cA.ea.g..
00020 : 69 a1 16 6b c1 16 6d f1 ff 6f 01 17 71 21 17 73  : i..k..m..o..q!.s
00030 : 41 17 75 61 17 77 81 17 79 a1 17 7b c1 17 7d e1  : A.ua.w..y..{..}.
00000 : a1 a1 a1 fb c2 2a ad e2 2a ff 0f 2b ff 2f 2b b3  : .....*..*..+./+.
00010 : 42 2b b5 62 2b b7 82 2b b9 a2 2b bb c2 2b bd e2  : B+.b+..+..+..+..
00020 : 2b bf 02 2c c1 22 2c c3 42 2c c5 62 2c c7 82 2c  : +..,.",.B,.b,..,
00030 : c9 a2 2c cb c2 2c cd e2 2c cf 02 2d d1 22 2d d3  : ..,..,..,..-."-.
00000 : a1 a1 a1 fb 50 4f 56 34 31 20 20 20 4d 53 44 08  : ....POV41   MSD.
00010 : 00 00 00 00 00 00 00 00 00 00 53 00 fe 12 00 00  : ..........S.....
00020 : 00 00 00 00 41 55 54 4f 20 20 20 20 20 20 20 10  : ....AUTO       .
00030 : 00 00 00 00 00 00 00 00 00 00 a6 92 86 15 02 00  : ................
00000 : a1 a1 a1 fb 00 00 00 00 00 00 00 00 00 00 00 00  : ................
00010 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  : ................
00020 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  : ................
00030 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  : ................
199 ms in 55875 bytes

...
```

❓ Write chunks are in the range 55000-57000 bytes - should that match 65000-70000 range in the read?

### Re-reading the copy:

Running:
```
fluxengine read ibm -s:d=0:s=0-1:t=0-79
```

Produces:

```
Reading from: :d=0:s=0-1:t=0-79
Measuring rotational speed... 200ms
  0.0: 249.447 ms in 69824 bytes
       22 records, 11 sectors; 2.00us clock (499kHz); 
       logical track 0.0; 4608 bytes decoded.
  0.1: 249.412 ms in 66560 bytes
       22 records, 11 sectors; 1.99us clock (501kHz); 
       logical track 0.1; 4608 bytes decoded.
  1.0: 250.135 ms in 72192 bytes
       24 records, 12 sectors; 2.00us clock (500kHz); 
       logical track 1.0; 4608 bytes decoded.
  1.1: 250.112 ms in 71168 bytes
       25 records, 11 sectors; 2.00us clock (500kHz); 
       logical track 1.1; 4608 bytes decoded.
  2.0: 250.004 ms in 71168 bytes
       24 records, 12 sectors; 2.00us clock (500kHz); 
       logical track 2.0; 4608 bytes decoded.
  2.1: 249.992 ms in 71552 bytes
       26 records, 11 sectors; 2.00us clock (500kHz); 
       logical track 2.1; 4608 bytes decoded.
  ...

Autodetecting output geometry
H.SS Tracks ---> 
0. 0 ................................................................................
0. 1 ................................................................................
0. 2 ................................................................................
0. 3 ................................................................................
0. 4 ................................................................................
0. 5 ................................................................................
0. 6 ................................................................................
0. 7 ................................................................................
0. 8 ................................................................................
1. 0 ................................................................................
1. 1 ................................................................................
1. 2 ................................................................................
1. 3 ................................................................................
1. 4 ................................................................................
1. 5 ................................................................................
1. 6 ................................................................................
1. 7 ................................................................................
1. 8 ................................................................................
Good sectors: 1440/1440 (100%)
Missing sectors: 0/1440 (0%)
Bad sectors: 0/1440 (0%)
writing 80 tracks, 2 heads, 9 sectors, 512 bytes per sector, 720 kB total
```

The read of the written disk reports it as a 9 sector disk with 4608 bytes decoed vs 5120 when reading the original

**Comment by keithclark** [comment]
I've re-tried this (read, write, re-read) with a few 80 track, 9 sector, 2 side, 512 bytes per sector disks and the disks write perfectly. All my 10 sector per track disks fail as indicated above, so it looks like my issue is specific to the 10 sector per track format.

**Comment by keithclark** [comment]
I found this very useful resource on the TOS (Atari) disk format and the differences between it and the IBM standard: https://info-coach.fr/atari/software/FD-Soft.php.

**Comment by davidgiven** [comment]
Aha. The PC 720kB format is _nine_ sectors per track. So if you're writing a 10-sector-per-track image, it's all going to go horribly wrong. The write will succeed, but every sector after the ninth will be in the wrong place.

FluxEngine doesn't know out of the box how to write 800kB images --- I haven't seen them in the PC world. You can't just change the input format as there's usually a whole slew of timing settings which need changing as well. If you look at src/fe-writeibm.cc you'll see the presets (two so far). However, from the link you sent me (thanks for that, by the way!) it looks like 800kB format timings are the same as the 720kB format but with less margin at the end. So you _may_ be able to get away with just setting --ibm-sector-skew to 0123456789 and --source to :c=80:h=2:s=10:b=512. Could you try that and let me know what happens? If it works, I'll add another preset.

880kB disks will be more fiddly, but are also worth doing...

**Comment by keithclark** [comment]
The 10 sector format is fairly common for ST disks. 11 sectors is also possible but IIRC, it was prone to data loss so wasn't used very often.

I couldn't get the `--source` argument to work with `fluxengine write` — I get `Error: unknown flag '--source'`. `-i` works though.

If I run:

```
fluxengine write ibm --ibm-preset-720 --ibm-sector-skew=0123456789 -i pov41-ref.img:c=80:h=2:s=10:b=512
```

I get an error:

```
reading 80 tracks, 2 heads, 10 sectors, 512 bytes per sector, 800 kB total
Writing to: :d=0:s=0-1:t=0-79

...sector data omitted for brevity...

Error: track data overrun
```

**Comment by davidgiven** [comment]
That error means that it can't fit all that data in the 200ms per rotation on a 3.5" disk. This will be because the gaps between sectors are too big. This explains why the gap sizes in the article don't match the ones I expected; the Atari ST uses smaller gaps, and so can fit more data in.

At this point it's a matter of adjusting the --ibm-gap parameters to try and make it fit. Unfortunately, FluxEngine's idea of gaps isn't quite the same as that article's, so this will need experimentation. I'm still thinking about a better way to handle this (it ought to be possible to analyse a flux file and tell you what the gaps are).

**Comment by keithclark** [comment]
I'll generate a flux of the original disk and see if I can figure out the gaps from the data. Would you like any copies of the files?

**Comment by keithclark** [comment]
Success!!

```
fluxengine write ibm --ibm-preset-720 --ibm-sector-skew=0123456789 --ibm-emit-iam=false --ibm-gap0-bytes=0 --ibm-gap1-bytes=60 --ibm-gap3-bytes=40 -i ibm.img:c=80:h=2:s=10:b=512 
```

**Comment by keithclark** [comment]
I've tried 20 different disks images now and they all work with those values.

I was thinking about the best way to implement this into fluxengine; Adding new presets to the IBM writer sounds simple enough but are these formats relevant to IBM disks? Would be make more sense to add an Atari ST specific `fe-writeatarist.cc` that defines `--st-preset-720`, `--st-preset-800` and `--st-preset-880` flags?

Also, Atari disk images are generally identifiable by the `.st` extension so you could use that to determine the disk writer, like you do with `.adf` and `.img`. (Could format also be an flag? at the moment I have to rename my .st files to .img to make fluxengine read them)
