### ISSUE TITLE
virustotal / 541 Windows Client

### ISSUE THREAD

**Issue by ch0mik** [davidgiven/fluxengine#216]
https://www.virustotal.com/gui/file/bd0179a19c4820ab5c882c0c64ad1def5011f6bdef0516b54ca9ba460c00e55e/detection

**Comment by davidgiven** [comment]
False positive, I believe (only one engine detected it).

**Comment by ch0mik** [comment]
yeap, The Defender are most false+ av ;). I've had a few cases like this before.

**Comment by davidgiven** [comment]
Thanks for reporting it anyway!
