### ISSUE TITLE
Incomprehensible sql3 tracks 

### ISSUE THREAD

**Issue by Voldemar0** [davidgiven/fluxengine#228]
Hi !

Recently I am build FluxEngine by description on cowlark.com website.

I need to read floppy disks in a format that is NOT supported by FluxEngine.

I am using the command:
fluxengine.exe read ibm --write-flux xxx.sql3
then I use my parser on the xxx.sql3 file (ibm.img has 0 byte size).

Some tracks are decoded correctly, but they are not on their numbers: the cylinder number in the SQL does not correspond info into address fields (I have not review this problem yet).

But some tracks in the SQL are filled only with the constant 0x3F (and it compressed size 69-70 bytes). But it not be possible: is not a single impulse on the track? And no INDEX ?

Is there any reason why such a file might be generated?
And this happens only at where side=0, for side=1 no such failures.

Floppy drive is ok.
I can send sql3-files for research.
Thanks.

**Comment by davidgiven** [comment]
Re mismatched address info: that's normal for some formats; the cylinder number in the SQL file corresponds to the _physical_ location of the head, which doesn't necessarily correspond to the _logical_ cylinder encoded in the address fields. You'll see this in, for example, 40-track disks. 

The blank tracks are odd, though. It suggests that the data isn't being transferred correctly from the drive to the board. When you do the read (and remember to do `--retries=0`), does the total amount of data look reasonable --- 200 to 300ms? Also, do you have more than one drive plugged in? I've seen termination oddities in that situation.

**Comment by Voldemar0** [comment]
Thanks for your reply !

> --retries=0
I have not used this key, can this make the oddities?

Empty tracks have a slightly different size around 47100-47300 bytes. Since 0x3F is 83 ns, then 63 * 0.083 * 47200 = ~ 246809 μs.

I'm store two disk images here:
https://drive.google.com/drive/folders/1P8sODlU74WES_PzsxB3P5poDBV-dTksi?usp=sharing

The error with track numbering is more complex.
For example, the d2.sql3 image:
t0h0, t0h1 are empty.
t1h0, t1h1 - correctly decoded, address field CRC ok, data field CRC ok, but this data should be located on t5h0 and t5h1.
t2h0, t2h1 - ok, but should be located on t4h0 and t4h1.
t3h0, t3h1 - all right!
t4h0 - empty
t4h1 is ok, but should be located on t2h1.
...etc

I don't understand how such a strange address glitch occurs. Please note: the head numbers is always correct. But the tracks are numbered in reverse.
I am well knowing of this format, I can also read (and write) these discs on another device and I know that these discs are "standard" - they do not have any deviations in the recording rules.

I use the following script to retrieve data from SQL:

`#!/bin/sh

for img in *.sql3
do
  dir="${img%%.sql3}"
  [ -d "$dir" ] && continue
  mkdir "$dir"

  for t in `seq -f "%02g" 0 79`
  do
    for s in `seq 0 1`
    do
      printf "select writefile('/tmp/zdata.zl', data) from zdata where track=$t and side=$s;\n" | sqlite3 $img
      trk="${dir}/t${t}s${s}.trk"

      # This command decompress ok
      ./zlib-decompress.py /tmp/zdata.zl "$trk" || rm "$trk"

      # This command will output "CRC ERROR", but decompress be right:
      # cat GZIP-HEADER8 /tmp/zdata.zl | gunzip > "$trk"

      [ ` stat -f %z /tmp/zdata.zl ` -lt 100 ] && cp /tmp/zdata.zl ${trk}.z
      rm /tmp/zdata.zl
    done
  done
done
`

Little program zlib-decompress.py:

`
#!/usr/local/bin/python2.7

import zlib
import sys

with open(sys.argv[1], 'r') as f:
    z = f.read()
s = zlib.decompress(z)
with open(sys.argv[2], 'w') as f:
    f.write(s)
`

And then I use the pascal-program to decode the files t??h?.trk from MFM bitstream to a RAW-byte stream.
(RAW-byte stream: stream between real hardware floppy disk controller and software driver. It's internal format for our disk images).

**Comment by Voldemar0** [comment]
A solved it !! YES !

At short: power supply problem.

Some floppy disks rotate easily in an envelope, a floppy drive (Samsung SFD-321B / KE) consumes about 250 ma. However, some floppy disks rotate harder and make noise. The drive consumes about 350 ma.
When the head move to next cylinder, the voltage drops and some kind of failure occurs: FluxEngine starts to move the head back (I don't know why, FluxEngine is powered independently, from USB. The track counter increases on the screen). When the head returns to "0", FluxEngine moves it to the desired track and then the head moves to the center again, counter on screen again in sync with head position.

0x3F-fill track zero tracks are probably due to the fact that due to a power failure:
the floppy drive closes the read channel (wait for stabilize RPM), so the FluxEngine does not actually receive pulses.

15 test floppies read successfully.
Great device !

**Comment by davidgiven** [comment]
Ah, yes. The heads will be moving backwards because the low voltage will be causing missteps --- it's a problem with stepper motors. Then the head won't be pointing at any track and you'll get bad data. You might try 'fluxengine test voltages' to read the various signal levels.

If you're sorted, I'll close this issue --- feel free to reopen if necessary.
