### ISSUE TITLE
add ability to read obscure 420k IBM (MFM) 5.25" floppies?

### ISSUE THREAD

**Issue by tjhoppe** [davidgiven/fluxengine#232]
I apparently used an obscure 5.25" format on my old IBM PC system that allowed me to store a little more than 360k on an MFM 5.25" disk (420k to be exact). I thought it might be interesting for you to look at.
[Ninja-420k.zip](https://github.com/davidgiven/fluxengine/files/5962601/Ninja-420k.zip)

**Comment by ldkraemer** [comment]
$ ./fluxengine read ibm -s Ninja-420k.flux -o Ninja-420k.img -c 0-79x2 > Ninja-420k.log

  0.0: 206.529 ms in 57920 bytes
       24 records, 12 sectors; 1.68us clock (597kHz); 
       logical track 0.0; 5120 bytes decoded.
  0.1: 206.619 ms in 59648 bytes
       24 records, 12 sectors; 1.68us clock (595kHz); 
       logical track 0.1; 5120 bytes decoded.
  2.0: 206.105 ms in 60032 bytes
       24 records, 12 sectors; 1.68us clock (595kHz); 
       logical track 1.0; 5120 bytes decoded.
  2.1: 206.179 ms in 59584 bytes
       26 records, 13 sectors; 1.67us clock (598kHz); 
       logical track 1.1; 5120 bytes decoded.
  4.0: 207.123 ms in 59264 bytes
       26 records, 12 sectors; 1.67us clock (598kHz); 
       logical track 2.0; 5120 bytes decoded.
  4.1: 207.04 ms in 54912 bytes
       24 records, 12 sectors; 1.67us clock (599kHz); 
       logical track 2.1; 5120 bytes decoded.
  6.0: 207.032 ms in 57792 bytes
       24 records, 12 sectors; 1.67us clock (598kHz); 
       logical track 3.0; 5120 bytes decoded.
  6.1: 206.97 ms in 53504 bytes
       27 records, 13 sectors; 1.68us clock (595kHz); 
       logical track 3.1; 5120 bytes decoded.
  8.0: 206.731 ms in 54592 bytes
       24 records, 12 sectors; 1.68us clock (595kHz); 
       logical track 4.0; 5120 bytes decoded.
  8.1: 206.788 ms in 53760 bytes
       26 records, 13 sectors; 1.67us clock (600kHz); 
       logical track 4.1; 5120 bytes decoded.
 10.0: 206.369 ms in 55552 bytes
       24 records, 12 sectors; 1.67us clock (599kHz); 
       logical track 5.0; 5120 bytes decoded.
 10.1: 206.47 ms in 54784 bytes
       25 records, 12 sectors; 1.67us clock (600kHz); 
       logical track 5.1; 5120 bytes decoded.
 12.0: 206.268 ms in 55552 bytes
       26 records, 13 sectors; 1.67us clock (599kHz); 
       logical track 6.0; 5120 bytes decoded.
 12.1: 206.546 ms in 54912 bytes
       24 records, 12 sectors; 1.67us clock (598kHz); 
       logical track 6.1; 5120 bytes decoded.
 14.0: 207.162 ms in 55808 bytes
       30 records, 13 sectors; 1.67us clock (599kHz); 
       logical track 7.0; 5120 bytes decoded.
 14.1: 207.172 ms in 54144 bytes
       24 records, 12 sectors; 1.68us clock (596kHz); 
       logical track 7.1; 5120 bytes decoded.
 16.0: 206.885 ms in 56640 bytes
       25 records, 12 sectors; 1.68us clock (597kHz); 
       logical track 8.0; 5120 bytes decoded.
 16.1: 206.997 ms in 60096 bytes
       25 records, 12 sectors; 1.67us clock (598kHz); 
       logical track 8.1; 5120 bytes decoded.
 18.0: 206.834 ms in 59840 bytes
       24 records, 12 sectors; 1.67us clock (599kHz); 
       logical track 9.0; 5120 bytes decoded.
 18.1: 206.887 ms in 59776 bytes
       26 records, 13 sectors; 1.67us clock (599kHz); 
       logical track 9.1; 5120 bytes decoded.
 20.0: 206.59 ms in 59648 bytes
       26 records, 13 sectors; 1.66us clock (601kHz); 
       logical track 10.0; 5120 bytes decoded.
 20.1: 206.723 ms in 59328 bytes
       24 records, 12 sectors; 1.67us clock (597kHz); 
       logical track 10.1; 5120 bytes decoded.
 22.0: 206.552 ms in 59008 bytes
       24 records, 12 sectors; 1.68us clock (597kHz); 
       logical track 11.0; 5120 bytes decoded.
 22.1: 206.476 ms in 59648 bytes
       26 records, 13 sectors; 1.68us clock (596kHz); 
       logical track 11.1; 5120 bytes decoded.
 24.0: 206.436 ms in 59712 bytes
       24 records, 12 sectors; 1.68us clock (596kHz); 
       logical track 12.0; 5120 bytes decoded.
 24.1: 206.294 ms in 59584 bytes
       26 records, 13 sectors; 1.67us clock (600kHz); 
       logical track 12.1; 5120 bytes decoded.
 26.0: 206.16 ms in 59456 bytes
       26 records, 13 sectors; 1.67us clock (599kHz); 
       logical track 13.0; 5120 bytes decoded.
 26.1: 207.138 ms in 59904 bytes
       25 records, 12 sectors; 1.67us clock (598kHz); 
       logical track 13.1; 5120 bytes decoded.
 28.0: 206.999 ms in 59584 bytes
       24 records, 12 sectors; 1.68us clock (597kHz); 
       logical track 14.0; 5120 bytes decoded.
 28.1: 206.896 ms in 59904 bytes
       26 records, 13 sectors; 1.68us clock (595kHz); 
       logical track 14.1; 5120 bytes decoded.
 30.0: 206.701 ms in 52096 bytes
       26 records, 13 sectors; 1.68us clock (597kHz); 
       logical track 15.0; 5120 bytes decoded.
 30.1: 206.685 ms in 59648 bytes
       26 records, 13 sectors; 1.67us clock (600kHz); 
       logical track 15.1; 5120 bytes decoded.
 32.0: 206.57 ms in 58944 bytes
       26 records, 13 sectors; 1.67us clock (599kHz); 
       logical track 16.0; 5120 bytes decoded.
 32.1: 206.415 ms in 59072 bytes
       24 records, 12 sectors; 1.67us clock (597kHz); 
       logical track 16.1; 5120 bytes decoded.
 34.0: 206.215 ms in 59264 bytes
       26 records, 13 sectors; 1.67us clock (599kHz); 
       logical track 17.0; 5120 bytes decoded.
 34.1: 206.27 ms in 54720 bytes
       24 records, 12 sectors; 1.68us clock (597kHz); 
       logical track 17.1; 5120 bytes decoded.
 36.0: 206.892 ms in 58304 bytes
       26 records, 13 sectors; 1.68us clock (597kHz); 
       logical track 18.0; 5120 bytes decoded.
 36.1: 207.037 ms in 54912 bytes
       24 records, 12 sectors; 1.67us clock (599kHz); 
       logical track 18.1; 5120 bytes decoded.
 38.0: 206.66 ms in 58176 bytes
       25 records, 12 sectors; 1.67us clock (599kHz); 
       logical track 19.0; 5120 bytes decoded.
 38.1: 206.586 ms in 59200 bytes
       26 records, 13 sectors; 1.66us clock (602kHz); 
       logical track 19.1; 5120 bytes decoded.
 40.0: 206.453 ms in 59264 bytes
       26 records, 13 sectors; 1.66us clock (601kHz); 
       logical track 20.0; 5120 bytes decoded.
 40.1: 206.487 ms in 57536 bytes
       24 records, 12 sectors; 1.68us clock (597kHz); 
       logical track 20.1; 5120 bytes decoded.
 42.0: 206.219 ms in 56512 bytes
       24 records, 12 sectors; 1.67us clock (597kHz); 
       logical track 21.0; 5120 bytes decoded.
 42.1: 205.995 ms in 57216 bytes
       24 records, 12 sectors; 1.67us clock (599kHz); 
       logical track 21.1; 5120 bytes decoded.
 44.0: 206.927 ms in 55552 bytes
       25 records, 12 sectors; 1.67us clock (599kHz); 
       logical track 22.0; 5120 bytes decoded.
 44.1: 206.868 ms in 54720 bytes
       26 records, 13 sectors; 1.66us clock (601kHz); 
       logical track 22.1; 5120 bytes decoded.
 46.0: 206.582 ms in 58176 bytes
       24 records, 12 sectors; 1.67us clock (600kHz); 
       logical track 23.0; 5120 bytes decoded.
 46.1: 206.67 ms in 59712 bytes
       24 records, 12 sectors; 1.68us clock (597kHz); 
       logical track 23.1; 5120 bytes decoded.
 48.0: 206.296 ms in 57984 bytes
       24 records, 12 sectors; 1.68us clock (597kHz); 
       logical track 24.0; 5120 bytes decoded.
 48.1: 206.196 ms in 59968 bytes
       24 records, 12 sectors; 1.67us clock (599kHz); 
       logical track 24.1; 5120 bytes decoded.
 50.0: 206.985 ms in 60160 bytes
       26 records, 13 sectors; 1.68us clock (596kHz); 
       logical track 25.0; 5120 bytes decoded.
 50.1: 206.898 ms in 60224 bytes
       24 records, 12 sectors; 1.67us clock (600kHz); 
       logical track 25.1; 5120 bytes decoded.
 52.0: 206.773 ms in 55872 bytes
       26 records, 13 sectors; 1.67us clock (599kHz); 
       logical track 26.0; 5120 bytes decoded.
 52.1: 206.695 ms in 59776 bytes
       24 records, 12 sectors; 1.67us clock (598kHz); 
       logical track 26.1; 5120 bytes decoded.
 54.0: 206.364 ms in 56384 bytes
       24 records, 12 sectors; 1.67us clock (597kHz); 
       logical track 27.0; 5120 bytes decoded.
 54.1: 206.315 ms in 47232 bytes
       25 records, 12 sectors; 1.68us clock (595kHz); 
       logical track 27.1; 5120 bytes decoded.
 56.0: 206.3 ms in 47296 bytes
       26 records, 13 sectors; 1.68us clock (597kHz); 
       logical track 28.0; 5120 bytes decoded.
 56.1: 207.315 ms in 47424 bytes
       24 records, 12 sectors; 1.67us clock (599kHz); 
       logical track 28.1; 5120 bytes decoded.
 58.0: 206.872 ms in 47360 bytes
       24 records, 12 sectors; 1.66us clock (601kHz); 
       logical track 29.0; 5120 bytes decoded.
 58.1: 206.91 ms in 47360 bytes
       24 records, 12 sectors; 1.67us clock (598kHz); 
       logical track 29.1; 5120 bytes decoded.
 60.0: 206.528 ms in 47296 bytes
       24 records, 12 sectors; 1.67us clock (598kHz); 
       logical track 30.0; 5120 bytes decoded.
 60.1: 206.585 ms in 47296 bytes
       26 records, 13 sectors; 1.68us clock (596kHz); 
       logical track 30.1; 5120 bytes decoded.
 62.0: 206.31 ms in 47232 bytes
       24 records, 12 sectors; 1.67us clock (600kHz); 
       logical track 31.0; 5120 bytes decoded.
 62.1: 206.127 ms in 47232 bytes
       26 records, 13 sectors; 1.67us clock (599kHz); 
       logical track 31.1; 5120 bytes decoded.
 64.0: 206.935 ms in 57088 bytes
       24 records, 12 sectors; 1.66us clock (601kHz); 
       logical track 32.0; 5120 bytes decoded.
 64.1: 207.038 ms in 59840 bytes
       24 records, 12 sectors; 1.67us clock (597kHz); 
       logical track 32.1; 5120 bytes decoded.
 66.0: 206.635 ms in 59712 bytes
       24 records, 12 sectors; 1.67us clock (597kHz); 
       logical track 33.0; 5120 bytes decoded.
 66.1: 206.839 ms in 60096 bytes
       26 records, 13 sectors; 1.68us clock (596kHz); 
       logical track 33.1; 5120 bytes decoded.
 68.0: 206.409 ms in 60096 bytes
       24 records, 12 sectors; 1.67us clock (600kHz); 
       logical track 34.0; 5120 bytes decoded.
 68.1: 206.368 ms in 59968 bytes
       26 records, 13 sectors; 1.67us clock (599kHz); 
       logical track 34.1; 5120 bytes decoded.
 70.0: 207.082 ms in 59136 bytes
       26 records, 13 sectors; 1.66us clock (601kHz); 
       logical track 35.0; 5120 bytes decoded.
 70.1: 207.08 ms in 55232 bytes
       24 records, 12 sectors; 1.67us clock (598kHz); 
       logical track 35.1; 5120 bytes decoded.
 72.0: 206.746 ms in 55360 bytes
       24 records, 12 sectors; 1.67us clock (597kHz); 
       logical track 36.0; 5120 bytes decoded.
 72.1: 206.724 ms in 56064 bytes
       26 records, 13 sectors; 1.67us clock (597kHz); 
       logical track 36.1; 5120 bytes decoded.
 74.0: 206.539 ms in 55680 bytes
       24 records, 12 sectors; 1.67us clock (599kHz); 
       logical track 37.0; 5120 bytes decoded.
 74.1: 206.379 ms in 54976 bytes
       26 records, 13 sectors; 1.66us clock (602kHz); 
       logical track 37.1; 5120 bytes decoded.
 76.0: 207.095 ms in 55936 bytes
       24 records, 12 sectors; 1.67us clock (599kHz); 
       logical track 38.0; 5120 bytes decoded.
 76.1: 207.247 ms in 56640 bytes
       26 records, 13 sectors; 1.67us clock (598kHz); 
       logical track 38.1; 5120 bytes decoded.
 78.0: 206.871 ms in 57408 bytes
       24 records, 12 sectors; 1.68us clock (597kHz); 
       logical track 39.0; 5120 bytes decoded.
 78.1: 206.746 ms in 60032 bytes
       26 records, 13 sectors; 1.67us clock (599kHz); 
       logical track 39.1; 5120 bytes decoded.
``
     Tracks -> 1         2         3         
H.SS 0123456789012345678901234567890123456789
0. 0 ........................................
0. 1 ........................................
0. 2 ........................................
0. 3 ........................................
0. 4 ........................................
0. 5 ........................................
0. 6 ........................................
0. 7 ........................................
0. 8 ........................................
0. 9 ........................................
1. 0 ........................................
1. 1 ........................................
1. 2 ........................................
1. 3 ........................................
1. 4 ........................................
1. 5 ........................................
1. 6 ........................................
1. 7 ........................................
1. 8 ........................................
1. 9 ........................................
``
Good sectors: 800/800 (100%)
Missing sectors: 0/800 (0%)
Bad sectors: 0/800 (0%)
wrote 40 tracks, 2 sides, 400 kB total

**Comment by CheetahPixie** [comment]
Are we good on this?

**Comment by tjhoppe** [comment]
That command line worked great. We are good with this.

Tom

**Comment by tjhoppe** [comment]
Closing.
