### ISSUE TITLE
How do you upgrade firmware?

### ISSUE THREAD

**Issue by FozzTexx** [davidgiven/fluxengine#237]
Trying to use the latest version, it tells me I need to upgrade the firmware. Can't figure out how the command is supposed to work.

    > fluxengine upgradefluxfile
    Error: syntax: fe-upgradefluxfile <fluxfile>

    > fluxengine upgradefluxfile FluxEngine.cydsn/CortexM3/ARM_GCC_541/Release/FluxEngine.hex
    Error: database error: file is not a database

**Comment by davidgiven** [comment]
Sorry, that upgrades flux files to a new version of the client; to upgrade the board's firmware, you have to use the PSoC programmer tool (the same one you used to originally program the board).

**Comment by davidgiven** [comment]
Also, now I think of it, I didn't actually commit anything which would have upgraded the firmware version recently. If this happened via a PR and I didn't notice, then I'll need to build the new firmware and commit.

**Comment by FozzTexx** [comment]
I was hoping to avoid having to use that awful PSoC tool again. I'm just trying to see if I can master some Victor 9000 disks from images I found online.

Not a recent commit that caused the need to upgrade that I'm aware of. I haven't messed with the fluxengine in a long time. 

    Error: your FluxEngine firmware is at version 8 but the client is for version 15; please upgrade
