### ISSUE TITLE
Amiga - how to rip 5,25 DD/DS floppy ?

### ISSUE THREAD

**Issue by ch0mik** [davidgiven/fluxengine#239]
my edition of FluxEngine : [https://obrazki.elektroda.pl/9447625000_1615678160.jpg](https://obrazki.elektroda.pl/9447625000_1615678160.jpg)

It works fine with Amiga (3,5) and C64 (5,25) floppies, but I have a lot Amiga 5,25 DD/DS floppies.
How to rip 5,25 DD/DS floppy ? Amiga for 3,5" DD has s=0-1 and t=0-79 source format.

Regards
Pawel

**Comment by davidgiven** [comment]
(Oh, lovely! I used to have a Shuttle --- got rid of it when the bespoke PSU failed. I wish I'd kept the case.)

I've never heard of 5.25" Amiga disks! Chances are they're very similar to the 3.5" disks, so I'd suggest trying the same command you'd use for a 3.5" disk but on the other drive. Let me know what happens? I'll want to write this up.

**Comment by ch0mik** [comment]
I got it ;) ":d=0:s=0-1:t=0-39"

[https://obrazki.elektroda.pl/1761456000_1615679599.jpg](https://obrazki.elektroda.pl/1761456000_1615679599.jpg)

**Comment by tingox** [comment]
Based on Wikpedia's list of floppy formats https://en.wikipedia.org/wiki/List_of_floppy_disk_formats
the 5.25 inch format is 512 bytes per sector, 11 sectors and 80 tracks for a quad density drive, 40 tracks for a double density drive, giving 880 kbyte and 440 kbyte capacity per floppy. Compare with the 3.5 inch double density: it is 512 bytes per sector, 11 sectors and 80 tracks - capacity 880 kbytes per floppy. 
If your Commodore A1020 is original, it has only a double density drive, according to this http://www.zimmers.net/cbmpics/damigas2.html

**Comment by bugjacobs** [comment]
Out of curiosity and trying to get FluxEngine client software working with a GreaseWeazle, what is the command used for 3.5" dump / write ??

**Comment by davidgiven** [comment]
```
fluxengine read amiga --usb.greaseweazle=<device>
```

`<device>` should be /dev/ttyACMsomething for a Linux-ish OS, or COMsomething for a Windows-ish OS.

**Comment by CheetahPixie** [comment]
Is this solved?
