### ISSUE TITLE
Only a green light on the floppy drive when running .obj/fe-rpm

### ISSUE THREAD

**Issue by jacwib** [davidgiven/fluxengine#24]
I only get a green light on the floppy drive, along with "Error: failed to receive command reply: No such device (it may have been disconnected)"  
(had to run under sudo aswell, otherwise it just gave me "Error: cannot find the FluxEngine (is it plugged in?)")  
...im not even sure if this thing is getting power, as it seems to do the same thing without GND and VCC connected to the power ports... ive tried a not-fpga supply, aswell.  
Floppy drive model is Sony MPF920.
Tested in both usb 3 and 2 ports on 2 diffrent computers, respectively running fedora twenty-whatever-is-the-latest and opensuse leap ihavenoideaalsothelatestone.

Edit: i put in a floppy for funsies to see what would happen, i can hear something happening in the floppy drive, thats for sure. (still same error though...)

Any help would be appreciated!

(oh, and as reward... or something... for helping me out, i have a _looot_ of amiga floppies waiting to be dumped, so we could get those tested to see if they actually work. thats the whole goal of me doing this anyway, hehe. i also have some macintosh floppies, dunno if theyre modern ones or not though...)

**Comment by davidgiven** [comment]
This sounds very much like you've got the drive plugged in the wrong way round. (The symptoms are that the drive will spin continuously while the drive has power. It'll also erase the track under the head of whatever floppy disk you've got in at the time, so be careful.)

Pin 2 on the FDD connector needs to be on pin 2.7 on the board. If you are using a FDD cable, and you've soldered pins onto the top of the board, that means that the red stripe on the cable needs to be on the right and the pins plug into the _lower_ row on the connector.

If not... send me a photo?

**Comment by jacwib** [comment]
[Well, the pins _should_ be right...](https://imgur.com/1sgJ9rX) (Sorry for the unclear photo; the floppy pins are on the top if you cant tell, and the leftmost pin goes to 2.7.)
Maybe this drive has it the wrong way, or something? Maybe i just got it the wrong way?
(Oh, and dont worry. The floppies i tested with was uh, "legit" windows 3.1 install media?)

The drive seemingly isnt spinning all the time, but i'd assume it only gets power while the fpga tells it to.

**Comment by davidgiven** [comment]
Oh, yikes, you're using discrete jumpers... painful!

Floppy drives do vary, but I think yours are right (I found a datasheet: http://www.silmoh.com/pezzi2/DS/98-DS.PDF) There's a possibility that your drive has been rejumpered to act as drive 0 --- check the datasheet. It needs to be set to drive 1.

Most commands will only work if there's a disk in the drive. If there isn't one, the board will hang for a couple of seconds and then reset, leading to a confusing error message. I'm working on this. fe-testbulktransport is the only one which works without a disk. (Try it.)

Re grounds: I'm still figuring that out for myself, but I think that provided the FDD and the FluxEngine share a common ground, you'll be fine.

Also, make sure that you're running the `master` branch and not the `long` branch. I'm working on that and it doesn't work.

**Comment by davidgiven** [comment]
...actually, you said the drive doesn't spin all the time? So, if you run fe-rpm, the light comes on, the drive spins up? That suggests it's jumpered correctly, so that's a red herring.

It's a long shot, but are you sure the drive works?

**Comment by jacwib** [comment]
Well, lets see here...  
I tried switching out the cables... because what else to do while waiting for a reply? (Didn't work, obviously. Was also painful. Suprisingly easy to get back into the initial position, though.)  
There are no jumpers on this model, sadly. I'd just have to hope that its drive 0 - considering that it does nothing when i tried to add -s :d=1 i'd assume it sure is.  
.obj/fe-testbulktransport gives  
Transferred 1048576 bytes in 1307 (783 kB/s)  
Which is a good sign... i hope???
I am running the master branch, yes. (Atleast according to git status.)  
And uh, I don't actually have a clue if the drive works. I got it off some old computer at my school. I guess fe-testbulktransport giving a result is good, but well... god knows. (If not: They have plenty more drives, hehe.)

**Comment by davidgiven** [comment]
Yeah, sorry --- it _does_ sound like it's wired up correctly, but there's definitely something wrong. If the motor noises are particularly sad it could mean that the rubber band has lost its bandiness. This happens; it means the motor never gets up to speed and the drive never becomes ready, which will explain the error.

They do fail --- a lot of them were really badly made. I have a _brand new_ drive which has started making distressing noises, and has failed. Luckily I have several in stock. Let me know what happens with a second drive.

**Comment by jacwib** [comment]
Well, thanks anyway! Guess ill go check some other ones out tomorrow; ill try to bring the whole contraption with me, hehe. (Lets hope no wires fall off while im out...)
Have a good night!

**Comment by jacwib** [comment]
Aight, day two...
I managed to get my hands on a proper floppy connector (yay, no more pain!), verification that *the drive does indeed work*(!), and some heat shrink to make my garbage wiring slightly less garbage, hehe.

Ive tried plugging the floppy connector (to the pins) in every direction and tried rpm with -s :d=1 and not having that there...
14/16 result in nothing (and uh, a lot of heat. thankfully i didnt fry the board.)
1/16 result in same things as before (green light, no audible noise when no disk, noise when disk in)
1/16 result in no light and drive making (fron what i know) normal floppy drive noises continusly (while the command is being ran, like you described...)
the last one is having the pins flipped from the other one, so this is expected...

Now, im thinking one out of three things can have happened:
1) there isnt enough power (while my usb power thingy only says its drawing about 0.06 ah while doing the green spinny thing, it does say on the tin it wants an entire amp...)
2) my soldering is bad (maybe i screwed some output pin up..?)
3) the software/firmware is bad (the drive might have some weird way of communicating..?)
But i dont really have a clue, hehe.
Im gonna try to figure out a way to get more power into this thing, atleast... (any suggestions for power supplies that isnt "getting one out of a 90s pc"?)

yet another thing: when running fe-readibm -s :d=1 in the "green light" pin configuration, i can hear it going from one sound to three(?) diffrent ones, so i'd assume its trying to read more than one thing... i dont really have a clue, though...

**Comment by davidgiven** [comment]
Aha! Yes --- power! An amp's about twice as much as USB can safely supply. Does you USB power monitor show voltage? Check to see if you get any voltage drop. I had a drive that stopped working reliably below about 4.8V.

Try an external power supply. If you connect the grounds of the drive and the FluxEngine together, but _not_ the 5V line, you should be able to power the FluxEngine from USB and the drive off some other regulated supply. 3.5" drives typically only need the 5V line and you can safely leave the 12V line disconnected.

(Check inside your computer; you may already have a floppy drive power connector attached to the power supply there.)

**Comment by jacwib** [comment]
Well, the usb power monitor seems to (while doing the spinny noise green light thing) report 0.06a, 5.02v.  
And while that's not a lot of power, atleas't the voltage isn't dropping.

Well, i have to go outside anyway, so ill pick up some power supply that can output 5v at 1a, should hopefully solve it. (don't really feel like opening my computer up, its reasonably new, and i dont think i have anything to properly connect it up with anyway...)

And so i've gotten the wiring bit correct: [the power should look something like this?
](https://i.imgur.com/CQG9Cj4.png) (sorry if that is dumb or something; i really cant into electricity.)

oh, and thanks for all the help so far! i really appreciate it :)

**Comment by davidgiven** [comment]
Yes, that should work.

It's pretty forgiving; my prototype box has the FluxEngine powered from the external power supply, but this means that when it's plugged into the PC but the power supply's switched off, it tries to run the external power supply off the USB! So I have to be careful which order I turn things on and off.

**Comment by jacwib** [comment]
It werks!!11 (after an initial panic when i forgot to plug the actual floppy drive into the fluxengine...)

Aight, regarding your promised disks, do you want me to do a fe-writeflux or is "yeah this works" enough?

**Comment by davidgiven** [comment]
Excellent news! Did adding a power supply fix it? If so, I should change the documentation not to suggest USB power any more.

Also, before you start scanning all your disks: FluxEngine's Amiga output files won't work in emulators because I made the format up myself (not knowing anything about Amiga disk image standards). Normal Amiga tools won't touch them. I now know more, so I'll need to update the code.

If you have a bootable Workbench disk with you, could you scan it with this command:

```
.obj/fe-readamiga --write-flux=workbench.flux
```

...verify that it's a good read (reported as 100% good sectors), and then send me the resulting `workbench.flux` file? I'll then update my code, scan the flux file, and make sure it actually works in an emulator. I can then upgrade Amiga in the table from a dinosaur to a unicorn. (If you happen to have a _blank_ Amiga disk, formatted but with no files on it, I'd really like a flux file from that too.)

**Comment by jacwib** [comment]
Yeah, adding a power supply fixed it.

And uh, I got the two(out of three because one had two bad sectors which made the emu _ANGERY_) floppies to work in winuae actually, they appear on the workbench, but there seemingly aren't any files on there when you open one. However, i tried filemaster ("hey i wonder what this program does lol") and uh. it works!!! mod files playing!! yay!!!11231232

I'll go find a workbench disk rn, gimme a minute... (will edit post whenever im done...)

**Comment by davidgiven** [comment]
Re the disk files: oh, huh, turns out I _am_ saving completely valid ADF files. Your Workbench flux file decodes and boots in UAE. That was an easy fix! I'll document that. Ta.
