### ISSUE TITLE
Add HP-LIF format to read and write

### ISSUE THREAD

**Issue by wybren1971** [davidgiven/fluxengine#240]
Hello David,
Love your work on the fluxengine. For my old logic analyzer i have to use disk formatted to the HP-LIF standard. And i looked at your code and thought i could add a preset for writing a HP-LIF format to disk. it is just another encoding. But i'm a bit stuck now in definitions.
![image](https://user-images.githubusercontent.com/14984509/114182009-75e89480-9942-11eb-96d5-cd321b62fc49.png)

The disk format is described here: [https://www.hp9845.net/9845/projects/fdio/](url)

The preset i defined looks like this:
/* --- HP-LIF ----------------------------------------------------- */

static ActionFlag presetHPLIF(
	{ "--ibm-preset-hp-lif" },
	"Preset parameters to a HP-LIF 3.5\" 616kB HP disk.",
	[] {
		setWriterDefaultInput(":c=77:h=2:s=16:b=256");
		trackLengthMs.setDefaultValue(200);
		sectorSize.setDefaultValue(256);
		startSectorId.setDefaultValue(0);
		emitIam.setDefaultValue(false);
		clockRateKhz.setDefaultValue(250);
		idamByte.setDefaultValue(0x5554);  //??? dont know
		damByte.setDefaultValue(0x5545);  //??? dont know
		gap0.setDefaultValue(32);  // just the number of repeats
		gap1.setDefaultValue(80); //as emitIam is false this value remains unused
		gap2.setDefaultValue(22);  // just the number of repeats
		gap3.setDefaultValue(46);  // just the number of repeats
		sectorSkew.setDefaultValue("0123456789abcdef"); //?? there are 16 tracks... 
		swapSides.setDefaultValue(false);
	});

But i don't know if i did something wrong here. 
The i changed to the read part.. but i did not see how to calculate the constant FluxPattern MFM_PATTERN for the HP-LIF. 
and i couldn't find how to change the number of tracks and sectors en bytes per sector.
maybe you can add the HP-LIF format to the fluxengine client for me or give me some pointers to what to change..
i have a attached an IMD file with a image of an HP-LIF disk. 
thanks in advance
[10342-13017.zip](https://github.com/davidgiven/fluxengine/files/6285875/10342-13017.zip)

**Comment by davidgiven** [comment]
Hello --- thanks for this! It'll be good to have LIF support.

It looks like it's a simple variant of the standard IBM scheme. What happens if you try to read a LIF disk with `fluxengine read ibm`? If that works (and make sure that it has the right number of sectors) then it should make things very easy. From the image you attached, I don't think you need custom byte or patterns, so just copying the 3.5" DD preset in the writer with the minor changes you have here should work.

Of course, the only way to test it is with a real HP device to try reading disks, and unfortunately I don't have one...

**Comment by wybren1971** [comment]
If i try ./fluxengine read ibm --ibm-sector-id-base=0
{Reading from: :d=0:s=0-1:t=0-79}
it doesn't read right. It reads 0-79 tracks. while the format specifies 0-76 Cylinders (are tracks the same as Cylinders?)
the result is: Good sectors: 797/3840 (20%)
Missing sectors: 2989/3840 (77%)
Bad sectors: 54/3840 (1%)
writing 80 tracks, 2 heads, 24 sectors, 1024 bytes per sector, 3840 kB total
the 1024 bytes per sector is wrong. it should find 16 sectors with 256 bytes of data. So how can i specify this?
[HP-LIF](https://www.hp9845.net/9845/projects/fdio/)

**Comment by davidgiven** [comment]
That sounds like the disk was previously formatted, and the automatic analyser is confused by seeing some 1024-byte sectors and some 256-byte sectors. What does the sector map look like? You may need `-s :t=0-76` to limit the area being read.

**Comment by wybren1971** [comment]
I formatted an 3M DD/DS 1.0Mb disk (which was previously formatted as a 720Kb dos disk) on my logic analyzer in LIF format. I put this empty LIF formatted disk in the fluxengine and tried to read it:
"./fluxengine read ibm --ibm-sector-id-base=0 -s :t=0-76:s=0-1:d=0 --overwrite -f test.flux" 
the result is (including the sector map): 
H.SS Tracks --->
0. 0 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0. 1 .............................................................................
0. 2 .............................................................................
0. 3 .............................................................................
0. 4 .............................................................................
0. 5 .............................................................................
1. 0 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
1. 1 .............................................................................
1. 2 .............................................................................
1. 3 .............................................................................
1. 4 ...............................................................B....B.BBBBBB.
1. 5 .............................................................................
Good sectors: 762/924 (82%)
Missing sectors: 154/924 (16%)
Bad sectors: 8/924 (0%)
writing 77 tracks, 2 heads, 6 sectors, 1024 bytes per sector, 924 kB total
I don't know how i can force fluxengine to read 77 tracks with a forced sector size of 256bytes. It should know from the ID-field what the number of cylinder, head, sector and length is..
I include the produced Flux file: test.flux
[test.zip](https://github.com/davidgiven/fluxengine/files/6296872/test.zip)

**Comment by davidgiven** [comment]
That's found five sectors per track, numbered 1..5. (Your use of `--ibm-sector-id-base=0` has forced it to assume that sector 0 exists, which is why it's reading as 6 sectors per track, but this disk doesn't have a sector 0.) That's definitely not the LIF you described to me above. I think instead it's the format described at the bottom of this page: https://www.rudiswiki.de/wiki9/HP1652InverseAssembler

It's still the IBM format, so FluxEngine should have no problem reading and writing them with the write options.

**Comment by wybren1971** [comment]
David, you are absolutely right. Silly me. I tried to read the disk with: ./fluxengine read ibm -s :t=0-76:s=0-1:d=0 -o testhplif.img
This resulted in de following sector map:
H.SS Tracks --->
0. 0 .............................................................................
0. 1 .............................................................................
0. 2 .............................................................................
0. 3 .............................................................................
0. 4 .............................................................................
1. 0 .............................................................................
1. 1 .............................................................................
1. 2 .............................................................................
1. 3 .............................................................................
1. 4 .............................................................................
Good sectors: 770/770 (100%)
Missing sectors: 0/770 (0%)
Bad sectors: 0/770 (0%)
writing 77 tracks, 2 heads, 5 sectors, 1024 bytes per sector, 770 kB total

Everything seems to be read. Now to write a disk.
When reading fluxengine said the following:
Measuring rotational speed... 200ms
  0.0: **249.706** ms in 65088 bytes
       12 records, 6 sectors; 2.01us clock (**498kHz**); 
       logical track 0.0; 5120 bytes decoded.
This means for the write options that they should contain the following:
static ActionFlag presetHPLIF(
	{ "--ibm-preset-hp-lif" },
	"Preset parameters to a HP-LIF 3.5\" 770kB HP disk.",
	[] {
		setWriterDefaultDest(":d=0:s=0-1:t=0-76");
		setWriterDefaultInput(":c=77:h=2:s=5:b=1024");
		trackLengthMs.setDefaultValue(250);
		startSectorId.setDefaultValue(1);
                sectorSize.setDefaultValue(1024);
		clockRateKhz.setDefaultValue(500);
	});

Question is the tracklengthMs the same as the value shown while reading the disk? In this example 249.706 ms say 250ms?
and the clockrate is 500kHz (while reading the disk 498kHz?)
The resulting disk is not readable on my logic analyzer. Any Clue?

**Comment by wybren1971** [comment]
I found it. Reading the image went well. And writing is also successful with this preset:
/* --- HP-LIF ----------------------------------------------------- */

static ActionFlag presetHPLIF(
	{ "--ibm-preset-hp-lif" },
	"Preset parameters to a HP-LIF 3.5\" 770kB HP disk.",
	[] {
		setWriterDefaultDest(":d=0:s=0-1:t=0-76");
		setWriterDefaultInput(":c=77:h=2:s=5:b=1024");
		trackLengthMs.setDefaultValue(200);
		sectorSize.setDefaultValue(1024);
		startSectorId.setDefaultValue(1);
		emitIam.setDefaultValue(true);
		clockRateKhz.setDefaultValue(250);
		idamByte.setDefaultValue(0x5554);
		damByte.setDefaultValue(0x5545);
		gap0.setDefaultValue(80);
		gap1.setDefaultValue(50); //as emitIam is false this value remains unused
		gap2.setDefaultValue(22);
		gap3.setDefaultValue(44);
		sectorSkew.setDefaultValue("01234");
		swapSides.setDefaultValue(false);
	});

The disk is recognized by my logic analyzer as a LIF disk and accessible.

Thanks for the hints you gave me. You were right that i had the wrong disk format in the beginning.
Anyway, thanks again and i close the item now.
Greetings Wybren
