### ISSUE TITLE
Add support for CP/M 8" floppy (1.2 Mb)

### ISSUE THREAD

**Issue by mancausoft** [davidgiven/fluxengine#247]
We have some 8" floppy made from digital research CP/M on a Eco 1 computer 
We used fluxengine to extract data from several floppies, and I think will be nice if this format will be add to fluxengine

Description of the format:
77 track

d=0:s=0:t=0
26 sectors, 128 bytes per sector (3296 bytes)
d=0:s=1:t=0
 26 sectors, 256 bytes per sector (6656 bytes)
 
 all others:
 16 sectors, 512 bytes per sector (8192 bytes)
 
 
here an example of what we had:

 Fluxengine log
[dona01-07.zip](https://github.com/davidgiven/fluxengine/files/6369267/dona01-07.zip)
flux file output
[dona01-07.flux.zip](https://github.com/davidgiven/fluxengine/files/6369256/dona01-07.flux.zip)
file img outpput
[dona01-07.zip](https://github.com/davidgiven/fluxengine/files/6369254/dona01-07.zip)

How the file img should be:
[dona01-07.fixed.zip](https://github.com/davidgiven/fluxengine/files/6369274/dona01-07.fixed.zip)

Thanks :)

**Comment by davidgiven** [comment]
Gosh, _three_ different format zones? That's unusually exciting. It looks like it read fine, with no bad sectors, so this should be a matter of reading and writing the appropriate output image. There's no generic way to handle these non-uniform formats yet; it'd be nice if there was something...

**Comment by mancausoft** [comment]
the "correct" image i get reading each single track manually and after I remove the padding from each image and cat it together:

```
i=0
while [ $i -le 76 ]
do
./fluxengine  read ibm --hd  -s ${file}:d=0:s=0:t=${i} -o ${i}-0.img > /dev/null
./fluxengine  read ibm --hd  -s ${file}:d=0:s=1:t=${i} -o ${i}-1.img > /dev/null
((i++))
done
```
 
 i found some wired (for me) padding that happens... maybe is correct but look wired to me:
 d=0:s=0:t=0
0-0.img data start from: 0x00000000
d=0:s=1:t=0
0-1.img data start from:  00001A00

d=0:s=0:t=1
1-0.img: data start from: 0x00002000
d=0:s=1:t=1
1-1.img data start from: 0x00006000 (i was expecting 0x00004000 )
d=0:s=0:t=2
2-0.img: data start from: 0x00004000 (i was expecting 0x00006000 )
d=0:s=1:t=2
2-1.img: data start from: 0x0000A000 (i was expecting 0x00008000 )

**Comment by davidgiven** [comment]
Yes, the padding is there because FluxEngine doesn't know how big the tracks are _supposed_ to be, and so it takes the maximum seen sector, side, track etc as the size.

**Comment by mancausoft** [comment]
yes i read about that in documentation.
I don't understand how this padding is calculated... i mean why i for  d=0:s=1:t=1 the data start from  0x00006000 
instead of 0x00004000
before s=1:t=1 we have only 3 track  so i was expecting a padding of  24576 * 3 that is... o wait is correct  24576

So the problem is the d=0:s=0:t=2 we have 4 track before and should be 8192 * 4 = 32768, so 0x00008000

So reading  d=0:s=0:t=2 fluxengine read only sector 0 and think is only 1 sector and "calculate"  8192 * 2... that make sense now :+1:

**Comment by davidgiven** [comment]
The new version, which I'm working on in the `protobuf` branch if you want to look, now supports these mixed-mode disks properly; there's a `eco1` profile which when I read the flux file you gave me, produces an identical image to your `dona01-07.fixed.zip` image. Thanks very much for including these --- it's exactly what I need!

Can you point me at any more information on the Eco1 which I can include in the documentation? All I can really find is that it's Italian, runs CP/M, and is extremely brown.

**Comment by davidgiven** [comment]
This change has now been merged into the master branch.

**Comment by mancausoft** [comment]
Unfortunately i don't have documentation about that computer, we get only floppy to read.
But from internet i can see:
Technical data: Z80A, 64KB RAM, up to 8 KB EPROM, 1 or 2 RS232 serial lines, 1 parallel output for printer, 12 "high resolution 24x80 video, separate keyboard, 2 floppy disks (2.4 MB) or hard disk up to 10MB + 1.2MB floppy.

,the ECO1 systems adopt as basic software the most classic of standards: operating system CP/M 2.2 original from DIGITAL RESEARCH, integrated by all languages ​​and compilers available from MICROSOFT

If i will found more data i will write it
