### ISSUE TITLE
writeflux doesn't work

### ISSUE THREAD

**Issue by FozzTexx** [davidgiven/fluxengine#254]
When I try to writeflux, it just crashes:

    terminate called after throwing an instance of 'std::runtime_error'
      what():  Attempt to access uninitialised flag
    Abort

**Comment by davidgiven** [comment]
Oops. Thanks for the report. Fixing.

**Comment by FozzTexx** [comment]
It doesn't crash anymore and I'm able to write out a flux file, but the written floppy is unreadable. I'm not sure if the problem is with writing or with conversion from the scp. I'm using a 360k 5.25" drive. I'm attaching some images for the Commodore 64. The .scp file is not a copy from a disk, I created it from a d64. The .flux was converted from the .scp with fluxengine. The flux-test.flux was read back in after failing to read on a real Commodore drive. If I write out the .scp to disk using a SuperCardPro the disk does read fine on a real Commodore drive.

[flux-test.zip](https://github.com/davidgiven/fluxengine/files/6461935/flux-test.zip)

**Comment by davidgiven** [comment]
So I can see that the input flux file (goonies.flux?) contains tracks 0-39, which is only the first half of the disk, but luckily you're using a 40-track drive and (presumably) not using the `--40-track` option so that should sort itself out. (FluxEngine uses 80-track numbering throughout so the tracks on a 40-track disk should be in 0, 2, 4, 6 etc.) Also, each track contains 199ms of data. Your 360kB 5.25" drive spins at 300rpm and not 360rpm, right?

I don't have a 360kB 5.25" drive so I tried writing it to a 3.5" drive, which spins at 300rpm, and it _mostly_ worked when reading back with FluxEngine --- I got increasing numbers of bad sectors on the higher tracks, but the lower ones worked fine. What happens when you try to read the written 5.25" disk with FluxEngine?

**Comment by FozzTexx** [comment]
Yes, the 360k drive is 300 RPM. The original scp file contains only 35 tracks, with the other 5 empty and all tracks for side B/1 empty. While the scp format has a flag to mark a disk as single sided, it doesn't work and putting in empty tracks is the way the Windows scp program does it. The command I am using to write the converted file is:

    fluxengine writeflux -s goonies.flux:t=0-34

If I try to include :s=0 in then it complains and tells me that side 1 is missing. Same if I try to use --40-track.

The command I just tried to read back in the goonies.flux as created above is:

    fluxengine read c64 --40-track -o goonies-flux-test.d64

and I end up with a 0 byte goonies-flux-test.d64 file. Without the --40-track flag it tries to read 80 tracks from a 40 track drive.

I'm unable to create a new flux image from the physical floppy with fluxengine because I cannot find the right combination of arguments that will make it stop reading at track 40 (or only read tracks 0-34) and I have to interrupt it and I get no output.

Commands I've tried to read the disk back in as a flux file:

    fluxengine writeflux -i :s=0:t=0-34 -o goonies-flux-test.flux
    fluxengine writeflux -o goonies-flux-test.flux:s=0:t=0-34
    fluxengine writeflux -o goonies-flux-test.flux
    fluxengine writeflux --40-track -o goonies-flux-test.flux

**Comment by davidgiven** [comment]
writeflux was hacked in and is a bit of a mess, and really needs to be thrown away and replaced completely (I'm actually working on a major rearchitecture right now). What it does is that it reads all of the source, and then writes it to all of the destination. The reason why you're getting the error is that the destination defaults to `:t=0-79:s=0-1` and it's trying to find data for side 1. So, you'll want to use `fluxengine writeflux -s goonies.flux -d :t=0-34:s=0`.

Re `--40-track`: this tells the client to halve the track numbers when accessing the drive. So, from FluxEngine's perspective, tracks 0, 2, 4 end up on 0, 1, 2 on the drive. This means that FluxEngine's internal track numbering will end up consistent regardless of what kind of drive you have. scptoflux is generating the _wrong_ track numbers so this can't be used for writing, but it should work for reading.

To read from the disk and also generate a flux file, this command should work:

```
fluxengine read c64 --40-track --write-flux=out.flux -o goonies-flux-test.d64
```

I'm surprised the one you use above isn't working --- can you paste a few lines of the logging as it runs?

**Comment by FozzTexx** [comment]
It doesn't make any sense to me to halve/double track numbers when reading from a 48tpi drive. I should be able to tell it to just use the first 35-40 tracks. The drive has less tracks, it's not skipping tracks like a 96tpi drive. I would also expect to see track data in the file in the first 40 tracks of a side, not track data skipping every other track. The duplication of flags is also very confusing. It's hard to know when -d is the output or -o is the output. Same for -i or -s and input. 

    fluxengine writeflux -s goonies.flux:t=0-34:s=0
    Writing to: :d=0:s=0-1:t=0-81
      0.0: Using FluxEngine with serial number 7403020B1B0A3374
    199 ms in 49949 bytes
      0.1: Error: missing in source

    fluxengine writeflux --40-track -s goonies.flux:t=0-34
    Writing to: :d=0:s=0-1:t=0-81
      0.0: Using FluxEngine with serial number 7403020B1B0A3374
    199 ms in 49949 bytes
      0.1: 0 ms in 0 bytes
      1.0: Error: cannot write to odd physical tracks in 40-track mode

I've attached the out.flux generated from the read c64 command you gave me above. The d64 itself is still empty.

[out.zip](https://github.com/davidgiven/fluxengine/files/6468692/out.zip)

**Comment by davidgiven** [comment]
The problem with using drive numbering is that you can put the same disk in an 80-track drive, and now the tracks are in a different place. So, FluxEngine works in terms of the _position_ of the track instead.

BTW, `-s` and `-d` and source and destination disks. `-i` and `-o` are for input and output images. See "Source and destination" and "Input and output" here: http://cowlark.com/fluxengine/doc/using.html

Re the two writeflux commands: you have to tell it where to write with the `-d` option, otherwise it'll try to write to all tracks and both sides --- you can see the 'Writing to' line. Try this:

```
fluxengine writeflux -s goonies.flux -d :t=0-34:s=0
```

**Comment by FozzTexx** [comment]
> Re the two writeflux commands: you have to tell it where to write with the -d option, otherwise it'll try to write to all tracks and both sides

Since I didn't specify the destination, shouldn't the destination default to matching the source?

**Comment by davidgiven** [comment]
No, it's the other way around --- the process is driven from the destination with data being read from the source lazily. (This is only a problem with `writeflux`, because it was rapidly hacked together. The new version will have an improved architecture for this.)

**Comment by FozzTexx** [comment]
> The problem with using drive numbering is that you can put the same disk in an 80-track drive, and now the tracks are in a different place

Yes, but no. If you're reading/writing a format that isn't matched to the hardware then shuffling the tracks around should be handled during reading/writing. The track arrangement in the file shouldn't be munged to pretend to be a 96tpi source when it really did come from a 48tpi disk.

**Comment by FozzTexx** [comment]
> the process is driven from the destination with data being read from the source lazily

But I'm a lazy user and that trumps all laziness! ;-)

**Comment by davidgiven** [comment]
>Yes, but no. If you're reading/writing a format that isn't matched to the hardware then shuffling the tracks around should be handled during reading/writing. The track arrangement in the file shouldn't be munged to pretend to be a 96tpi source when it really did come from a 48tpi disk.

I'll admit to not being particularly wed to the idea --- I don't have a 40-track drive to test with, so I don't actually get to try it in real life. But it's not a simple as you're making out: for example, right now I'm reading 48tpi disks by doing a _96tpi_ read on them, with two reads per 48tpi track... and sometimes the two reads are different. I'll agree it's surprising, and surprising things are bad in computing. It needs work. But that's where it is right now.
