### ISSUE TITLE
Installing?

### ISSUE THREAD

**Issue by mole42** [davidgiven/fluxengine#261]
Hi, I've tried to install Fluxengine on an older XP machine and a newer Macintosh and failed miserably at both.
I've successfully programmed the Cypress gadget but MSYS2 seems elusive for XP and Hombrew doesn't install on my Mac.

Any ideas?

**Comment by davidgiven** [comment]
Hmm, XP. There's a name I haven't heard for a long time.

There are precompiled binaries in each release; look for the 'fluxengine.zip' file on the release page. That _should_ work. I haven't tried them on XP, though. Let me know if it works.

**Comment by mole42** [comment]
Hmmm. Using the precmpiled binary on XP I get this message: "The procedure entry point CancelIoEx could not be located in the dynamic link library KERNEL32.dll" I don't know Windows well enough to make anything of that!

**Comment by davidgiven** [comment]
It's hard to find definitive documentation, but it looks like mingw-w64 dropped support for XP in 2019. It's possible that the older mingw project (not the same thing!) still has support for it, if you were to compile the FluxEngine binary yourself on it. https://sourceforge.net/projects/mingw/ Or, maybe, Cygwin (haven't tried this).

Re OSX, I'm not enough of a Max expert to know why Homebrew won't work on it, but it's not been particularly reliable IME...

**Comment by davidgiven** [comment]
There is, BTW, now a proper OSX installer.
