### ISSUE TITLE
Cannot make fluxengine on windows 10 read image from file

### ISSUE THREAD

**Issue by cm631** [davidgiven/fluxengine#265]
Hi,

I am trying to decode some 5.25" images taken with greaseweazle, however I cannot make fluxengine read from file. It always returns Error: unrecognised flux filename extension. I am on Windows 10. Tried with relative and absolute paths. I even tried to do it from the cygwin shell. It seems I am doing something totally wrong. 

>fluxengine.exe read ibm -s norton.scp
Reading from: norton.scp:d=0:s=0-1:t=0-79
Error: unrecognised flux filename extension

**Comment by davidgiven** [comment]
So what's happening here is that I just reworked the CLI, and I think you've got the old version of the client but are looking at the documentation for the new client --- the old client didn't support `.scp` files like this. You want the latest development build from here: https://github.com/davidgiven/fluxengine/releases/tag/dev

**Comment by cm631** [comment]
This is what I initially tried (the latest build). However it gave me no output no matter if I provide any attributes, e.g. 
"> .\fluxengine.exe read --help" gives no output. That's why I tried few of the previous builds, e.g. 580: https://github.com/davidgiven/fluxengine/releases/tag/FluxEngine-Windows-client-version-580 . But then I get "Error: unrecognised flux filename extension".

**Comment by davidgiven** [comment]
That's not right. To confirm: when you run `fluxengine.exe read`, with no other parameters, you get no output?

**Comment by cm631** [comment]
Yes, I get no output. What I did now is to get the sources and compile them in Linux environment (actually Windows 10 Subsystem for Linux). And it works fine. I managed to convert some scp flux files to .img. Of course I had to sort out some dependencies by installing the required packages like g++, make, the libraries you mention here http://cowlark.com/fluxengine/doc/building.html and few other missing libraries in the default installation of Windows Subsystem for Linux.
Something which may point to the cause of the issue with fluxengine.exe:
I also decided to give a try of fluxengine.exe in the Windows Subsystem for Linux. (WSL) The latest build throws System Errors
 about the following missing libraries:
libstdc++-6.dll
libwinpthread-1.dll
libprotobuf.dll
libgcc_s_dw2-1.dll
![Capture](https://user-images.githubusercontent.com/84720496/119582848-0d5c5680-bdce-11eb-8c26-4ddc16729cdb.PNG)
Build 580 however runs fine under WSL, but still produces "Error: unrecognised flux filename extension" when I try to convert .scp file.

**Comment by davidgiven** [comment]
I don't know anything about WSL, and have neither tried the Windows binary on it or tried to build it with it. However, in a recent update it does appear that I accidentally removed the option to produce static binaries, resulting in completely broken executables. I didn't spot this on my own system because, of course, I had the development pages installed...

Please try again with the latest development release.
