### ISSUE TITLE
Greaseweazle define com port

### ISSUE THREAD

**Issue by rdpeake** [davidgiven/fluxengine#275]
Howdy,

I'm having trouble getting flux engine to talk to greaseweazle hardware. I read through the documentation which states to replace the driver on windows, however doing this doesn't result in a COM port being assigned to the greaseweazle, which is how flux engine is told that their is a greaseweazle to talk to.

Using the standard driver, which does get a com port assigned, trying to do anything using fluxengine simply hangs with no errors displayed. I did spot a comment on an issue that the way greaseweazle is handled has been changed from what it was, so not sure if i should just revert to an earlier build, or if this is something that is in the works of being fixed?

**Comment by rdpeake** [comment]
The second part of my comment was done with the original driver restored - which is where it hangs and nothing gets printed to the screen at all

**Comment by rdpeake** [comment]
it could be an issue with mine as well - but it at least responds to `gw info` command

**Comment by natesiteweb** [comment]
This is what happens with mine as well. I've just been using fluxengine version 580 in the meantime, and using greaseweazle 0.22 on bluepill.

**Comment by rdpeake** [comment]
does it need replacement driver, or the usb cla?

**Comment by rdpeake** [comment]
hmm, looks like 580 doesn't have 1581 or 1541 support on it

**Comment by natesiteweb** [comment]
I use fluxengine 580 with greaseweazle 0.22 on a blue pill, and I use the replacement WinUSB driver.

**Comment by davidgiven** [comment]
If you look in the 'greaseweazle' branch, there should be a version which works on Linux; I'm still trying to make it work on Windows. (Turns out the serial port wasn't being set up correctly.)

If you're still using the old 580 build, 1541 support is called `c64` and 1581 support is handled by the standard `ibm` reader.

**Comment by rdpeake** [comment]
yeah, i spotted the 1541 support (though had to dig into the code to find the correct flag for writing 1581. successfully wrote a disk just then.

**Comment by davidgiven** [comment]
Okay, this should be actually fixed now, for real. Thanks very much for the report!
