### ISSUE TITLE
OSX build error missing tests/kryoflux.cc

### ISSUE THREAD

**Issue by beyond-circuits** [davidgiven/fluxengine#28]
When building on OSX I get the following error message:

meson.build:183:0: ERROR:  File tests/kryoflux.cc does not exist.

If I remove the line from meson.build then everything seems to build. Is the file missing from the tests or is this not needed anymore?

Thanks,

-Pete

**Comment by davidgiven** [comment]
Something went wrong with my VCS and the file never got pushed to github. It should be fixed now. Sorry about that.

Memo to self: this is why you always work in a branch...

**Comment by beyond-circuits** [comment]
Looks good now. Thanks for the fast response.

-Pete
