### ISSUE TITLE
Add .jv3 write support

### ISSUE THREAD

**Issue by scotia70** [davidgiven/fluxengine#281]
Hi,
as per the subject, specifying .jv3 fails with
```
Error: unrecognised image filename 'trs80.jv3'
```
NB: the command I ran was suggested by http://cowlark.com/fluxengine/doc/disk-trs80.html
Thanks

**Comment by davidgiven** [comment]
Yup, that's a documentation bug --- the JV3 format is only supported when writing, not reading. You'll have to read as .img and then convert. Thanks for reporting.

**Comment by scotia70** [comment]
It's not only mentioned in the GitHub page (as a dinosaur), but you have a page dedicated to reading TRS-80 disks at http://cowlark.com/fluxengine/doc/disk-trs80.html

This is my main intended use for FluxEngine.  Can you please recommend any extra settings that the IBM decoder might need and point me in the right direction to convert the image (other than the SD knob)?  I assume I would use "read" and not "rawread". I would like the converted image to be .DSK but if I get .JV3 I think I can convert from that too.

Many thanks for a great project.  I'm looking forward to repurposing my new CY8 once I've read all my 40 year old floppies and flippies.

**Comment by scotia70** [comment]
Hi,
post #2 above says that TRS-80 is supported for writing only, not reading.  This is in conflict with https://github.com/davidgiven/fluxengine/issues/198#issuecomment-738074049 which says that writing is unsupported.

Can you please clarify which mode is and isn't supported?  Thanks.

**Comment by davidgiven** [comment]
The `.jv3` format is only supported when writing; however you can still write TRS-80 disks if you can get then in a different format (`.img` for preference). They're just variants of the standard IBM scheme although getting the sector ID right for the directory tracks is going to be difficult --- you might need to write them in two passes. This hasn't been tested as I don't have any hardware for this.

**Comment by scotia70** [comment]
Thanks David.  I don't intend (at least in the short term) to do any writing of TRS-80 disks. My current intent is to read.  Can you please recommend how to do the conversion from an IBM img to a TRS-80 img?  Thanks

**Comment by davidgiven** [comment]
There's no specific IBM or TRS-80 img file format --- they're just all the sectors, in a row. Assuming your emulator wants JV3 files the easiest way to do the conversion is probably with the libdsk tools. I don't know what platform you're on but after installing them you'll probably want a command like:

```
dsktrans -itype raw -otype jv3 file.img file.jv3
```

I'll try and get native JV3 support added; it's not very complex.

**Comment by scotia70** [comment]
Thanks David.  JV3 support for reads would be great.  I downloaded and compiled dsktrans on FreeBSD and also grabbed the compiled Windows binaries but unfortunately any IMG from FluxEngine I present to dsktrans causes a segmentation fault (on both FreeBSD and Windows).
