### ISSUE TITLE
Programmed Cypress CY8CKIT-059, trying to execute in Debian 9.x Linux

### ISSUE THREAD

**Issue by ldkraemer** [davidgiven/fluxengine#284]
After I programmed the Cypress I did a verify  The verify is shown here in mycypress.txt file.
I assume it programmed correctly.

Verify Finished at 4:09:10 PM                                   	| 
                                                                	| Succeeded
                                                                	|  Verified  Blocks: 1024
                                                                	|  Failed Blocks:       0
                                                                	|  Protected Blocks:    0
                                                                	|  ----------------------
                                                                	|  Total           : 1024
                                                                	| Verifying 262144 bytes of FLASH
                                                                	| Verifying of 'User NVL' area Succeeded
Device set to CY8C5888LTI-LP097 at 4:08:43 PM                   	| 262144  FLASH bytes
Device Family set to CY8C5xxxLP at 4:08:43 PM                   	| 
                                                                	| Automatically Detected Device: CY8C5888LTI-LP097
                                                                	| JtagID: 2E 16 10 69
Verify Requested at 4:08:43 PM                                  	| 
Memory Types Load from HEX Finished at 4:06:29 PM               	| 
Memory Types Load from HEX Requested at 4:06:29 PM              	| 
Program Finished at 4:05:30 PM                                  	| 
                                                                	| Programming Succeeded
                                                                	| Doing Checksum
                                                                	| Doing Protect
                                                                	| Programming of Flash Succeeded
                                                                	| > Transfer rate: 9.32 KB/sec. 21504 bytes transferred (84 blocks x 256 bytes) in 2254 ms
                                                                	| Programming of Flash Starting...
                                                                	| Erase Succeeded
Device set to CY8C5888LTI-LP097 at 4:05:27 PM                   	| 262144  FLASH bytes
Device Family set to CY8C5xxxLP at 4:05:27 PM                   	| 
                                                                	| Automatically Detected Device: CY8C5888LTI-LP097
                                                                	| JtagID: 2E 16 10 69
Program Requested at 4:05:27 PM                                 	| 
Successfully Connected to KitProg/111B0986000E0400 at 4:05:22 PM	| KitProg Version 2.21
Opening Port at 4:05:20 PM                                      	| 
Connected at 4:05:20 PM                                         	| KitProg/111B0986000E0400
Memory Types Load from HEX Finished at 4:05:10 PM               	| 
Device set to CY8C5888LTI-LP097 at 4:05:10 PM                   	| 262144  FLASH bytes
Device Family set to CY8C5xxxLP at 4:05:10 PM                   	| 
Memory Types Load from HEX Requested at 4:05:10 PM              	| 
Active HEX file set at 4:05:10 PM                               	| C:\Users\user\Downloads\fluxengine\fluxengine-master\fluxengine-master\FluxEngine.cydsn\CortexM3\ARM_GCC_541\Release\FluxEngine.hex
                                                                	|  
                                                                	| Users must be aware that the following PSoC device should not be powered or programmed at 5V. Doing so will cause damage to the devices: CY8C6xxx, CYRF89xxx
Session Started at 4:05:09 PM                                   	| PPCOM Version 42.0

I plugged the programmed Cypress Fluxengine in to a Debian 9.x - USB 2.0 Port

Before Plugging in Fluxengine

$ lsusb
Bus 004 Device 005: ID 058f:9540 Alcor Micro Corp. AU9540 Smartcard Reader
Bus 004 Device 004: ID 0461:4dce Primax Electronics, Ltd 
Bus 004 Device 003: ID 046d:c52f Logitech, Inc. Unifying Receiver
Bus 004 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
larry@debian:~/Downloads/fluxengine/fluxengine-master$

After Plugging in Fluxengine 
larry@debian:/home/user/Downloads/fluxengine/fluxengine-master$ lsusb
Bus 004 Device 005: ID 058f:9540 Alcor Micro Corp. AU9540 Smartcard Reader
Bus 004 Device 004: ID 0461:4dce Primax Electronics, Ltd 
Bus 004 Device 003: ID 046d:c52f Logitech, Inc. Unifying Receiver
Bus 004 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 006: ID 1209:6e00 Generic                    <<----------------------------This USB Device is the Cypress Fluxengine
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
larry@debian:/home/user/Downloads/fluxengine/fluxengine-master$

Bus 001 Device 006: ID 1209:6e00 Generic 

$ lsusb -v -s 001:006

Bus 001 Device 006: ID 1209:6e00 Generic 
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass          255 Vendor Specific Class
  bDeviceSubClass         0 
  bDeviceProtocol         1 
  bMaxPacketSize0         8
  idVendor           0x1209 Generic
  idProduct          0x6e00 
  bcdDevice            0.01
  iManufacturer           2 
  iProduct                1 
  iSerial               128 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           46
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           4
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              1 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval              10
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval              10
larry@debian:/home/user/Downloads/fluxengine/fluxengine-master$

Before Plugging in my Fluxengine 

$ usb-devices

T:  Bus=01 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=480 MxCh= 2
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=1d6b ProdID=0002 Rev=04.09
S:  Manufacturer=Linux 4.9.0-15-amd64 xhci-hcd
S:  Product=xHCI Host Controller
S:  SerialNumber=0000:26:00.0
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub

T:  Bus=02 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=5000 MxCh= 2
D:  Ver= 3.00 Cls=09(hub  ) Sub=00 Prot=03 MxPS= 9 #Cfgs=  1
P:  Vendor=1d6b ProdID=0003 Rev=04.09
S:  Manufacturer=Linux 4.9.0-15-amd64 xhci-hcd
S:  Product=xHCI Host Controller
S:  SerialNumber=0000:26:00.0
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub

T:  Bus=03 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=480 MxCh= 3
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=1d6b ProdID=0002 Rev=04.09
S:  Manufacturer=Linux 4.9.0-15-amd64 ehci_hcd
S:  Product=EHCI Host Controller
S:  SerialNumber=0000:00:1a.0
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub

T:  Bus=03 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#=  2 Spd=480 MxCh= 6
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=8087 ProdID=0024 Rev=00.00
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub

T:  Bus=04 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=480 MxCh= 3
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=1d6b ProdID=0002 Rev=04.09
S:  Manufacturer=Linux 4.9.0-15-amd64 ehci_hcd
S:  Product=EHCI Host Controller
S:  SerialNumber=0000:00:1d.0
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub

T:  Bus=04 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#=  2 Spd=480 MxCh= 8
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=8087 ProdID=0024 Rev=00.00
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub

T:  Bus=04 Lev=02 Prnt=02 Port=00 Cnt=01 Dev#=  3 Spd=12  MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS= 8 #Cfgs=  1
P:  Vendor=046d ProdID=c52f Rev=22.01
S:  Manufacturer=Logitech
S:  Product=USB Receiver
C:  #Ifs= 2 Cfg#= 1 Atr=a0 MxPwr=98mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=01 Prot=02 Driver=usbhid
I:  If#= 1 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid

T:  Bus=04 Lev=02 Prnt=02 Port=03 Cnt=02 Dev#=  4 Spd=480 MxCh= 0
D:  Ver= 2.00 Cls=ef(misc ) Sub=02 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=0461 ProdID=4dce Rev=00.19
S:  Manufacturer=Primax Electronics Ltd.
S:  Product=HP HD Webcam [Fixed]
S:  SerialNumber=PMX02
C:  #Ifs= 2 Cfg#= 1 Atr=80 MxPwr=500mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=0e(video) Sub=01 Prot=00 Driver=uvcvideo
I:  If#= 1 Alt= 0 #EPs= 0 Cls=0e(video) Sub=02 Prot=00 Driver=uvcvideo

T:  Bus=04 Lev=02 Prnt=02 Port=07 Cnt=03 Dev#=  5 Spd=12  MxCh= 0
D:  Ver= 1.10 Cls=00(>ifc ) Sub=00 Prot=00 MxPS= 8 #Cfgs=  1
P:  Vendor=058f ProdID=9540 Rev=01.20
S:  Manufacturer=Generic
S:  Product=EMV Smartcard Reader
C:  #Ifs= 1 Cfg#= 1 Atr=a0 MxPwr=50mA
I:  If#= 0 Alt= 0 #EPs= 3 Cls=0b(scard) Sub=00 Prot=00 Driver=(none)
larry@debian:~/Downloads/fluxengine/fluxengine-master$

After Plugging in the Fluxengine

$ usb-devices

T:  Bus=01 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=480 MxCh= 2
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=1d6b ProdID=0002 Rev=04.09
S:  Manufacturer=Linux 4.9.0-15-amd64 xhci-hcd
S:  Product=xHCI Host Controller
S:  SerialNumber=0000:26:00.0
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub

T:  Bus=01 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#=  8 Spd=12  MxCh= 0
D:  Ver= 2.00 Cls=ff(vend.) Sub=00 Prot=01 MxPS= 8 #Cfgs=  1
P:  Vendor=1209 ProdID=6e00 Rev=00.01
S:  Manufacturer=Cowlark Technologies
S:  Product=FluxEngine                    <<-----------------------------------------This USB Device is the Cypress Fluxengine
S:  SerialNumber=1B03020606092004
C:  #Ifs= 1 Cfg#= 1 Atr=80 MxPwr=100mA
I:  If#= 0 Alt= 0 #EPs= 4 Cls=ff(vend.) Sub=00 Prot=00 Driver=(none)

T:  Bus=02 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=5000 MxCh= 2
D:  Ver= 3.00 Cls=09(hub  ) Sub=00 Prot=03 MxPS= 9 #Cfgs=  1
P:  Vendor=1d6b ProdID=0003 Rev=04.09
S:  Manufacturer=Linux 4.9.0-15-amd64 xhci-hcd
S:  Product=xHCI Host Controller
S:  SerialNumber=0000:26:00.0
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub

T:  Bus=03 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=480 MxCh= 3
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=1d6b ProdID=0002 Rev=04.09
S:  Manufacturer=Linux 4.9.0-15-amd64 ehci_hcd
S:  Product=EHCI Host Controller
S:  SerialNumber=0000:00:1a.0
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub

T:  Bus=03 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#=  2 Spd=480 MxCh= 6
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=8087 ProdID=0024 Rev=00.00
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub

T:  Bus=04 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=480 MxCh= 3
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=1d6b ProdID=0002 Rev=04.09
S:  Manufacturer=Linux 4.9.0-15-amd64 ehci_hcd
S:  Product=EHCI Host Controller
S:  SerialNumber=0000:00:1d.0
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub

T:  Bus=04 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#=  2 Spd=480 MxCh= 8
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=8087 ProdID=0024 Rev=00.00
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub

T:  Bus=04 Lev=02 Prnt=02 Port=00 Cnt=01 Dev#=  3 Spd=12  MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS= 8 #Cfgs=  1
P:  Vendor=046d ProdID=c52f Rev=22.01
S:  Manufacturer=Logitech
S:  Product=USB Receiver
C:  #Ifs= 2 Cfg#= 1 Atr=a0 MxPwr=98mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=01 Prot=02 Driver=usbhid
I:  If#= 1 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid

T:  Bus=04 Lev=02 Prnt=02 Port=03 Cnt=02 Dev#=  4 Spd=480 MxCh= 0
D:  Ver= 2.00 Cls=ef(misc ) Sub=02 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=0461 ProdID=4dce Rev=00.19
S:  Manufacturer=Primax Electronics Ltd.
S:  Product=HP HD Webcam [Fixed]
S:  SerialNumber=PMX02
C:  #Ifs= 2 Cfg#= 1 Atr=80 MxPwr=500mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=0e(video) Sub=01 Prot=00 Driver=uvcvideo
I:  If#= 1 Alt= 0 #EPs= 0 Cls=0e(video) Sub=02 Prot=00 Driver=uvcvideo

T:  Bus=04 Lev=02 Prnt=02 Port=07 Cnt=03 Dev#=  5 Spd=12  MxCh= 0
D:  Ver= 1.10 Cls=00(>ifc ) Sub=00 Prot=00 MxPS= 8 #Cfgs=  1
P:  Vendor=058f ProdID=9540 Rev=01.20
S:  Manufacturer=Generic
S:  Product=EMV Smartcard Reader
C:  #Ifs= 1 Cfg#= 1 Atr=a0 MxPwr=50mA
I:  If#= 0 Alt= 0 #EPs= 3 Cls=0b(scard) Sub=00 Prot=00 Driver=(none)

$ ./fluxengine test bandwidth
Error: cannot open USB device: Access denied (insufficient permissions)

The Fluxengine does not show up as:  /dev/ttyU*, /dev/ttyA* as is typical for Linux.

How do I proceed?

Thanks.

Larry

**Comment by davidgiven** [comment]
The 'cannot open USB device' error sounds like a permissions error --- try running it as root. (It's possible to configure udev so you don't need this.) Also, try `sudo lsusb` and see if it shows up with a proper name there. The listing of the USB descriptors given by `lsusb -v` looks right, but there are some strings in the descriptor table which actually declare it as a Cowlark Technologies FluxEngine, and it's odd they don't seem to be present.

**Comment by ldkraemer** [comment]
Here are the results using sudo and as ROOT.  I also included my groups and the permissions of fluxengine.


AS SUDO

$ sudo lsusb
Bus 004 Device 005: ID 058f:9540 Alcor Micro Corp. AU9540 Smartcard Reader
Bus 004 Device 004: ID 0461:4dce Primax Electronics, Ltd 
Bus 004 Device 003: ID 046d:c52f Logitech, Inc. Unifying Receiver
Bus 004 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 1209:6e00 Generic 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

$ sudo lsusb -v

Bus 001 Device 002: ID 1209:6e00 Generic 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass          255 Vendor Specific Class
  bDeviceSubClass         0 
  bDeviceProtocol         1 
  bMaxPacketSize0         8
  idVendor           0x1209 Generic
  idProduct          0x6e00 
  bcdDevice            0.01
  iManufacturer           2 Cowlark Technologies
  iProduct                1 FluxEngine
  iSerial               128 1B03020609162004
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           46
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           4
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              1 FluxEngine
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval              10
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval              10
Device Status:     0x0000
  (Bus Powered)


AS ROOT

$ su -
Password: 
root@debian:/home/larry/Downloads/fluxengine/fluxengine-master#

# lsusb
Bus 004 Device 005: ID 058f:9540 Alcor Micro Corp. AU9540 Smartcard Reader
Bus 004 Device 004: ID 0461:4dce Primax Electronics, Ltd 
Bus 004 Device 003: ID 046d:c52f Logitech, Inc. Unifying Receiver
Bus 004 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 1209:6e00 Generic 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
root@debian:/home/larry/Downloads/fluxengine/fluxengine-master#


# lsusb -v
Bus 001 Device 002: ID 1209:6e00 Generic 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass          255 Vendor Specific Class
  bDeviceSubClass         0 
  bDeviceProtocol         1 
  bMaxPacketSize0         8
  idVendor           0x1209 Generic
  idProduct          0x6e00 
  bcdDevice            0.01
  iManufacturer           2 Cowlark Technologies
  iProduct                1 FluxEngine
  iSerial               128 1B03020609162004
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           46
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           4
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              1 FluxEngine
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval              10
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval              10
Device Status:     0x0000
  (Bus Powered)



$ groups larry
larry : larry tty lp dialout cdrom floppy sudo audio dip video plugdev netdev scanner bluetooth lpadmin

-rwxr-xr-x  1 larry larry  1668504 Jun 19 18:51 brother120tool-debug
-rwxr-xr-x  1 larry larry  1140072 Jun 19 18:51 fluxengine
-rwxr-xr-x  1 larry larry  1720696 Jun 19 18:51 fluxengine-unstripped

I execute fluxengine with the ./fluxengine command from a Linux Terminal.

root@debian:/home/larry/Downloads/fluxengine/fluxengine-master# ./fluxengine test bandwidth
Transferred 1048576 bytes from FluxEngine -> PC in 1101 ms (929 kB/s)
Transferred 1048576 bytes from PC -> FluxEngine in 1739 ms (588 kB/s)


larry@debian:~/Downloads/fluxengine/fluxengine-master$ sudo ./fluxengine test bandwidth
Transferred 1048576 bytes from FluxEngine -> PC in 1099 ms (931 kB/s)
Transferred 1048576 bytes from PC -> FluxEngine in 1830 ms (559 kB/s)
larry@debian:~/Downloads/fluxengine/fluxengine-master$

Thanks.

Larry

**Comment by ldkraemer** [comment]
Why does github give the strike through lines?  This is pure ASCII text from Gedit in Linux?

**Comment by davidgiven** [comment]
Excellent --- the board is functioning (otherwise 'test bandwidth' wouldn't have worked). If you hook up a drive and do 'fluxengine rpm' with a disk in the drive you should get a result.

(github parses comments as markdown, so anything with tildes each side gets the strikethrough style. Use three backquotes to switch in and out of code mode:

```
~tilde~
```

~tilde~

**Comment by ldkraemer** [comment]
David,
OK, I have my 3.5" Floppy connected to the fluxengine (Cypress Board) with a cable that has conductors 10-16
twisted.  On;u one connector on each end of the cable.

With the drive:0 command I do not get a sample for RPM as shown here:

$ sudo ./fluxengine rpm --source drive:0
No index pulses detected from the disk. Common causes of this are:
  - no drive is connected
  - the drive doesn't have an index sensor (e.g. BBC Micro drives)
  - the disk has no index holes (e.g. reversed flippy disks)
  - (most common) no disk is inserted in the drive!

So, I tried a test with by selecting Drive 1, and that does make it work.  But why?  The DEFAULT should be set for Drive 0?


larry@debian:~/Downloads/fluxengine/fluxengine-master$ sudo ./fluxengine rpm --source drive:1
Rotational period is 200 ms (300 rpm)
larry@debian:~/Downloads/fluxengine/fluxengine-master$ sudo ./fluxengine rpm --source drive:1
Rotational period is 199 ms (301.508 rpm)
larry@debian:~/Downloads/fluxengine/fluxengine-master$ sudo ./fluxengine rpm --source drive:1
Rotational period is 199 ms (301.508 rpm)
larry@debian:~/Downloads/fluxengine/fluxengine-master$ sudo ./fluxengine rpm --source drive:1
Rotational period is 200 ms (300 rpm)
larry@debian:~/Downloads/fluxengine/fluxengine-master$ sudo ./fluxengine rpm --source drive:1
Rotational period is 200 ms (300 rpm)
larry@debian:~/Downloads/fluxengine/fluxengine-master$

So, at least it is working.

Larry

**Comment by ldkraemer** [comment]
David,
I got to looking at how Keir Frasier has GreaseWeazle configured for /etc/udev/rules.d and used
his idea to fix the sudo usage problem.  It might not be the same way you do it but this also works.

larry@debian:~/Downloads/fluxengine/fluxengine-master$ ls -alt 49-fluxengine.rules
-rw-r--r-- 1 larry larry 615 Jun 23 16:53 49-fluxengine.rules
larry@debian:~/Downloads/fluxengine/fluxengine-master$

49-fluxengine.rules:
[code]
# UDEV Rules for Fluxengine
#
# To install, type this command in a terminal:
#   sudo cp 49-fluxengine.rules /etc/udev/rules.d/.
#
# After this file is installed, physically unplug and reconnect the Fluxengine.
#
ATTRS{manufacturer}=="Cowlark Technologies", ATTRS{product}=="FluxEngine", \
    SUBSYSTEMS=="usb", MODE:="0666"
#
# If you share your linux system with other users, or just don't like the
# idea of write permission for everybody, you can replace MODE:="0666" with
# OWNER:="yourusername" to create the device owned by you, or with
# GROUP:="somegroupname" and mange access using standard unix groups.
[/code]

$ cd ~/path/to/fluxengine-master/49-fluxengine.rules
$ cp 49-fluxengine.rules to /etc/udev/rules.d/.


$ cd /etc/udev/rules.d
$ ls -alt 49-fluxengine.rules
-rw-r--r-- 1 root root  615 Jun 23 16:55 49-fluxengine.rules
larry@debian:/etc/udev/rules.d$ 

Test to see if ./fluxengine works without using sudo command

$ pwd
/home/larry/Downloads/fluxengine/fluxengine-master
$ ./fluxengine test bandwidth
Transferred 1048576 bytes from FluxEngine -> PC in 1096 ms (933 kB/s)
Transferred 1048576 bytes from PC -> FluxEngine in 1795 ms (570 kB/s)
larry@debian:~/Downloads/fluxengine/fluxengine-master$

fluxengine now works without prefix sudo. 


Larry
