### ISSUE TITLE
Powering floppy drive

### ISSUE THREAD

**Issue by beyond-circuits** [davidgiven/fluxengine#29]
The instructions seem to suggest that you can power the floppy drive from the PSoC board. Is that really correct? When I do this it doesn't seem like the floppy is really powering on. 

Is the other option to provide an external 5V supply and make sure to tie the ground of that supply to the ground of the PSoC?

Thanks,

-Pete

**Comment by davidgiven** [comment]
No, that doesn't work --- I need to update the documentation. I was misled by my original test drive, which claimed to draw 400mA, but lied.

Yes, providing an external power supply and tying the grounds together should work.

**Comment by beyond-circuits** [comment]
OK, good to know. It seemed a little magical to think it would work.

**Comment by davidgiven** [comment]
I've rewritten the docs. See http://cowlark.com/fluxengine/doc/building.html.
