### ISSUE TITLE
Dropped pulses writing Amiga disks

### ISSUE THREAD

**Issue by davidgiven** [davidgiven/fluxengine#295]
I've finally fixed the Amiga encoder, meaning that it's generating correct (as far as I can tell) flux. However, it doesn't appear to be making onto disk correctly...

![image](https://user-images.githubusercontent.com/100638/124671486-d6419080-deb5-11eb-848d-800a70d91e26.png)

Top is what was read back from the disk, bottom is what the encoder produced. You can see there's a small section (two or three bits) missing. I haven't investigated more than this but the relevant track is enclosed.
[sample.zip](https://github.com/davidgiven/fluxengine/files/6773012/sample.zip)

**Comment by davidgiven** [comment]
So having done some writes and then reads, it seems that the written flux doesn't change, but the read back flux does. But it's always roughly the same sectors, which makes me think that there's actually something in the written flux which causes unreliable reads.

But IBM 720kB disks write and read back absolutely fine, and they use MFM at the same clock speed as the Amiga disks! I wonder if I'm not generating correct MFM encoding for the Amiga case and it's making the drive unhappy (such as too-wide intervals)?

**Comment by davidgiven** [comment]
Raw MFM bytes; good:

```
00000 : aa aa 44 89 44 89 55 29 2a a5 55 52 aa a9 2a aa  : ..D.D.U)*.UR..*.
00010 : aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa  : ................
00020 : aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa  : ................
00030 : aa aa aa 51 2a a4 2a aa aa aa aa 51 44 49 2a aa  : ...Q*.*....QDI*.
```

Bad:

```
00000 : aa aa 44 89 44 89 55 29 2a a5 55 52 aa a9 2a aa  : ..D.D.U)*.UR..*.
00010 : aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa  : ................
00020 : aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa  : ................
00030 : aa aa aa 51 2a a4 2a aa aa aa aa 5a 22 49 55 55  : ...Q*.*....Z"IUU
```

51 44 is 0101 0001 0100 0100.
5a 22 is 0101 1010 0010 0010. That shouldn't actually be possible, as there are 1s too close together, but I don't think that's very relevant.

**Comment by davidgiven** [comment]
The raw bytecode looks like this:

Good:

```
b0 b0 b0 3f 89 b0 3f 89 3f 89 b0 b0 b0
```

Bad:

```
b0 b0 b1 3f 89 b0 ae b1 b0 b0 b0
```

The good address is about 0x9c through the bytestream, so it's not obviously a USB framing issue.

**Comment by davidgiven** [comment]
Just tested this on the GreaseWeazle and, once I had it writing to the 3.5" drive rather than the 5.25" one (wasted an hour there), it works fine. So, it's a FluxEngine firmware bug.

**Comment by ourIThome** [comment]
I think this is one of the reasons why I've asked for track header / which contains sector CRC / track being read.  I had some images where the output from the adf output said everything was good.  But if I check the file level CRC ... I had corrupt files on the disk.

**Comment by davidgiven** [comment]
> I think this is one of the reasons why I've asked for track header / which contains sector CRC / track being read. I had some images where the output from the adf output said everything was good. But if I check the file level CRC ... I had corrupt files on the disk.

The sector and header checksums are already verified by the FluxEngine client when the disk is read. Unfortunately the Amiga checksums are terrible and are very bad at picking up bit errors. If you're getting apparently good reads but seeing bad files, that's what you'll be seeing here. Note that the errors I'm discussing here _are_ picked up by the sector and header checksums.

**Comment by davidgiven** [comment]
I believe this to be obsolete now.
