### ISSUE TITLE
Support GreaseWeazle 27?

### ISSUE THREAD

**Issue by psfales** [davidgiven/fluxengine#297]
Just ordered a new GreaseWeazle board on ebay and was pleased to find that there is software support from fluxengine.  When I run it, I get:

Error: only GreaseWeazle firmware versions 22 and 24 are currently supported, but you have version 27. Please file a bug.

(Apologies if this is a duplicate.  I did attempt to search, but I found it difficult to get clear results)

**Comment by davidgiven** [comment]
I actually heard from keirf the other day that the USB protocol is frozen, so v27 is the same as v24 --- I just didn't get round to doing it.

**Comment by psfales** [comment]
Maybe there is something else going on then.   I modified the code accept 27 (and now 28) as valid version numbers.   But it it still doesn't work.  It prints out a message that says "Checking rotation speed....",  the disk spins for a few seconds, and then it hangs forever without doing anything more.

**Comment by davidgiven** [comment]
It does all work for me; I have one with firmware 27. How recently have you updated your source? I did fix some bugs a couple of weeks ago.

**Comment by psfales** [comment]
I downloaded the zip file on July 7.    Does the zip file reflect the latest available code?

**Comment by davidgiven** [comment]
If it was from the main code page, yes; if it was from the Releases page, then only if you downloaded the one marked 'Current development release'. It does sound like you have the right one, though.

**Comment by psfales** [comment]
I believe I got it from the "code" page with all the default options, which I guess is the "Master" branch. Should I do something different?   Is there a version number in the source code I should check?

**Comment by davidgiven** [comment]
No, that should be fine. You should have the bugfix. That's very odd. 

Could you try `fluxengine test bandwidth` (with the GreaseWeazle options)?

**Comment by psfales** [comment]
I verified that I can still read a disk with "gw"

When I run "fluxengine test bandwidth --usb.greaseweazle=/dev/ttyACM0" it hangs without printing any output.  Running under strace shows that the last thing it did before my SIGINT  was a 10485760 byte write request that returned 9785344.
