### ISSUE TITLE
Unable to write 800K diskcopy images

### ISSUE THREAD

**Issue by andshort** [davidgiven/fluxengine#305]
Hello,

My setup consists of a greaseweazle F1 adapter. Using latest build, I am able to successfully read physical disks, but cannot write. Using the same hardware with previous versions of fluxengine, I can both read/write, so I believe something broke in latest build.
During write, I do not get errors, however the disk cannot be read.

Reading disks written by actual mac hardware is fine. Is there something I could look into?

     Tracks -> 1         2         3         4         5         6
H.SS 012345678901234567890123456789012345678901234567890123456789012345
0. 0 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBX
0. 1 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBX
0. 2 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBX
0. 3 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBX
0. 4 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBX
0. 5 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0. 6 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBX
0. 7 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBX
0. 8 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0. 9 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.10 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.11 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
1. 0 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.
1. 1 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.
1. 2 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.
1. 3 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.
1. 4 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXB
1. 5 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXB
1. 6 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXB
1. 7 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXB
1. 8 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
1. 9 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
1.10 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
1.11 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Good sectors: 28/1584 (1%)
Missing sectors: 1545/1584 (97%)
Bad sectors: 11/1584 (0%)
writing DiskCopy 4.2 image
66 tracks, 2 sides, 12 sectors, 524 bytes per sector; GCR

**Comment by andshort** [comment]
Also, I do not know if it is related, but latest release reads/writes disks almost twice as slow compared to release 580

**Comment by davidgiven** [comment]
I'm currently in the middle of a massive refactor in favour of getting verification during writes working, which is desperately needed, and it's entirely likely something got broken along the way. I need better tests. I'll investigate; thanks.

**Comment by andshort** [comment]
I know and that is great. Let me know if I can be of any assistance (troubleshooting, beta testing and so on)

**Comment by davidgiven** [comment]
The verifier change has been committed and pushed. I've verified that I'm able to write disks correctly on my setup. Could you try again with the latest client, please? (Note that the format name has changed from `macintosh` to `mac800`.)

**Comment by andshort** [comment]
Thanks for your response. I am still trying with different options, however early results show that it is exhibiting the same behaviour: 

     Tracks -> 1         2         3         4         5         6
H.SS 012345678901234567890123456789012345678901234567890123456789012345
0. 0 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBX
0. 1 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0. 2 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0. 3 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBX
0. 4 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBX
0. 5 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0. 6 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0. 7 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBX
0. 8 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0. 9 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.10 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.11 .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
1. 0 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXB
1. 1 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXB
1. 2 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXB
1. 3 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXB
1. 4 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXB
1. 5 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXB
1. 6 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXB
1. 7 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXB
1. 8 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
1. 9 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
1.10 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
1.11 X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


Also, I don't know if it is relevant, but in this version I had to supply --flux_source.drive.drive=0 and  --flux_sink.drive.drive=0 in order to read/write respectively. I would otherwise receive Error: bad input/output disk config

**Comment by davidgiven** [comment]
That last was a bug --- should be fixed now. (BTW you can use '-d drive:0' instead of the longer config options.)

Can you paste in the full command line and output from both the write and the read, please? I don't see how, with the verifier, that the write can be completing and still producing an unreadable disk.

**Comment by andshort** [comment]
Yes of course. Give me 2 minutes

**Comment by andshort** [comment]
Hi David,

using your latest release, the verify function is indeed being called. However Only track 0.0 is able to be written successfully.

Measuring rotational speed... 199ms
reading DiskCopy 4.2 image
80 cylinders, 2 heads; GCR; FluxEngine image
Writing to: drive 0
  0.0: Write:   199 ms in 71489 bytes
       Verify:  288 ms in 82054 bytes
  0.1: Write:   199 ms in 71166 bytes
       Verify:  286 ms in 82475 bytes
       Rewrite: 199 ms in 71166 bytes
       Verify:  287 ms in 82805 bytes
       Rewrite: 199 ms in 71166 bytes
       Verify:  286 ms in 82377 bytes
       Rewrite: 199 ms in 71166 bytes
       Verify:  287 ms in 82733 bytes
       Rewrite: 199 ms in 71166 bytes
       Verify:  285 ms in 82040 bytes
       Rewrite: 199 ms in 71166 bytes
       Verify:  285 ms in 82221 bytes
Error: Write failed; uncorrectable error during write.

**Comment by davidgiven** [comment]
Hmm. Are you using an HD or a DD disk? Writing DD formats to HD disks doesn't always work. (Mac GCR formats are always DD.)

That said, I think I might be doing something wrong here; I'll investigate.

**Comment by andshort** [comment]
Thanks David for your reply. I get the same behaviour with multiple disks (DD and HD). With all disks, it always writes only sector 0.0 correctly.
On the same note, I am able to use read/write disks successfully using the previous stable version with same hardware.

**Comment by andshort** [comment]
Hi again,

upon further investigation, I find that the issue occurs only when working with diskcopy images. When I load an img file, it writes and verifies successfully.

**Comment by andshort** [comment]
Hi David,

just writing to tell you that your latest commits have solved the issue with writing to 800kb mac disks. I will also test on physical mac but it is looking good.

Thanks

**Comment by davidgiven** [comment]
Oh, good --- glad to know this is fixed. Thanks!
