### ISSUE TITLE
help ! graph with fluxengine analyze layout

### ISSUE THREAD

**Issue by proteus075** [davidgiven/fluxengine#339]
hi, I have successfully created an output.csv file, in my case i wrote: 

**fluxengine read acornadfs --decoder.write_csv_to=output.csv --usb.greaseweazle=COM3**

can you tell me a command line example to get the graph with fluxengine analyze layout?

I tried :

**fluxengine analyse layout output.csv**

but syntax wrong, can you help me?

**Comment by davidgiven** [comment]
You want `fluxengine analyse layout --csv=output.csv`. Try `fluxengine analyse layout --help` to see all the parameters.
