### ISSUE TITLE
Support for reading bare HFS image (e.g. no header/tags) into mac400/mac800 format

### ISSUE THREAD

**Issue by tdaede** [davidgiven/fluxengine#343]
I'd like to add support for reading non-diskcopy images into mac400 and mac800 (usually ending in .dsk). For these, we can treat the tags as all zeros (that's what FloppyEmu does), and just used a fixed sector mapping.

However, it looks like the existing configuration options for the imgimagereader aren't flexible enough to describe the track layout needed. I was thinking of adding an extra "mac" flag to the imgimagereader, that when set, generates the appropriate track layout. Alternatively, I could expand the proto files to allow a whole table of track/sector assignments (though this feels overkill for the single image format that requires it).

**Comment by davidgiven** [comment]
What's the HFS format? One thing on my to-do list was to extend imgimagereader/writer to allow for different block orders (e.g. Acorn formats use all of side 0 and then all of side 1).

**Comment by tdaede** [comment]
In terms of http://cowlark.com/fluxengine/doc/disk-macintosh.html it's just a bare image with 512 byte sectors, without holes (and with the 12 byte tag implied as 0 bytes). The block order is the same as in DiskCopy files, I believe.

(HFS is the filesystem - an image in this format can be loop mounted by Linux, for example)

**Comment by davidgiven** [comment]
Ah, I'd forgotten those pesky variable-sector disks...

So this can already be done, but it's pretty clunky. You need to specify the number of sectors in each track in the image_reader/image_writer sectiosn, using something like this:

```
trackdata {
  sector_range {
    start_sector: 0
  }
}
trackdata {
  track: 0
  up_to_track: 9
  sector_range {
    sector_count: 10
  }
}
trackdata {
  track: 10
  up_to_track: 19
  sector_range {
    sector_count: 15
  }
}
```

(although obviously with the right numbers substituted in). It assumes CHS order which should be correct for HFS logical block order.

Two disclaimers: I currently have a cold and my brain's undervolted, and this has also never been used by any formats and so could be buggy. The way the track data works is that all clauses which match the track and side predicates are merged, in order, which subsequent values overriding the prior.

**Comment by ladyada** [comment]
mac dsk support is now merged, i tested it not with floppyemu but with a powerbook 180 and some 400k and 800k diskettes sucessfully

**Comment by davidgiven** [comment]
Oops, forgot to tag this bug. That was #449.

**Comment by ladyada** [comment]
all good, i was sweeping thru any mac-related issues in case there was something else to test
