### ISSUE TITLE
Reading c64 disks with Greaseweazle v0.27 and Fluxengine Development build 2021-11-04

### ISSUE THREAD

**Issue by joostpvh** [davidgiven/fluxengine#345]
I'm trying to read c64 disks and I need advice on how to do this.

I have a Greaseweazle v4 with firmware version v0.27, a PC floppy drive, and the most recent Fluxengine version. 

I first tried to use the --usb.greaseweazle option directly to the Greaseweazle, but this just hangs, I found out that this is expected when the Greaseweazle firmware level is >0.22. 

Then I tried to follow the many online examples where they first use the Greaseweazle software to read the drive with `./gw read c64-disk.scp`. But the examples then all use `./fluxengine convert scptoflux c64-disk.scp c64-disk.flux` and then `./fluxengine read c64 -s c64-disk.flux -o c64-disk.d64` or some variant of this. But the new restructured versions of Fluxengine no longer need the two steps (which is great), but the `c64` type no longer seems to exist. 

It seems there are two new types `commodore1541` and `commodore1581` in stead, but if I use this like this `./fluxengine read commodore1541 -o c64-disk.d64 -s c64-disk.scp` but this results in a segmentation fault. 

The setup does work correctly with IBM disks, using the two step read scp and then create img file. 

So I don't know what to do, I seem stuck. could you please advise how to proceed?

**Comment by frakswe** [comment]
I've got the same setup, the following line works for me:

./fluxengine read commodore1541 -s drive:1 -o test.d64 --usb.greaseweazle=/dev/ttyACM0

no hangs.

**Comment by joostpvh** [comment]
Thank you for the reaction. I just tried using what you advised in my case it looks like this:
`./fluxengine read commodore1541 -s drive:1 -o c64-testdrive.d64 --usb.greaseweazle=/dev/tty.usbmodem14511`
But I'm unfortunately still getting it just sitting there doing nothing, disk not moving. I also tried with `-s drive:0` and `-s drive:2`, not doing anything either.

Thank you for your help.

**Comment by davidgiven** [comment]
The GreaseWeazle code should work with either 0.22 or 0.24 and above, so 0.27 should work fine. I've got a 0.27 F7 Lightning and I've just verified that it works for me (at least as far as running 'fluxengine rpm' goes, as I don't have a C64 disk handy). Can you check to make sure you're running the latest development version of the FluxEngine client?

(This may also be causing what's wrong with trying to decode .scp files as I fixed some stuff not long ago.)

**Comment by joostpvh** [comment]
I'm running the version of FluxEngine available last week.

It's also on a Mac, I don't know if that makes any difference. (I was reading other issues and in some cases there seemed to be a difference.)

Also is the command I run above correct? Or should I use different flags?

I could run something like Ubuntu inside VirtualBox and pass the USB through but it seems like that might be overcomplicating things...

**Comment by joostpvh** [comment]
I pulled the latest version from the GitHub page just now, built it, same result. I also tried a different system.

I ran: `./fluxengine read commodore1541 -s drive:1 -o c64-testdrive.d64 --usb.greaseweazle=/dev/tty.usbmodem14511` 

It definitely tries to talk with the Greaseweazle, because if I remove it, it complains the device is not found.

**Comment by joostpvh** [comment]
Hi David, a small update. After trying different combinations on different systems I installed the Greaseweazle and FluxEngine software on Ubuntu running inside VirtualBox on one of the Macs I was trying it on earlier. This worked! :-) 

It took some fiddling with the USB forwarding, if used in the default USB2 mode the output bandwidth was high enough but the input bandwidth fell quite a bit short. Switching VirtualBox to simulate USB3 pass through did the trick.

I guess I'm left with some questions though:
- The drive seems to read much more than needed, it shows a 256 by 256 table at the end. Is this normal for the commodore1541 option? Or should I add something else to limit this?
- It only reads side 0, is there a way to read the other head with the appropriate offset? (I've seen references to setting the offset but these either don't work or I'm not using them correctly.)
- It remains strange that the same hardware seems to work fine with Ubuntu and not on MacOS. Any other advice? Or something you'd want me to try? I'm more than happy to help figure it out.

Thank you for your help and great software!

**Comment by davidgiven** [comment]
Re working on Linux and not Mac: that's weird. I mean, it's just a USB serial device. It should work. I do have a Mac I use for testing and it works there, or at least the last time I tried it. I'll give it another go.

If it's reading more than is correct that means it's seeing some corrupted sectors with garbage sector IDs. If the disk has any exotic copy protection then this might be confusing the FluxEngine decoder.

1541 disks are single-sided, which is why it's not reading the other side. Sometimes it's possible to read the other side of a flippy disk using the other head of a specially modified floppy disk drive but FluxEngine doesn't support that (as modifying the drive is hard). 1581 disks are double-sided --- they're just normal IBM disks.

**Comment by joostpvh** [comment]
Re working on Linux and not Mac: Weird indeed :-) It seems to be waiting for some handshake or so. On the Linux system it immediately starts to measure the rotational speed and run. 

Re reading more: The resulting `.d64` file seems fine, it's just weird how many things it scans. I think it's a regular C64 single sided image. It sees no errors until track 27 and then the errors start growing. I've uploaded the output I'm seeing to give you a better idea. [test_output.txt](https://github.com/davidgiven/fluxengine/files/7596483/test_output.txt)

Would it be possible to take a Greaseweazle generated scp image of the second side and feed this into the FluxEngine client as if it's the first side? I'm pretty sure most of my old disks are used on both sides and I flipped them over.

**Comment by davidgiven** [comment]
I've just rewritten the decoder and someone's submitted a bugfix for the Greaseweazle backend. Could you get the latest development release and try again? You may get better reads (much better, in some circumstances).

Yes, the FluxEngine client software will decode .scp files no problem. Just use the filename as the input for `-s`.

**Comment by davidgiven** [comment]
...also, there's a section on flippy disks here: https://cowlark.com/fluxengine/doc/faq.html

**Comment by joostpvh** [comment]
Hi David, sorry for the delay, I finally had some time to try it out. 

So on the Mac I pulled and built the latest source and unfortunately I'm still getting the same result... It just sits there, it doesn't complain about anything (like the USB device not being there or something like that) and with a `^c` it breaks back to the prompt. 

On the Linux instance (inside VirtualBox on the same system, cables, everything) I did the same and this works no problems.

I didn't update the Greaseweazle firmware or software as I presumed you only made changes to the FluxEngine code.

Thank you for your help.

**Comment by davidgiven** [comment]
I think I know what's wrong now, after hooking up my Mac and Greaseweazle. It seems OSX creates two serial port devices, which on my system look like `/dev/tty.usbmodem12345` and `/dev/cu.usbmodem123451`. FluxEngine only works with the second, not the first.

This could certainly be handled more gracefully because right now it's very confusing. I've found http://stuffthingsandjunk.blogspot.com/2009/03/devcu-vs-devtty-osx-serial-ports.html which seems to shed some light on what's going on.
