### ISSUE TITLE
Image-defined geometry

### ISSUE THREAD

**Issue by tdaede** [davidgiven/fluxengine#352]
I'm working on adding a d88 disk image reader, which is basically the Japanese equivalent of IMD format - each sector can specify its size and encoding independently. This is important as PC-88 disks frequently have different sector sizes on their first and subsequent track.

Currently, fluxengine requires you to specify a write profile which has explicit geometry - e.g. the ibm1232 profile. I was wondering if it would be beneficial to add an "auto" profile (or repurpose the "ibm" profile that's currently ro) for writing these sort of images, and source all of the profile parameters from the image itself.

Less importantly, such a mode might be handy for e.g. dim files that basically imply ibm1232 format, fluxengine could automatically pick a suitable profile.

**Comment by davidgiven** [comment]
Yes, I've had a similar request for IMD image-defined geometry. The recent rework to use protos was supposed to allow this but I never got around to it.

The way it would work is that the image reader would update the global config object to set the appropriate encoder (and decoder) settings. However, this would need to happen before the encoder gets created, for obvious reasons, and current `ImageReader::readImage` is called from deep inside `lib/writer.cc`, so there'd need to be some minor refactoring. But it should all be fairly straightforward now.

**Comment by davidgiven** [comment]
I've done some work here; it's in the `imageformats` branch (#358). Unfortunately the IMD format which I've looked at is more complicated than it looks so it doesn't actually work there yet, but ought to work as the prototype for the DIM format. This should allow writing disks without specifying a profile at all.
