### ISSUE TITLE
building the client under FreeBSD fails

### ISSUE THREAD

**Issue by tingox** [davidgiven/fluxengine#37]
Hello. I'm trying to build the client under FreeBSD, but the process fails, like this:
'''
tingo@kg-core1$ make
meson .obj
The Meson build system
Version: 0.49.2
Source dir: /zs/tingo/personal/projects/PSoC/fluxengine
Build dir: /zs/tingo/personal/projects/PSoC/fluxengine/.obj
Build type: native build
Project name: fluxclient
Project version: undefined
Native C++ compiler: c++ (clang 6.0.1 "FreeBSD clang version 6.0.1 (tags/RELEASE_601/final 335540) (based on LLVM 6.0.1)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/local/bin/pkg-config (1.6.0)
Dependency libusb-1.0 found: YES 1.0.13
Dependency sqlite3 found: YES 3.27.1
Dependency zlib found: YES 1.2.10
Build targets in project: 47
Found ninja-1.8.2 at /usr/local/bin/ninja
ninja: Entering directory `.obj'
[17/129] Compiling C++ object 'fluxreaderlib@sha/lib_fluxreader_sqlitefluxreader.cc.o'.
FAILED: fluxreaderlib@sha/lib_fluxreader_sqlitefluxreader.cc.o 
c++ -Ifluxreaderlib@sha -I. -I.. -I../lib -I../dep/fmt -I../lib/stream -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -g --std=c++14 -fPIC  -MD -MQ 'fluxreaderlib@sha/lib_fluxreader_sqlitefluxreader.cc.o' -MF 'fluxreaderlib@sha/lib_fluxreader_sqlitefluxreader.cc.o.d' -o 'fluxreaderlib@sha/lib_fluxreader_sqlitefluxreader.cc.o' -c ../lib/fluxreader/sqlitefluxreader.cc
In file included from ../lib/fluxreader/sqlitefluxreader.cc:3:
../lib/sql.h:4:10: fatal error: 'sqlite3.h' file not found
#include <sqlite3.h>
         ^~~~~~~~~~~
1 error generated.
[18/129] Compiling C++ object 'fluxreaderlib@sha/lib_fluxreader_hardwarefluxreader.cc.o'.
../lib/fluxreader/hardwarefluxreader.cc:44:14: warning: private field '_revolutions' is not used [-Wunused-private-field]
    unsigned _revolutions;
             ^
1 warning generated.
[22/129] Compiling C++ object 'decoderlib@sha/lib_decoders_decoders.cc.o'.
ninja: build stopped: subcommand failed.
*** Error code 1

Stop.
make: stopped in /zs/tingo/personal/projects/PSoC/fluxengine
'''
in FreeBSD, third-party files end up under /usr/local, so sqlite3.h is `/usr/local/include/sqlite3.h`
Unfortunately, I'm not familiar enough with meson / ninja to suggest a fix for this.
Details:
'''
tingo@kg-core1$ uname -a
FreeBSD kg-core1.kg4.no 11.2-STABLE FreeBSD 11.2-STABLE #0 r342545: Thu Dec 27 00:29:46 CET 2018     root@kg-core1.kg4.no:/usr/obj/usr/src/sys/GENERIC  amd64
'''

**Comment by davidgiven** [comment]
It's a dependency bug at my end --- I forgot to declare that library as depending on sqlite.

Could you please go to line 49 of meson.build and try adding this line:

```
dependencies: [sqlite]
```

(with the appropriate commas), and then let me know if it works?

**Comment by tingox** [comment]
yes, that works. That dependency is also needed a few other places:
readerlib (73)
writerlib (79)
brotherdecoderlib (121)
fe-upgradefluxfile (190)
cwftoflux (196)
(apologies if this is obvious to you)
but then it builds fine. Now to test it.

**Comment by davidgiven** [comment]
Sigh. Yes, you're right. I do actually have a spare machine here I'll install FreeBSD on to test with. Thanks for spotting this.

**Comment by davidgiven** [comment]
The build system is completely rewritten now (and the client has been reworked), so this is now obsolete.
