### ISSUE TITLE
Any reason a TEAC FD-505 Dual Floppy Drive wouldn’t work?

### ISSUE THREAD

**Issue by esemwy** [davidgiven/fluxengine#38]
I have my PSoC5 ready to go, but I haven’t sourced a drives yet. I have an old Shuttle XPC that’d work great for this application. It’ll fit separate drives, but things would be cramped and I’d like to use the 3.5 bay for a media reader. I think the 5.25 and 3.5 drives are completely separate electronically on the FD-505, but it’s been a while since I owned one. Any insight?

**Comment by davidgiven** [comment]
Ooh, I've always wanted one of those...

No, it should work fine. I found the datasheet: https://gekk.info/misc/Teac%20FD505%20Dual%20Function%20Combo%20Diskette.pdf

If you want the 3.5" drive to be FluxEngine's drive 0, plug it into the middle connector on the cable; if you want the 5.25" drive to be FluxEngine's drive 0, plug it into the end. (The other drive will be drive 1.)

Let me know if it works?

**Comment by davidgiven** [comment]
I assume it either all went fine, or the dog ate it and the question is now moot --- closing bug for cleanup.
