### ISSUE TITLE
Victor 9000 Images are Missing the Disk Label Preamble

### ISSUE THREAD

**Issue by pauldevine** [davidgiven/fluxengine#389]
On Victor 9000 disk images the FluxEngine images seem to be missing the floppy disk label preamble. I imaged the same disk via Kryoflux and then via Greaseweazle v4/FluxEngine. In the Kryoflux image the first ~500 bytes are the information with the speed/sector table described below. The information appears to be missing from the FluxEngine image. Example files attached.

The boot ROM lists the format as 
```
;
;	FLOPPY DISK LABEL FORMAT
;
fd_lbl		struc;

valid		dw	?;		must be ff00 to be a loadable O/S
load		dw	?;		system load address
paras		dw	?;		size of system
entry_offset	dw	?;		program's start offset from segment
entry_segment	dw	?;		program's start segment
disk_id		db	8 dup (?);	disk identification (unused)
system_id	db	8 dup (?);	system identification (unused)
sector_size	dw	?;		floppy's sector size
data_start	dw	?;		offset to unreserved region
boot_start	dw	?;		boot sector origin
flags		db	?;		(unused)
int_fact	db	?;		sector interleave (unused)
disk_type	db	?;		disk version
reserved	db	3 dup (?);	(unused)
speed_control	db	18 dup (?);	speed control table
zone_table	db	15 dup (?);	locations of speed change
sectors_track	db	15 dup (?);	sectors per track

fd_lbl		ends;
```

I think you're stripping that out as noise when you're saving the images. 

Referenced Images: 
[VictorTalk_FluxEngine.img.zip](https://github.com/davidgiven/fluxengine/files/7709473/VictorTalk_FluxEngine.img.zip)
[VictorTalk_Kryoflux.raw.zip](https://github.com/davidgiven/fluxengine/files/7709475/VictorTalk_Kryoflux.raw.zip)

On a separate issue about the dynamic sector sizes that was being discussed in #344, there was a question about the sector format and reading it dynamically:

>@pauldevine The number of sectors per track is in a table in the first sector of the floppy. Which tracks belong to which zones and the speed of the zones is also in the first sector of the floppy. It can be completely changed based on what's first read from the floppy, it's not hardcoded into ROM.
> @FozzTexx I didn't know that. Do you have a reference? It sounds like both the encoder and decoder are going to have to understand this, and it's going to make things really awkward.

The  states [Victor 9000 Hardware Reference Manual.pdf](https://github.com/davidgiven/fluxengine/files/7709402/Victor.9000.Hardware.Reference.Manual.pdf)
states on page 47: "On system powerup, the SCP [Speed Control Processor] uses a default speed table that allows the system to boot. Once the operating system software is loaded, the CPU writes a new speed table to the SCP that allows it to operate with the current 512-byte sectors. The SCP can be programmed with up to 15 different speeds."

Though in practice I don't think this is a real issue. I read through the decompiled ms-dos format.com assembly, and the speed table, which contains both the sector sizes and rpm, is hard coded and matches the boot ROM values. You can see the resultant entry in the Disk Label of the Kryoflux image starting at byte 71: `13 12 11 10 0F 0E 0D 0C 0B`. Those are the hex values you can see in the boot ROM as sectors per track 
```
;
;	speed tables used in reading floppy disks
;	NOTE:	prolog must directly preceed speeds !!!
;
prolog	db	15,4,17,1;				command prologue
speeds	db	3Eh,49h,53h,5Dh,67h,71h,7Bh,86h,8Ah;	speeds

tzones	db	3,15,26,37,47,59,70,82,97;		speed change locations
spt	db	19,18,17,16,15,14,13,12,11;		sectors per track
```
In practice I think all floppies would have been formatted with format.com which means you don't really need to dynamically load the values.  I didn't check the cp/m OS, however. So might differ there.

**Comment by davidgiven** [comment]
Thanks very much --- it actually turned out to be a simple disagreement between the decoder and the image reader/writer about whether track numbers started at 0 or 1, so all sectors with the ID of 0 got discarded. Oops.

Re the disk speed table: one thing I noted from the technical reference is that the two sides of the disk have different speed change locations, but I don't see anything in the table above about that. Is there another table which defines the format of the second side?

**Comment by pauldevine** [comment]
That is an excellent question David. Most of the images I've been playing with are single-sided. The boot rom definitely only references the first side, but to do the initial boot that's all it would need. What's interesting is the decompiled format.com code I have also only references side one. But it would definitely need a table for side 2. I'll dig into this and see what I can find. I have physical disks that appear to be double sided.
