### ISSUE TITLE
Some errors building under MacOS 12.0.1 then interfacing with Greaseweazle

### ISSUE THREAD

**Issue by Yserra** [davidgiven/fluxengine#391]
Hi, 
I get some 'deprecated' errors when I build the latest FluxEngine under MacOS 12.0.1 (tried on one MacBook Pro x86 and one MacBook Pro M1). When I "make" once more, it seems to build the remaining code. But when I want to use it, it seems to not recognize my Greaseweazle card anymore (it did, previously).

The first building process:
--------------------------
MacBook-Yann:fluxengine yserra$ make
MKNINJA .obj/build.ninja
[9/678] CXX .obj/dbg/.obj/proto/tests/testproto.pb.o
FAILED: .obj/dbg/.obj/proto/tests/testproto.pb.o 
clang++ -ffunction-sections -fdata-sections -pthread -I/usr/local/Cellar/protobuf/3.17.3_1/include -Ilib -Idep/fmt -Iarch -x c++ --std=gnu++2a -Wno-deprecated-enum-enum-conversion -Wno-deprecated-enum-float-conversion -I.obj/proto -O0 -g -I. -c -o .obj/dbg/.obj/proto/tests/testproto.pb.o .obj/proto/tests/testproto.pb.cc -MMD -MF .obj/dbg/.obj/proto/tests/testproto.pb.o.d
In file included from .obj/proto/tests/testproto.pb.cc:4:
.obj/proto/tests/testproto.pb.h:34:10: fatal error: 'lib/common.pb.h' file not found
#include "lib/common.pb.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
[11/678] CXX .obj/opt/.obj/proto/tests/testproto.pb.o
FAILED: .obj/opt/.obj/proto/tests/testproto.pb.o 
clang++ -ffunction-sections -fdata-sections -pthread -I/usr/local/Cellar/protobuf/3.17.3_1/include -Ilib -Idep/fmt -Iarch -x c++ --std=gnu++2a -Wno-deprecated-enum-enum-conversion -Wno-deprecated-enum-float-conversion -I.obj/proto -Os -I. -c -o .obj/opt/.obj/proto/tests/testproto.pb.o .obj/proto/tests/testproto.pb.cc -MMD -MF .obj/opt/.obj/proto/tests/testproto.pb.o.d
In file included from .obj/proto/tests/testproto.pb.cc:4:
.obj/proto/tests/testproto.pb.h:34:10: fatal error: 'lib/common.pb.h' file not found
#include "lib/common.pb.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
[105/678] CC .obj/opt/dep/libusbp/src/mac/list_mac.o
dep/libusbp/src/mac/list_mac.c:53:13: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
            kIOMasterPortDefault, dict, &iterator);
            ^~~~~~~~~~~~~~~~~~~~
            kIOMainPortDefault
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
const mach_port_t kIOMasterPortDefault
                  ^
1 warning generated.
[107/678] CC .obj/opt/dep/libusbp/src/mac/iokit_mac.o
dep/libusbp/src/mac/iokit_mac.c:22:44: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
    *service = IOServiceGetMatchingService(kIOMasterPortDefault, dict);
                                           ^~~~~~~~~~~~~~~~~~~~
                                           kIOMainPortDefault
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
const mach_port_t kIOMasterPortDefault
                  ^
1 warning generated.
[108/678] CC .obj/dbg/dep/libusbp/src/mac/list_mac.o
dep/libusbp/src/mac/list_mac.c:53:13: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
            kIOMasterPortDefault, dict, &iterator);
            ^~~~~~~~~~~~~~~~~~~~
            kIOMainPortDefault
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
const mach_port_t kIOMasterPortDefault
                  ^
1 warning generated.
[109/678] CC .obj/dbg/dep/libusbp/src/mac/iokit_mac.o
dep/libusbp/src/mac/iokit_mac.c:22:44: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
    *service = IOServiceGetMatchingService(kIOMasterPortDefault, dict);
                                           ^~~~~~~~~~~~~~~~~~~~
                                           kIOMainPortDefault
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
const mach_port_t kIOMasterPortDefault
                  ^
1 warning generated.
[186/678] CXX .obj/dbg/lib/imagewriter/imgimagewriter.o
lib/imagewriter/imgimagewriter.cc:67:11: warning: enumeration value 'SECTORS_ONEOF_NOT_SET' not handled in switch [-Wswitch]
                switch (trackdata.sectors_oneof_case())
                        ^
lib/imagewriter/imgimagewriter.cc:67:11: note: add missing switch cases
                switch (trackdata.sectors_oneof_case())
                        ^
1 warning generated.
[188/678] CXX .obj/opt/lib/imagewriter/imgimagewriter.o
lib/imagewriter/imgimagewriter.cc:67:11: warning: enumeration value 'SECTORS_ONEOF_NOT_SET' not handled in switch [-Wswitch]
                switch (trackdata.sectors_oneof_case())
                        ^
lib/imagewriter/imgimagewriter.cc:67:11: note: add missing switch cases
                switch (trackdata.sectors_oneof_case())
                        ^
1 warning generated.
[620/678] ENCODEDECODE scp n88basic
ninja: build stopped: cannot make progress due to previous errors.
make: *** [all] Error 1

The second build process:
--------------------------

MacBook-Yann:fluxengine yserra$ make
[60/60] TEST .obj/fluxpattern-test-debug

Trying to use FluxEngine with Greaseweazle:
--------------------------------------------

MacBook-Yann:Greaseweazle yserra$ ./gw info
Host Tools: v0.33
Greaseweazle:
  Device:   /dev/cu.usbmodem2101
  Model:    F7 v3 "Thunderbolt"
  Firmware: v0.32
  Serial:   GW000F002A4E30501420343135
  USB Rate: Full Speed (12 Mbit/s)

MacBook-Yann:fluxengine yserra$ ./fluxengine inspect --usb.greaseweazle=/dev/cu.usbmodem2101
Error: no such config field 'greaseweazle' in 'usb.greaseweazle'

**Comment by davidgiven** [comment]
I recently did a major update --- I think the first error you were seeing is due to a stray build artifact when updating the source. I can't duplicate this with a fresh checkout. The warnings are unfortunately not my fault; I'll see about silencing them.

The reason why it's complaining about the `--usb.greaseweazle` parameter is that the update adds proper device autodetection; you don't need it any more.

Let me know if it works, please?

**Comment by davidgiven** [comment]
Ah, turns out there is a build issue! Fix OTW.

**Comment by Yserra** [comment]
Thank you for your answer! And, yes, you're absolutely right: i works perfectly without the --usb.greaseweazle. (I didn't see that information in the doc, my apologies).
