### ISSUE TITLE
GreaseWeazle does not work on COM port > 9 on Windows

### ISSUE THREAD

**Issue by hharte** [davidgiven/fluxengine#393]
While experimenting with FluxEngine support for GreaseWeazle on Windows 10, I found that it did not work properly when the system assigned a COM port number > 9 to the GreaseWeazle.

**Comment by davidgiven** [comment]
Are you using the up-to-date client? I ask because only a few days ago I committed a major rework to the way serial ports are handled.

**Comment by davidgiven** [comment]
...aaand now I see your PR!

**Comment by davidgiven** [comment]
Closing as this got fixed in the PR.
