### ISSUE TITLE
Victor 9000 Double Sided Support

### ISSUE THREAD

**Issue by pauldevine** [davidgiven/fluxengine#395]
Hi David,
I was playing around with trying to image some double-sided disks in the Victor9k format. I'm providing you two samples here. First sample is a semi-bad double sided disk from the 80's with some shareware utilities. I say semi-bad because when I try to duplicate the disk in an actual Victor 9K the copy craps out on some specific sectors as unreadable. All are on the second side and I gave up after 3 attempts with various errors in different spots on side two. If I don't touch the damaged sectors the disk reads normally in the machine. I'm enclosing both FluxEngine flux dumps as wells as Kryoflux raw streams in case they're helpful as well.

Utilities disk, I can see you're not yet processing the second side:
```
     Tracks -> 1         2         3         4         5         6         7
H.SS 01234567890123456789012345678901234567890123456789012345678901234567890123456789
0. 0 ................................................................................
0. 1 ................................................................................
0. 2 ................................................................................
0. 3 ................................................................................
0. 4 ................................................................................
0. 5 ................................................................................
0. 6 ................................................................................
0. 7 ................................................................................
0. 8 ................................................................................
0. 9 ................................................................................
0.10 ................................................................................
0.11 ................................................................................
0.12 .......................................................................XXXXXXXXX
0.13 ............................................................XXXXXXXXXXXXXXXXXXXX
0.14 ................................................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.15 ......................................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.16 ...........................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.17 ................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.18 ....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Good sectors: 1224/1520 (80%)
Missing sectors: 296/1520 (19%)
Bad sectors: 0/1520 (0%)
IMG: wrote 80 tracks, 1 sides, 612 kB total
```
I then took a never-used floppy disk and formatted it in the Victor as a double sided disk. The format reported good and I'm able to use the disk in the actual machine without error. I took an image of the blank disk immediately after formatting it so we could see what a blank freshly-formatted disk looks like. When I tried to image that disk FluxEngine gave me a bunch of "Failed to read sector XX (bad checksum);" errors throughout the disk. I'm assuming there must be a strange state on initialization of the format without any data. I'm enclosing both FluxEngine and Kryoflux flies of that as well. The Kryoflux documentation mentioned experimenting with double density vs high density settings, so that's the dd0 and dd1 difference. I know victor uses double-density disks but has fairly tight packing, so I tired both settings.

That blank disk looked terrible upon imaging. But what's funny about it is it's new media that's just been formatted:
```
     Tracks -> 1         2         3         4         5         6         7
H.SS 01234567890123456789012345678901234567890123456789012345678901234567890123456789
0. 0 .....B.BBBB.B.BBBBBBBBBBBBBBBBBBBBXBBBBBBXBBXXXXXXXXX?XXXX?XXXXXXXXXBBB?B?XXB?X?
0. 1 .....B...BB.BBBBBBBB.BBB.BBBBXBBBBXBXBB?BXBBBXXXXXBXXXXXXXXBXB?XBBXXXXBXXXXXB?B?
0. 2 ......BB.BB...B..BBBBBBB.BBBBBBBBBBBBBBBBBBBB?XXXXXXXXXXBXXXXXXXXXBXXXXXB?XBXXX?
0. 3 .....B.B.B.B..B.BBBBBBBBBBBBBXBXBBBBBBBXBXBXXXXXXXXXXXBXXXX?BX???XXXBB?XBXX?XXX?
0. 4 ......BB.BBBBBBB.BBBBBBBBBBBBBB?BBBBBBBBBBB?XXXXBXXXXBXXXX?XXXXB??X??XB?X?XBXBXX
0. 5 .......B.B.B.BB.BBBBBBBBBXBBBXBBBXBBBBBBBXBXXXXXXXBXXXXBXX?X?XXXXXBBXXXXXXBBBBXX
0. 6 .....B.B.B.B.BB.BBBBBBBBBBBBBBBBBBBBBBBBBXBBX?XXX?X?BXXB?XX??XXXBBX?X?XBXBB?XBB?
0. 7 ......B..B.B.BB.BBBBBBBBBBBBBBXBBBBBB?BBBBXBXXXBBXXXXBXXXXX?BXXBBXXXB?XXXXXXB?XB
0. 8 ......B..B......BBBBBBBB.BBBBB?BBBBBBBXBBX??XXX?XXXXXXXXXXBXXBXXBXXBXXXX?XXXXXXX
0. 9 ......B.BB.B....BBBBBBBBBBBBBBBBBBBBBBBBB?XXXXXX??XXXXXXXXXXBXXX?X??BB?XBBB??B?X
0.10 .B..BBB.BB.B..BB.BBBBBBBBBBBBBBBBX?BB?BBBBXBBXXXXXXXXXXXXBX??XX?BBXXXBXXXBXBXBXX
0.11 .....B..BB...B..BBBBBBBBBXBBBBBBBBBBBBBXBXB?XXXXXXXBXBXXXXXBXX?X??XBBXBXB??BB?B?
0.12 .B...BBB..B..B.B.XBBBBBBBBBBBBBBBBBBBBBBBXBBXXBXX?XXXXX??BX?BBBX?XB?XB?XXXXXXXXX
0.13 ...B.BBBB.BB.BB..BBBBBBBBBBBBBXBBBBBBXBBBBBXX?XBBXXX?XXBXX?XXXXXXXXXXXXXXXXXXXXX
0.14 .....BBBB.B....BBBBB.BBBBBBBBBBBBB?BBBBBBBBBX?XBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.15 .....BBBB....B..BBBBBBBBBBBBB?BBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.16 .........BB..B..BBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.17 .....BBB.BB..BBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.18 ....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Good sectors: 281/1520 (18%)
Missing sectors: 639/1520 (42%)
Bad sectors: 600/1520 (39%)
IMG: wrote 80 tracks, 1 sides, 612 kB total
```

Finally, when I open one of those disks in mame, I have it logging the speed/track/sector table and it reports:
```
 Speed table: 04 11 01 3e 49 53 5d 67 71 7b 86 8a 8a 8a 8a 8a 8a 8a
  Zone table: 03 0f 1a 25 2f 3b 46 52 61 61 61 61 61 61 61
Sector/track: 13 12 11 10 0f 0e 0d 0c 0b 00 00 00 00 00 00
```

values are in hex, which is what it indicated for the single-sided disks. Something very odd about the sector table for the later tracks. If I get ambitious I'm going to see if I can find and dump the table from RAM on the actual hardware.

Link to images on Google Drive
https://drive.google.com/drive/folders/1iPS9G-6VQGP2iZw4MYuQOUUimU4F6Uez?usp=sharing

**Comment by pauldevine** [comment]
If it's helpful I've been able to boot an actual machine and run a debugger against the disk sectors. I'm seeing the same values on the actual hardware as what we have above.
![IMG_2900](https://user-images.githubusercontent.com/1730609/147048382-4f4b83cf-d9b2-4dea-9d2e-f08977c715b3.jpeg)

**Comment by davidgiven** [comment]
Let me summarise to make sure that I understand what you're saying:

- you have some V9K disks that were formatted on someone else's machine.
- these work fine on your machine
- these image and decode fine with FluxEngine/Kryoflux.
- if you write a disk on your machine, they work fine on your machine.
- these then fail to image and decode.

TBH that sounds suspiciously like you have an alignment issue on the V9K's drive --- being able to read and write your own disks but then other people can't is a classic symptom. But I'd then expect you not to be able to read and write other people's disks, so that's weird. Do you have a twin floppy model? If so, can you try copying the disk using the other drive and seeing if that makes a difference?

Adding support for the second side is easy, just not done yet because I don't know the layout: see src/formats/victor9k_ss.textproto for the description. You can copy that and use the filename as a profile.

**Comment by pauldevine** [comment]
What you describe is correct except for the 1st bullet. I believe the disks I have were all generated by this same machine. It is a dual floppy model, and I can swap disks between the drives and they can read each other's writes fine, including newly formatted disks. 

I can image the disks, both old and new with both FluxEngine and Kryoflux. Single sided disks seem to be read correctly and I can get them partially working in mame. When I look at the hex of the imaged disks against the hex I see on the physical hardware they match with an occasional off-by 1 bit type thing quite rarely. What I can't do is take the resulting image and write it back to a new disk via the greasewezale and get that to be read by the machine. I suspect a bug in the track sector header.

**Comment by pauldevine** [comment]
Also found this: page 238 of the Hardware manual:  

> Floppy access times:
> 2 micro-second per bit data transfer rate, with an interleave factor of 3. Average seek time is approximately
> 90 milli-seconds.

Not sure if that's helpful in any way.

**Comment by pauldevine** [comment]
Realized the text has a great description of the sync pattern:

> (Sync is a special GCR pattern that does not occur in normal data fields. The sync pattern consists of 10 ones during a byte time; other GCR patterns cannot contain more than 8 ones during a byte time.) When the GCR read circuit detects a sync mark, it starts a counter that causes an interrupt to be sent to the CPU, if sync
remains present for 6 byte times. This interrupt to the CPU, which is called SYN and is on the highest level interrupt input line to the interrupt controller, informs the CPU that a header sync mark has been detected.

**Comment by pauldevine** [comment]
I offer a suggestion in #396 that may be the right path for double sided support. I welcome your feedback.
