### ISSUE TITLE
Incompatibility with Greaseweazle 1.0

### ISSUE THREAD

**Issue by z80micro-mc** [davidgiven/fluxengine#401]
https://cowlark.com/fluxengine/doc/greaseweazle.html

Trying to get it to work with my Greaseweazle v4 on COM5
I have Greaseweazle V4 board, latest 1.0 firmware and  v0.35 GW

D:\fluxengine>fluxengine read ibm -o ibm.img --usb.greaseweazle=/dev/com5
Error: no such config field 'greaseweazle' in 'usb.greaseweazle'

D:\fluxengine>fluxengine test bandwidth
Using GreaseWeazle GW135195184205400002401705 on COM5
Writing data: transferred 10485760 bytes from PC -> device in 10013 ms (1022 kb/s)
Reading data: Error: command returned garbage (0x1 != 0x12 with status 0x0)

D:\fluxengine>

D:\fluxengine>fluxengine read ibm -o ibm.img
Using GreaseWeazle GW135195184205400002401705 on COM5
Error: only GreaseWeazle firmware versions 22 and 24 or above are currently supported, but you have version 0. Please file a bug.

D:\gw-tools>gw info
Host Tools: v0.35
Device:
Port:     COM5
Model:    V4
Firmware: v1.0
Serial:   GW135195184205400002401705
USB Rate: Full Speed (12 Mbit/s)

Peter

**Comment by davidgiven** [comment]
I've just upgraded my GreaseWeazle to firmware 1.0 and, unfortunately, it works absolutely fine for me.

Did you try this again? I've seen situations where the communications protocol gets out of sync and unplugging and reinserting it (forcing the board to reboot) fixes things.

**Comment by z80micro-mc** [comment]
David,

which file should I be using for Windows 10 & Windows 7 both 64 bit?

The windows branch says that it is 265 comits behind the master.

Peter

**Comment by z80micro-mc** [comment]
I have tried again reloading every thing still no luck.

PC works happily with Greaseweazle v0.35 as per screen o/p reading 720k msdos disk but fails on Fluxengine to recognize the firmware as valid or to test bandwidth

Peter
[duff-flux.docx](https://github.com/davidgiven/fluxengine/files/7798116/duff-flux.docx)

**Comment by davidgiven** [comment]
You want the current development build here: https://github.com/davidgiven/fluxengine/releases/tag/dev That's got an .exe which will work on any 64-bit Windows system.

**Comment by z80micro-mc** [comment]
Thanks 

That seems to work having also replaced the floppy cable with IBM PC twisted cable.

How do I configure Fluxengine to use Greaseweazle in Shugart rather than IBM-PC drive mode?
Greaseweazle does it by using A: & B: for IBM-PC drive references and DS0 & 1 for Shugart.
As most of the systems I am interested in are not PCs I tend to have drives setup as Shugart and use straight cables. I had to pull one off a PC.

BTW where do I find documentation on writing profiles and creating Flux image files?

Peter
