### ISSUE TITLE
Drive logic appears wrong!

### ISSUE THREAD

**Issue by z80micro-mc** [davidgiven/fluxengine#403]
I have a greaseweazle that I am trying to use. -it works fine under Greaseweazle - DS0 shugart standard straight through cable.

Under Fluxengine it neither works as drive 0 nor as drive 1. -drive:0 in-use led comes on but motor does not start.
-drive:1 motor starts but no in-use led and does not detect ready.

How do I tell it to use the Greasweazle in Shugart mode?

Greaseweazle uses DS0  / DS1 for Shuggart and A: & B: for IBM mode wiring.

Peter

**Comment by davidgiven** [comment]
I wasn't actually aware the Greaseweazle supported Shugart mode. Let me have a look and see if it's easy to enable.

**Comment by davidgiven** [comment]
That was easy to do and it should be in the latest dev build. PTAL? I don't have any Shugart devices. To use, add `--usb.greaseweazle.bus_type=SHUGART` to the command line.
