### ISSUE TITLE
usbfinder.cc compile error

### ISSUE THREAD

**Issue by merclangrat** [davidgiven/fluxengine#407]
I am trying to build fluxengine (I have GreaseWeazle and want to use the client) on Devuan Beowulf (it uses the same versions as Debian Buster) and get an error. I guess it may happen because some libraries are very new.

`$ make`
`MKNINJA .obj/build.ninja`
`[326/689] CXX .obj/opt/lib/usb/usbfinder.o`
`FAILED: .obj/opt/lib/usb/usbfinder.o `
`g++ -ffunction-sections -fdata-sections -pthread -I/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -Ilib -Idep/fmt -Iarch -x c++ --std=gnu++2a -Wno-deprecated-enum-enum-conversion -Wno-deprecated-enum-float-conversion -I.obj/proto -Idep/libusbp/include -Os -I. -c -o .obj/opt/lib/usb/usbfinder.o lib/usb/usbfinder.cc -MMD -MF .obj/opt/lib/usb/usbfinder.o.d`
`lib/usb/usbfinder.cc: In function ‘std::vector<std::unique_ptr<CandidateDevice> > findUsbDevices(const std::set<unsigned int>&)’:
lib/usb/usbfinder.cc:33:11: error: ‘const class std::set<unsigned int>’ has no member named ‘contains’`
`   if (ids.contains(id))`
`           ^~~~~~~~`
`At global scope:`
`cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-enum-float-conversion’`
`cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-enum-enum-conversion’`
`[329/689] CXX .obj/dbg/lib/usb/usbfinder.o`
`FAILED: .obj/dbg/lib/usb/usbfinder.o `
`g++ -ffunction-sections -fdata-sections -pthread -I/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -Ilib -Idep/fmt -Iarch -x c++ --std=gnu++2a -Wno-deprecated-enum-enum-conversion -Wno-deprecated-enum-float-conversion -I.obj/proto -Idep/libusbp/include -O0 -g -I. -c -o .obj/dbg/lib/usb/usbfinder.o lib/usb/usbfinder.cc -MMD -MF .obj/dbg/lib/usb/usbfinder.o.d`
`lib/usb/usbfinder.cc: In function ‘std::vector<std::unique_ptr<CandidateDevice> > findUsbDevices(const std::set<unsigned int>&)’:`
`lib/usb/usbfinder.cc:33:11: error: ‘const class std::set<unsigned int>’ has no member named ‘contains’`
`   if (ids.contains(id))`
`           ^~~~~~~~`
`At global scope:`
`cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-enum-float-conversion’`
`cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-enum-enum-conversion’`
`[570/689] AR .obj/opt/tests/proto.o .obj/opt/.obj/proto/tests/testproto.o`
`ninja: build stopped: cannot make progress due to previous errors.`
`make: *** [Makefile:78: all] Error 1`

I installed everything as suggested, libusb version is:
`ii  libusb-0.1-4:amd64                       2:0.1.12-32                             amd64        userspace USB programming library`
`ii  libusb-1.0-0:amd64                       2:1.0.22-2                              amd64        userspace USB programming library`
`ii  libusb-1.0-0-dev:amd64                   2:1.0.22-2                              amd64        userspace USB programming library development files`
`ii  libusb-1.0-doc                           2:1.0.22-2                              all          documentation for userspace USB programming`

**Comment by davidgiven** [comment]
Mm. You're clearly using a different C++ compiler than I am --- what version of gcc is it? You might want to try clang instead:

`make CC=clang CXX=clang++`

I will try and remove that use of `contains` as I see in the docs that it's actually part of the _next_ (i.e. unreleased) version of C++.

**Comment by merclangrat** [comment]
thanks! it worked with clang, and I also found out that my system dependencies were a bit broken - some libraries were too new and some too old.
it has been built successful, then I'll close this issue.
