### ISSUE TITLE
Image formats that specify floppy format don't verify if no format is set

### ISSUE THREAD

**Issue by tdaede** [davidgiven/fluxengine#424]
e.g. DIM files verify when written with:

    ./fluxengine write ibm1232 -i file.dim

or:

    ./fluxengine write ibm -i file.dim

but not:

    ./fluxengine write -i file.dim

**Comment by davidgiven** [comment]
This is because the code which is setting the format is only setting the encoder config. To perform the verification, it needs to set the decoder config too.

The fix should be trivial --- let me have a look.
