### ISSUE TITLE
fluxupgrade issue

### ISSUE THREAD

**Issue by dk1spb** [davidgiven/fluxengine#441]
I can't upgrade flux file from v2 to v3 by current fluxengine.
# ./fluxengine upgradefluxfile 01.flux
Warning: reading a deprecated flux file format; please upgrade it
Error: that flux file is version 2, but this client is for version 3

Flux file http://oldpc.su/0/01.rar

But old version make upgrade OK.

And please, please, PLEASE add 'fluxengine version' options for check version of fluxengine.

**Comment by davidgiven** [comment]
Wow --- version 2 flux files are ancient! I was hoping that nobody was using them any more. I'll try and fix the upgrader shortly.
