### ISSUE TITLE
Troubles with new client

### ISSUE THREAD

**Issue by dk1spb** [davidgiven/fluxengine#442]
1) For Windows with MSYS2: also vim package is needed (or got 'xxd command not fount error') and diffutils (for 'cmp')
2) I can't run client (both: compiled by myself or precompiled Development build 2022-02-02; windows 10):
>fluxengine.exe rpm
Using FluxEngine 7403020917073374
terminate called after throwing an instance of 'libusbp::error'
  what():  Failed to initialize generic interface.  DeviceInterfaceGUIDs key does not exist.

I have updated fw, and old version fluxengine said:
     >fluxengine.exe rpm
     Using FluxEngine with serial number 7403020917073374
     Error: your FluxEngine firmware is at version 16 but the client is for version 15; please upgrade
but new version of client still can't run with same error :-(

**Comment by dk1spb** [comment]
Update: precompiled version 580 is OK.
But lastest client always said 
terminate called after throwing an instance of 'libusbp::error'
what(): Failed to initialize generic interface. DeviceInterfaceGUIDs key does not exist.

**Comment by davidgiven** [comment]
I know this one: the firmware upgrade confuses Windows. You need to go to the Device Manager, find the FluxEngine device, then pick 'uninstall' from the menu. Unplug and reinsert the device. It should work again.

**Comment by dk1spb** [comment]
Thank you!!!!
