### ISSUE TITLE
Unable to read mac800 disks from greaseweazle hardware

### ISSUE THREAD

**Issue by mistydemeo** [davidgiven/fluxengine#444]
I've got a greaseweazle I'm trying to use with the Fluxengine client. IBM disks are working fine, however the Mac disks I've tested all report empty sectors and fail to read:

```
       0 records, 0 sectors; 0 distinct sectors;
       Required sector 0 missing;
       Required sector 1 missing;
       Required sector 2 missing;
       Required sector 3 missing;
       Required sector 4 missing;
       Required sector 5 missing;
       Required sector 6 missing;
       Required sector 7 missing;
       Required sector 8 missing;
       Required sector 9 missing;
```

I've tested these two disks with a standard USB floppy drive and they read OK.

I've called it with:

```
$ fluxengine read mac800 disk.img --copy-flux-to disk.flux
```

**Comment by davidgiven** [comment]
USB drives typically don't support the mac800 format --- are you sure it's not a IBM format disk? You'll need the ibm1440 or ibm720 formats for those.

Regardless, if you attach your `disk.flux` file I can take a look.

**Comment by mistydemeo** [comment]
You're completely right - it was IBM format. Sorry about that! I did find that I had to specify `ibm1440` for a couple since the auto-detection got them wrong, but that's not a big deal at all.

I do have one question about a couple disks that are actually `mac800`. They show this "missing sector" format; is that expected for the format? It does seem like the DiskCopy output is as expected.

```
H.SS 01234567890123456789012345678901234567890123456789012345678901234567890123456789
0. 0 ................................................................................
0. 1 ................................................................................
0. 2 ................................................................................
0. 3 ................................................................................
0. 4 ................................................................................
0. 5 ................................................................................
0. 6 ................................................................................
0. 7 ................................................................................
0. 8 ................................................................XXXXXXXXXXXXXXXX
0. 9 ................................................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.10 ................................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
0.11 ................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
1. 0 ................................................................................
1. 1 ................................................................................
1. 2 ................................................................................
1. 3 ................................................................................
1. 4 ................................................................................
1. 5 ................................................................................
1. 6 ................................................................................
1. 7 ................................................................................
1. 8 ................................................................XXXXXXXXXXXXXXXX
1. 9 ................................................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
1.10 ................................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
1.11 ................XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Good sectors: 1600/1920 (83%)
Missing sectors: 320/1920 (16%)
Bad sectors: 0/1920 (0%)
```

**Comment by davidgiven** [comment]
Yes, that last is correct --- mac800 disks have different numbers of sectors depending on the track. I should probably update the map code to show intentionally-missing sectors differently. Also, given how much trouble it was to get the decoder working, it's really nice to see such a good read!

**Comment by mistydemeo** [comment]
>  correct --- mac800 disks have different numbers of sectors depending on the track.

Aha, that makes sense. Thank you!

> I should probably update the map code to show intentionally-missing sectors differently.

If that's possible, it'd definitely make that output a bit easier to read.

> Also, given how much trouble it was to get the decoder working, it's really nice to see such a good read!

Every single one of them has been a nice clean read! Thanks so much for your work on this; it's been incredibly helpful.
