### ISSUE TITLE
Shell?

### ISSUE THREAD

**Issue by mathe1** [davidgiven/fluxengine#45]
Hi,

this is my first soldering project for computer ever. 
All of your great project was descripted fine and step by step - I'm ready to start reading old disks at Win10 now.

You wrote:

> 6. Insert a scratch disk and do .obj/fe-rpm from the shell.

But what **shell**? 
Could you explain me, please?

**Comment by davidgiven** [comment]
It means the Cygwin command line, where you compiled the client tools. They're all intended to be run from the build directory. (They're currently not installed anywhere for simplicity.)

**Comment by mathe1** [comment]
Ok, thanks for help me. I installed Cygwin (32bit, setup from internet, no changes).

> where you compiled the client tools.

Did I compile them? Maybe I overlooked any instruction?
I compiled and program something with the Cypress Creator, but it seems not compile that tools? 

While the last 3 hours I red some manual about cygwin and tried a little bit, but find no way to compile anything (I find out, I need GCC. But no GCC there...). 

So I run the setup again, search for "gcc" but there 31 hits in category "Devel" - what package I need for success compiling your source (C, C++, Objective-C/C++; which version; ...)?

Sorry, it is my first time with this environment.

**Comment by davidgiven** [comment]
I'm afraid I am assuming that people know their way around a Unix command line --- the tools are all very low level and require a certain amount of knowledge to use. I should probably emphasise this in the documentation (although it is mentioned in the Building the Client section in the instructions).

I believe you need the gcc-g++, make, meson, ninja, libusb1.0-devel and libsqlite3-devel packages.

**Comment by mathe1** [comment]
Thank you!
Now it works all.

I've also add cmake and zlib.
The compiled .exe runs also in windows cmd - I have only put some cyg*.dlls in the folder with  wished readers (fe-readibm.exe for test; fe-readbrother.exe for praxis ;-) ).

Also I find out to open the resulting .img-files with 7-zip.

Thank you very much for your great project!

**Comment by davidgiven** [comment]
Good to know!

A surprising number of people are interested in FluxEngine specifically for the Brother support; let me know if you have any problems.
