### ISSUE TITLE
Brother file export

### ISSUE THREAD

**Issue by mathe1** [davidgiven/fluxengine#47]
Now I've started extract files from brother 120k disks.

My goal is to convert the extracted files to Richtext with the correct formatings. 

To examine this I write a text on WP-1, save the text on disk - read the disk by fluxEngine into my PC and export the files with the brother120tool.

I find out, the extracted files are cut on false position, because I defined a "Headnote" and a "Footnote" - these blocks are before the maintext...

At the start of .img-file there is the directory. Are the 2 bytes at offset 10 (dec.), 26, 42, .. for the position on disk, where the document starts? Track/sector maybe? How to find out then the offset inside the image?

**Comment by davidgiven** [comment]
Interesting. Can you sent me the `.img` file to have a loook at?

The numbers in the directory entry are, as far as I can tell, the sector number of the start of the file. There's an open question as to whether the _end_ is correct, but I thought the _start_ was fine. It's all based on guesswork from a small number of samples I have, so I'm by no means certain it's right...
