### ISSUE TITLE
Drive 0 with greaseweazle hardware

### ISSUE THREAD

**Issue by drdpj** [davidgiven/fluxengine#470]
I've been poking at this a bit - using greaseweazle hardware, I can happily access 5.25" drives I've set as drive 1, but drive 0 just seems to trigger the activity light and then do nothing. It's definitely not the drives, as jumpering them to 1 and accessing as drive 1 has them working fine.

**Comment by davidgiven** [comment]
I discovered recently that the GreaseWeazle software defaults to Shugart bus type while the FluxEngine client defaults to PC bus type. The symptoms you're describing sounds like you have Shugart drives --- try `--usb.greaseweazle.bus_type=SHUGART` and see if that helps.

**Comment by drdpj** [comment]
Yup, that works! Thanks :)
