### ISSUE TITLE
Update dependency list

### ISSUE THREAD

**Issue by ZHolyhell** [davidgiven/fluxengine#487]
When trying to make newest version of fluxengine I get an error stating 
/bin/sh: 1 wx-config: not found
Makefile: 49: *** You must have these wx-config installed. Stop.

Looking this up in Google eventually told me to install libwxgtk3.0-gtk3-dev and libwxgtk3.0-gtk3-0v5

Attempting to install these lead to more errors mostly involving libmount1:i386 not being configured 

I am assuming this mess is all related to the new gui

**Comment by davidgiven** [comment]
Curses. Yes, it is --- I forgot to update the README. Will fix.
