### ISSUE TITLE
Not sure how to continue chasing apple2 format problems

### ISSUE THREAD

**Issue by jepler** [davidgiven/fluxengine#491]
The apple2 format round-trips quite perfectly via .scp/.flux files. However, images written to media basically don't verify in fluxengine; sometimes, if I'm lucky, the media will read in my Apple II but unreliably even there.

Typical commandline (acting only on c0/h0 for quicker turnaround)
```
./fluxengine write apple2 -i dos33-phys.img  --flux_sink.rescale 0.833 --flux_sink.drive.high_density 0 -c 0 -h 0 --no-verify
./fluxengine-debug read apple2 -o blub.img -c 0 -h 0  --decoder.retries 1
```

Occasionally, in the read back flux, there's a '1' where the scp had a '0', as in the third line here. This pattern seems to account for the majority of the errors. Here's one example, where correct is on the left and wrong is on the right. This is some debug code I added into fluxengine which shows the whole track as I believe the Apple disk interface's state machine would interpret it. (32) means it was a 32 microsecond byte, there are magic 40-micosecond bytes, ff(40) with two extra '0' bits at the end, used to synchronize the receiver.

```
10111001        b9(32)                                          10111001        b9(32)
10100110        a6(32)                                          10100110        a6(32)
10100111        a7(32)                                        | 10101111        af(32)
11110101        f5(32)                                          11110101        f5(32)
11110101        f5(32)                                          11110101        f5(32)
```

Repeating the same test over and over again (write & read) the errors 'move around'; every sector of track 0 is readable at some point so it's not data dependent, but errors are frequent enough (37% of sectors) that there's never a "full good track" within a reasonable period of time/retries.

Using the very same drive & media I can 100% write and verify an ibm360 image. Some tracks require a 2nd read attempt but that is rare (1-2 tracks per full disk surface written):
```
./fluxengine write ibm360_525 -i random-360k.img  --flux_sink.drive.high_density 0
```

(why do I have to specify the flux rescale with apple2 but not ibm360?)

I didn't think that the flux specs of a low density 360kB image and an apple 2 gcr floppy image were that different, don't both formats have gaps of 4/8/12 microseconds (at 300rpm, 3.33/... at 360rpm)?

All tests with:
 * teac fd-55gfr at 360rpm
 * genuine greaseweazle v4 with firmware 1.0
 * new old stock 5.25 floppies from ebay

**Comment by davidgiven** [comment]
You might like to try the response analysis described at https://cowlark.com/fluxengine/doc/driveresponse.html to see if there are any particular intervals which the drive doesn't like. (Which I doubt.)

It's probably a flux decoder issue. If you can determine the exact location of an incorrect bit, `fluxengine inspect -F` will show the locations of the pulses themselves.

**Comment by jepler** [comment]
drive response looks clean.

![analysis](https://user-images.githubusercontent.com/1517291/157542763-638b2a48-aae9-4e13-9836-25c69a7f5726.png)

OK, this is wild. Why in the world would this workflow _WORK_?  I think it points at some kind of problem with fluxengine's flux writing code, or with my writing commandline in FE. (hmm I didn't tell gw to use low density, though the media is low density.. how DO you tell gw to use low density anyway?)
```
./fluxengine write apple2 -i dosdos.img -d dosdos.scp
../greaseweazle/gw write dosdos.scp
./fluxengine read apple2 --decoder.retries=37
...
     Tracks -> 1         2         3         
H.SS 0123456789012345678901234567890123456
0. 0 .....................................
0. 1 .....................................
0. 2 .....................................
0. 3 .....................................
0. 4 .....................................
0. 5 .....................................
0. 6 .....................................
0. 7 .....................................
0. 8 .....................................
0. 9 .....................................
0.10 .....................................
0.11 .....................................
0.12 .....................................
0.13 .....................................
0.14 .....................................
0.15 .....................................
Good sectors: 592/592 (100%)
Missing sectors: 0/592 (0%)
Bad sectors: 0/592 (0%)
```
The resulting disk still isn't perfect in the Apple 2 (it can load DOS but there are still 'read error' honking noises during the process), and as you see I needed multiple retries above to read it with fe, but ... it is weird that it works _that much better_ than writing directly with fluxengine. 

(hm maybe the density pin setting was sticky from running fluxengine earler, `gw pin get 2` says `Pin 2 is High (5v)`)

**Comment by davidgiven** [comment]
Yeah, that's extremely interesting. There's a chance that this is manifesting a bug in the GreaseWeazle bytecode conversion (lib/usb/greaseweazle.cc). I'll have a look at comparing the bytecode which the gw tool makes with the bytecode that fluxengine makes.

**Comment by jepler** [comment]
It seems to match +- 1 count (= 14ns, so insignificant), I couldn't spot any bug in `lib/usb/greaseweazle.cc` related to this conversion.

Fluxengine:
```
Sending 479 as two bytes: 250 230      
Sending 480 as two bytes: 250 231
Sending 481 as two bytes: 250 232
Sending 720 as two bytes: 251 216
Sending 721 as two bytes: 251 217
```

Greaseweazle:
```
sending 480 as 250 + 231
sending 481 as 250 + 232
sending 720 as 251 + 216
sending 721 as 251 + 217
```

**Comment by jepler** [comment]
hmmm does it turn out to be necessary to specify the density of both the flux source and sink? This combination gave me a bootable disk direct from fluxengine:
```
./fluxengine write apple2 --decoder.retries 37 --flux_sink.drive.high_density 0 --flux_source.drive.high_density 0 --flux_sink.rescale 0.833
```
This gave me a disk that boots and reaches the command prompt. It still blows one 'corrected error' raspberry every other reboot but that's far and away the best result I've had to date.

does it make sense to put these flux source/sink settings in apple2.textpb or is that trying to be too helpful? Otherwise, should this guidance go in apple2.md?

**Comment by davidgiven** [comment]
Yes, the source and sink both need density configuration. That's stupid; I'll fix that by adding a new drive top-level configuration option.

The rescale option is a stopgap measure intended to allow formats set up for 300rpm drives to work on 360rpm drives and vice versa, and it needs to go away as this should all happen automatically based on the detected drive speed. But that's more complicated and will require some careful thought.

**Comment by davidgiven** [comment]
I've done the config change; it's in https://github.com/davidgiven/fluxengine/tree/drive if you want to take a look.

**Comment by jepler** [comment]
Great, I'll keep an eye out and update our internal docs when you add the new flag.
