### ISSUE TITLE
--decoder.retries does not seem to have an effect (Greaseweazle HW)

### ISSUE THREAD

**Issue by anttivs** [davidgiven/fluxengine#499]
I do not seem to be able to get --decoder.retries to work. I am using Greaseweazle V4 firmware v1.1 with a FluxEngine I compiled today, on Mac OS Big Sur.

For example, trying to image a disk:
`./fluxengine read commodore1541 -o image.d64 --usb.greaseweazle.port /dev/cu.usbmodem14101 --decoder.retries=2`
on a bad disk results in seemingly unbounded retries, the output says
`retrying; xx retries remaining`
with xx just going up and up all the time, like this:

```
(snip)
7.0: 0 ms in 61009 bytes
      15 raw records, 2 raw sectors; 2.74us clock (365kHz)
      sectors: 6! 8! 10! 2!
      logical track 3.0; 29.0
      1024 bytes decoded
      retrying; 32 retries remaining
 7.0: 0 ms in 60353 bytes
      21 raw records, 3 raw sectors; 2.74us clock (365kHz)
      sectors: 6! 8! 10! 2!
      logical track 3.0; 29.0
      1024 bytes decoded
      retrying; 33 retries remaining
 7.0: 0 ms in 60722 bytes
      16 raw records, 2 raw sectors; 2.72us clock (368kHz)
      sectors: 6! 8! 10! 2!
      logical track 3.0; 29.0
      1024 bytes decoded
      retrying; 34 retries remaining
(snip)
```

**Comment by davidgiven** [comment]
Yup, that's a bug.
