### ISSUE TITLE
PSoC Build error in main.c

### ISSUE THREAD

**Issue by mathe1** [davidgiven/fluxengine#50]
Hi again,
today I want get new images from my bother disks.
Software told me "Error: your FluxEngine firmware is at version 4 but the client is for version 5; please upgrade"

So I downloaded the thing for PSoC Creator, update components, clean and build the project.

> main.c: In function 'cmd_set_drive':
main.c:573:44: error: 'struct set_drive_frame' has no member named 'high_density'
         current_drive_flags = f->drive | (f->high_density<<1);
                                            ^
The command 'arm-none-eabi-gcc.exe' failed with exit code '1'.
--------------- Rebuild Failed: 03/24/2019 16:29:42 ---------------

Did I anything wrong?

**Comment by mathe1** [comment]
After comment out: `current_drive_flags = f->drive;// | (f->high_density<<1);`
it buids complete. Then program.

But run the software contuing tells me: "firmware version 4, need 5"

**Comment by mathe1** [comment]
In protocol.h in line 6 I set FLUXENGINE_VERSION = 5
Now it works.

**Comment by davidgiven** [comment]
That change should never have been checked in on the master branch --- it's experimental; I've backed it out. However, it should have at least built. It sounds like your protocol.h and your FluxEngine.cydsn directory got out of sync. Are you copying the FluxEngine.cydsn directory somewhere before building it with PSoC Creator?

**Comment by mathe1** [comment]
I renamed the "FluxEngine.cydsn" folder to "FluxEngine.cydsn-old".
Then from zip I extract only the FluxEngine.cydsn folder into .\PSoC Creator\fluxengine-master.

But I see newer filedates also in the -old folder...

**Comment by davidgiven** [comment]
Could you check an entire clean copy out from github (downloading the zip file is fine) and build from there, rather than copying the FluxEngine.cydsn folder elsewhere, please, and let me know if that works?

**Comment by mathe1** [comment]
Compiling Firmware... success.

Make Software... there are some issues, but it compliles all in result OK.

> [62/136] Compiling C++ object 'ibmdecoderlib@sha/lib_ibm_decoder.cc.o'.
../lib/ibm/decoder.cc: In Elementfunktion »virtual SectorVector AbstractIbmDecoder::decodeToSectors(const RawRecordVector&, unsigned int)«:
../lib/ibm/decoder.cc:23:26: Warnung: Vergleich zwischen vorzeichenbehafteten und vorzeichenlosen Ganzzahlausdrücken [-Wsign-compare]
         if (bytes.size() < (headerSize + 1))
             ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~

But I didn't program the cypress adapter. And so I work with the version "5" before, if there is no critical problem.....
