### ISSUE TITLE
Can't "write" flux to `au:`?

### ISSUE THREAD

**Issue by jepler** [davidgiven/fluxengine#504]
I noticed that I can't write to a kind of flux sink that isn't also a flux source. So for example, this fails but I think it should be possible for it to succeed:
```
$ ./fluxengine write ibm360_525 -i empty-360k.img -d au:noise/
Error: unrecognised flux source 'au:noise/'
```

**Comment by davidgiven** [comment]
Hm. Yes, that's because of the setup for verification --- it's trying to configure the sink as a source as well so that the data can be read back. That ought to be a relatively simple fix...

**Comment by davidgiven** [comment]
This should work now.

**Comment by jepler** [comment]
thanks!
