### ISSUE TITLE
Add DMF support

### ISSUE THREAD

**Issue by hadess** [davidgiven/fluxengine#514]
Based on this [Reddit comment](https://www.reddit.com/r/vintagecomputing/comments/tokh9w/help_with_nonstandard_floppy_formats/i26lerd/?utm_source=reddit&utm_medium=web2x&context=3), I'm filing this issue for Fluxengine support for DMF files. I'm interested in reading that format to verify some original software I have, but I could easily imagine someone being interested in writing to make backup copies.

I use a Greaseweazle (v4), and have access to MS Works '95 installation disks which use DMF for disk 2 onwards.

Happy to test support, or help fund it. Let me know.

**Comment by markusC64** [comment]
What's the problem? I can decode the attached dmf image by

fluxengine read ibm -s bda-dmf.scp -o foo.img

[dmf.7z.zip](https://github.com/davidgiven/fluxengine/files/8773013/dmf.7z.zip)

**Comment by davidgiven** [comment]
It's writing that requires a custom profile; also, IBM disks can't be reliably auto-generated (trying too do so was a big, but useful, mistake) so it'd be good to have a profile available. I'll take a look.

**Comment by markusC64** [comment]
IBM? https://en.wikipedia.org/wiki/Distribution_Media_Format clains that it has been used by Microsoft. Perhaps you mix DMF up with XDF which IBM has been using.

**Comment by davidgiven** [comment]
Oops --- completely forgot about this...
