### ISSUE TITLE
Request: console-only build

### ISSUE THREAD

**Issue by mistydemeo** [davidgiven/fluxengine#523]
I only use the commandline tool, and don't need the GUI tool. The `Makefile` currently makes WXWidgets mandatory, and can't build if WX isn't present. I'm currently sticking with Fluxengine revisions I built from source in December, but it'd be great to be able to build CLI-only versions of the current software.

There's any interest in this, I'm glad to contribute patches to make it possible.

**Comment by davidgiven** [comment]
That's reasonable, but annoying to do. I actually want to rework the build system at some point --- again --- so let me see what I can do.

**Comment by davidgiven** [comment]
This should now work. Try `make fluxengine` (or `fluxengine.exe` on Windows).

**Comment by mistydemeo** [comment]
Thanks! That did the trick - CLI tool builds fine again now.

It looks like the `private` directives you're using now aren't compatible with the older gmake that Apple ships. That's not a problem for me - I can easily install a newer one - but it may be worth documenting in the build instructions that you require something newer.

**Comment by mistydemeo** [comment]
No wait, you already do. Ignore that, then! Thanks.
