### ISSUE TITLE
Packaging issues

### ISSUE THREAD

**Issue by VorpalBlade** [davidgiven/fluxengine#525]
I'm looking to package this for Arch Linux AUR (https://aur.archlinux.org/) as a `-git` package, as there are no releases for this repo.

However I ran into some issues:

1. There doesn't seem to be any install targets? Is the preferred method for the packaging script to copy the built binaries "by hand" so to speak? Or am I missing something?
2. There doesn't seem to be a way to build just to release build, both the debug and release build are built from make all (via ninja). The best I could come up with is:
```
make .obj/build.ninja
ninja -f .obj/build.ninja fluxengine fluxengine-gui brother120tool upgrade-flux-file
```
3. The Makefile seems to override the distro provided CFLAGS/CXXFLAGS. This is frowned upon by Arch Linux packaging guidelines, as distro-wide flags such as `-fstack-clash-protection` etc will not be applied for this package.
4. There does seem to be some test programs, but no `make test` or `make check`. What is the proper way to execute these presumably unit tests?
5. Installing documentation. I don't even know where to begin, as there doesn't seem to be any make docs target?
6. Vendored dependencies. You seem to have vendored agg, emu, fmt etc. I don't see an obvious way to use system installed versions instead. That is generally preferred by Linux distros. At least `fmt` is already packaged by Arch Linux.

I would be grateful for any assistance and advice you can provide.

**Comment by davidgiven** [comment]
Thanks for doing this --- as you may have observed, things aren't really set up for any kind of package building yet.

(1) There isn't anything to install; the binaries should be standalone. Copy by hand to the desired location.
(2) Correct. This probably wants a make target to build the four programs you identified.
(3) That's a makefile bug; it should be using CFLAGS += etc.
(4) Tests are run on every build.
(5) There isn't any documentation to install! Or rather, there is documentation, but it's set up to be viewed on the web. Look in the `doc` directory. For local installation it'll need conversion to HTML and nroff, I would think?
(6) Yes, Debian does the same (I maintain a couple of packages there). And it's really annoying, so I haven't bothered to do it for fluxengine yet. In the specific case of fmt, I'm not sure why I opted for a local copy. mingw32, perhaps?

I'm actually looking at reworking the build system to use bazel, but the results aren't encouraging. In particular, it really likes downloading and then compiling libraries behind the scenes, so you always end up with a final executable which has its own embedded copy of things like the protobuf libraries, which is bad...

**Comment by VorpalBlade** [comment]
Thanks for the quick reply!

2. Yes that would be nice!
3. I patched that locally in https://aur.archlinux.org/packages/fluxengine-git, but I realised my patch is suboptimal as flags will be copied twice into CXXFLAGS (due to CXXFLAGS in the Makefile also containing CFLAGS).
4. Hm not when I build that way that I only build some targets. A make check/test target would play a lot nicer with packaging. I would suggest the following rough setup (if you want to keep the current default behaviour):
```make
all: programs.opt programs.dbg check

programs.opt: fluxengine fluxengine-gui brother120tool upgrade-flux-file
programs.dbg: ...

check: <whatever is needed to run the tests>
    # Run the tests

install:
    # Copy what I did in the PKGBUILD basically.

```
I'd also get rid of the stripping. Normally that is handled by the distro packaging, as we might want to generate a separate -dbg package for example. If the installed binaries are unstripped that will be handled automatically on Arch Linux at least.

Also, this should probably mostly be done on the ninja side, not in the makefile, though the targets still need to be exposed somehow if we continue using a double layer thing. I used make syntax above since I know that (I only ever used ninja via a generator, thus the syntax is not as familiar to me).

5. Yes probably. HTML docs would be really nice. Man pages would be nice but would require additional work. All of that is lower priority though.
6. I have never used bazel so I can't speak to how it works. I do know however that with both cmake and autotools it is relatively easy to allow switching between vendored or system provided libraries. There is also meson that seems to be popular these days (but I never used it myself as a programmer, only as a user). I don't know how easy it would be using meson. If you care about Win32 using cmake is probably the best option out of those though. CMake can generate a variety of backends (make, ninja, visual studio projects etc).

**Comment by davidgiven** [comment]
I've explored build systems a bit and eventually settled on plan vanilla gmake. FluxEngine is pushing what make can reasonably do but avoiding depending on any more complex (or home-grown) build tool has to be a good thing.

This now properly supports 2 above (it only builds one configuration, now); 3; 4 (via `make tests`); still not 5; and 6 (via autodetecting system packages with pkg-config). agg is still vendored because I'm relying on the `Agg2D` class which for some reason isn't in the system library on Debian.

**Comment by VorpalBlade** [comment]
Sounds great, I'll take a look at this during the weekend.

**Comment by davidgiven** [comment]
The `.exe` extensions are intentional --- make rules get happier if there are extensions. I can probably wrap the main rules with something to rename them, though.

Likewise, `make tests` not rerunning the tests unnecessarily is also intentional. The tests are built in to the dependency graph so they only run if the code changes.

**Comment by VorpalBlade** [comment]
The rename is best done on install probably.

**Comment by VorpalBlade** [comment]
It seems running `make fluxengine.exe` on a clean checkout does not first build all required object files, but simply tries to link nothing. That seems to be a bit of a bug in the dependency handling currently.

The reason I want to do that is that Arch Linux packages has separate "build" and "check" phases, so to follow standard practises the unit tests should be executed during check, not build.

**Comment by davidgiven** [comment]
Sorry, I forgot to tell you.

It actually occurs to me now that the various binaries should probably be built on a `make binaries` pseudo-target rather than on `make all`, to make it easier to just build the binaries without running the tests.

**Comment by davidgiven** [comment]
I've added the `binaries` target.

**Comment by davidgiven** [comment]
(closing as stale)
