### ISSUE TITLE
GUI window sizing seems to be off

### ISSUE THREAD

**Issue by kuro68k** [davidgiven/fluxengine#534]
For some reason the GUI version appears like this on my system:

![image](https://user-images.githubusercontent.com/2674466/173907364-9a721829-73e1-40f4-8125-92a4ee1b1e5d.png)

As you can see the disk image area is tiny and cannot be expanded by any method I can see. It doesn't change size when I resize the window either.

Development build 2022-06-13

Windows 8.1 x64. 4k monitor.

**Comment by kuro68k** [comment]
Seems very likely, something about the DPI messing up the maths. I run at 175% scaling.

**Comment by davidgiven** [comment]
I don't know what's going on here. The application has no manifest and is therefore not HiDPI-aware, I think? This means that sizes should be in scaled pixels, not native pixels. So I don't know why this is being rendered incorrectly. All the text and control widgetry looks correct.

**Comment by kuro68k** [comment]
I tried the compatibility option to disable display scaling, but it did not help.

**Comment by davidgiven** [comment]
I _think_ this should be fixed now with the new GUI.

**Comment by kuro68k** [comment]
Thanks, I will test it when there is a release.
