### ISSUE TITLE
Merging multiple flux reads

### ISSUE THREAD

**Issue by tdaede** [davidgiven/fluxengine#536]
It would be nice to concatenate multiple flux reads to the decoder. For example, I read a floppy, cleaned it, then read it again, and would like to merge the good sectors from both reads.

**Comment by GWHAYWOOD** [comment]
There's a merge facility in recent fluxengine versions, I've used it with some success on marginal sectors.

Does it do what you need?

If so this issue can probably be closed.

**Comment by tdaede** [comment]
I ended up writing a standalone tool for track-wise manual merges: https://github.com/tdaede/scpweave

Using the new merge feature would have likely worked as well (when decoding to an image format).
