### ISSUE TITLE
GUI browse of D64 image results in: error: no filesystem configured

### ISSUE THREAD

**Issue by wybren1971** [davidgiven/fluxengine#577]
When i use the latest build and i want to browse (in the gui) a d64 image (which on the command line works) i get an error massage Error: No filesystem configured. when a customize the format and add a line "filesystem=cbmfs" i get the error Error: can't set this config value type. 
What am i doing wrong? i tried all the formats: commodore1541t35, commodore1541t40 and commodore1581

thank in advance and i like the GUi so far... thanks
My system is Ubuntu 22.04 LTS.

Wybren

**Comment by wybren1971** [comment]
Update. if i don't split the format config files (in a _commodore1541 and a commodore1541t35). then the browsing works. It seems the GUI has difficulties with the split proto config files..

**Comment by davidgiven** [comment]
_facepalm_ Yes, it does.

This should only take a few minutes to fix...

**Comment by wybren1971** [comment]
that sounds great! happy to help:-)

**Comment by davidgiven** [comment]
Should be fixed, now. Thanks for reporting and debugging...
