### ISSUE TITLE
Greaseweazle V4

### ISSUE THREAD

**Issue by IndigouFox** [davidgiven/fluxengine#587]
Trying to write commodore 1541 format with real disks and d64 file, have tried both HD and non HD disks and with 35 track disk setting and 40 tracks. Have also tried multiple different disk brands.

Can not use format disk option, every time it gives "error: unimplemented operation"

It almost seemed to have worked once (the first time I tried), every time since has failed "Error: fatal error on write".

Have tried different cables just in case but still the same error.

**Comment by IndigouFox** [comment]
D64: reading image with 39 tracks, 1 heads
Measuring rotational speed... 166.3ms (360.8rpm)
Measuring rotational speed... 166.3ms (360.8rpm)
 0.0: writing 166 ms in 55005 bytes
 1.0: erased
 0.0: 199 ms in 65472 bytes
 1.0: 199 ms in 72128 bytes
      48 raw records, 20 raw sectors; 2.70us clock (370kHz)
      sectors: 0.0.0? 0.0.1? 0.0.2! 0.0.3? 0.0.4! 0.0.5! 0.0.6! 0.0.7! 0.0.8! 0.0.9! 0.0.10! 0.0.11 0.0.12 0.0.13! 0.0.14! 0.0.15! 0.0.16? 0.0.17? 0.0.18! 0.0.19! 0.0.20!
      4096 bytes decoded
      bad read
      retrying; 5 retries remaining
 0.0: writing 166 ms in 55005 bytes
 1.0: erased
 0.0: 199 ms in 65512 bytes
 1.0: 199 ms in 72216 bytes
      52 raw records, 23 raw sectors; 2.70us clock (370kHz)
      sectors: 0.0.0? 0.0.1! 0.0.2! 0.0.3? 0.0.4! 0.0.5! 0.0.6! 0.0.7! 0.0.8! 0.0.9 0.0.10! 0.0.11! 0.0.12! 0.0.13! 0.0.14! 0.0.15! 0.0.16! 0.0.17? 0.0.18! 0.0.19! 0.0.20!
      4608 bytes decoded
      bad read
      retrying; 4 retries remaining
 0.0: writing 166 ms in 55005 bytes
 1.0: erased
 0.0: 199 ms in 65470 bytes
 1.0: 199 ms in 71556 bytes
      49 raw records, 18 raw sectors; 2.70us clock (370kHz)
      sectors: 0.0.0! 0.0.1! 0.0.2! 0.0.3! 0.0.4! 0.0.5? 0.0.6! 0.0.7? 0.0.8! 0.0.9! 0.0.10! 0.0.11! 0.0.12! 0.0.13! 0.0.14? 0.0.15! 0.0.16? 0.0.17! 0.0.18! 0.0.19! 0.0.20!
      4352 bytes decoded
      bad read
      retrying; 3 retries remaining
 0.0: writing 166 ms in 55005 bytes
 1.0: erased
 0.0: 199 ms in 65434 bytes
 1.0: 199 ms in 71661 bytes
      49 raw records, 21 raw sectors; 2.57us clock (388kHz)
      sectors: 0.0.0? 0.0.1? 0.0.2? 0.0.3? 0.0.4? 0.0.5? 0.0.6? 0.0.7 0.0.8? 0.0.9? 0.0.10? 0.0.11 0.0.12? 0.0.13? 0.0.14? 0.0.15? 0.0.16? 0.0.17? 0.0.18? 0.0.19? 0.0.20?
      512 bytes decoded
      bad read
      retrying; 2 retries remaining
 0.0: writing 166 ms in 55005 bytes
 1.0: erased
 0.0: 199 ms in 65393 bytes
 1.0: 199 ms in 71495 bytes
      50 raw records, 17 raw sectors; 2.70us clock (370kHz)
      sectors: 0.0.0! 0.0.1? 0.0.2? 0.0.3? 0.0.4! 0.0.5! 0.0.6! 0.0.7! 0.0.8? 0.0.9! 0.0.10! 0.0.11! 0.0.12! 0.0.13? 0.0.14? 0.0.15! 0.0.16! 0.0.17? 0.0.18! 0.0.19! 0.0.20!
      3584 bytes decoded
      bad read
      retrying; 1 retries remaining
 0.0: writing 166 ms in 55005 bytes
 1.0: erased
 0.0: 199 ms in 65798 bytes
 1.0: 199 ms in 71528 bytes
      50 raw records, 18 raw sectors; 2.70us clock (370kHz)
      sectors: 0.0.0? 0.0.1? 0.0.2? 0.0.3? 0.0.4! 0.0.5! 0.0.6! 0.0.7! 0.0.8? 0.0.9 0.0.10? 0.0.11? 0.0.12? 0.0.13? 0.0.14? 0.0.15? 0.0.16? 0.0.17? 0.0.18? 0.0.19? 0.0.20?
      1280 bytes decoded
      bad read

**Comment by davidgiven** [comment]
1541 filesystem support is currently read only. But you should be able to write D64 files; it works for me, although as I don't have a C64 I can't test them. What command are you using? Have you told FluxEngine whether you're using a high density disk? (The wrong setting will cause writes to fail.)

Also, I'll note that that 39 track .d64 file looks really weird --- they should be 35 or 40, surely?

**Comment by IndigouFox** [comment]
I am going to blame the disks after more attempts. I had 1 box of labeled/branded Sony MD2DA and it worked without any issues using the GUI on the first try. I then used the next 9 disks and filled them up with games, again all with no errors. 

I am going to assume the bulk box of 500 floppies I bought are in fact not DD but HD which won't work on the C64 :( Sad thing is I only have 10 of those Sony disks and now 500 paperweights.

**Comment by davidgiven** [comment]
Ouch, yeah. You can get away with using HD 3.5" floppies in DD drives but not with 5.25" floppies.

If you're in the US and your disks are NIB you might want to talk to the people at floppydisk.com --- you may be able to do an exchange.

**Comment by IndigouFox** [comment]
Awesome, thanks for the idea. I will shoot him off an email and cross my fingers :)
