### ISSUE TITLE
DSDD - Commodore 64

### ISSUE THREAD

**Issue by IndigouFox** [davidgiven/fluxengine#594]
I have a single side drive for writing disks but DSDD disks so want to make sure I can use both sides. Top side works great, no issues.

I've cut the notch out out on the other side and flipped the DSDD disk over and am trying to write to the back but can't figure out the command to ignore the index pulse (I assume this is what I need to ignore to make it work, but I might be wrong).

**Drive:** Epson SD-700
**Command:**
fluxengine write commodore1541t35 -i RAMPAGEG.D64 --drive.index_source=INDEXMODE_360

**Error:** Error: no such config field 'index_source' in 'drive.index_source'

**Comment by davidgiven** [comment]
You may be out of luck. Most modern drives require seeing the index pulse before they'll start transmitting data. See the section on flippy disks here: http://cowlark.com/fluxengine/doc/faq.html

You might be able to modify your drive, and if you're using actual FluxEngine hardware there are fake index pulses coming out of certain pins which you can use to spoof the drive into responding, but I'm afraid you're on your own there --- I've never done it and can't offer assistance.

**Comment by IndigouFox** [comment]
Ok sounds good, I am guessing if I find a double sided drive it will work normally?

**Comment by IndigouFox** [comment]
Ok, just read the "The reed switch method" that's beyond my capability as of right now. I will stick to single sided. Thanks again! :)
