### ISSUE TITLE
Parameter --decoder.ibm.required_sectors seems to be gone

### ISSUE THREAD

**Issue by sm6uax** [davidgiven/fluxengine#599]
Im trying to use the parameter --decoder.ibm.required_sectors=range but it says that no such config field, try to search in the code for the parameter but cant find it

**Comment by davidgiven** [comment]
This has been removed in favour of the new layouts stuff, which is much cleaner and more flexible. I bet I forgot to update all the documentation, though.

Try something like `--layout.layoutdata.physical.start_sector=1 --layout.layoutdata.physical.count=10`. You're best off creating a text file with your custom layout in it and passing that as a parameter, though.

```
layout {
  layoutdata {
    physical {
      start_sector: 1
      count: 10
    }
  }
}
```

**Comment by sm6uax** [comment]
Thanks for the update, I will try it out

Cheers
