### ISSUE TITLE
Error when trying to format an IBM720 disk

### ISSUE THREAD

**Issue by wybren1971** [davidgiven/fluxengine#602]
I can browse a disk just fine in the fluxengine-gui. but when i insert a disk and hit the "format disk" button then, after entering a label, i  get the following error message:
"Error invalid filesystem: sector 1441 is out of bounds" 

What am i doing wrong?

Kind regards Wybren

**Comment by davidgiven** [comment]
Hmm. IBM, right? On a ibm720 format disk?

What that's doing is complaining that the filesystem code (the fatfs library, in this case) is trying to write to a sector which isn't present in the defined disk layout. I did run into this a few times due to me misusing the library, so I wouldn't be surprised if it happened again. Although I'm pretty sure I tested that specific use case. Can you tell me more about the setup?

**Comment by wybren1971** [comment]
I downloaded the latest sources (git clone) and compiled it on my Ubuntu 22.04 setup.
i started up the fluxengine-gui
i select the format IBM720 and put in a 3,5 DS 135 TPI diskette in de drive.
and it does not matter if i try to browse first and press format there or the format disk button immediately both times i get this error.
If i use a HD disk and select the IBM1440 format the error is the same error but the sector number is  2881 instead of 1441.

Browsing a 5.25 inch commodore disk with the Commodore1541 format selected shows an empty file browser. i dont know if that is related. with the IBM formats browsing is going fine and the files are shown.

I tried both greaseweazle and fluxengine hardware, that doesn't make a difference.

**Comment by wybren1971** [comment]
Error is also manifesting itself in the commandline.
wybren@wybren-desktop:~/git/fluxengine$ ./fluxengine format ibm720
      IMG: read 80 tracks, 2 sides, 720 kB total from ibm720.img
Error: invalid filesystem: sector 1441 is out of bounds

reading goes fine:
`wybren@wybren-desktop:~/git/fluxengine$ ./fluxengine ls ibm720
      IMG: read 80 tracks, 2 sides, 720 kB total from ibm720.img
  NATOA2           11147 A
  NATOA1           11361 A
  OPG6P4.PAS         206 A
  OPG6P7.PAS         257 A
  PIZZA.PAS         2798 A
  PIZZA.BAK         2446 A
  OPGAVE93.BAK       353 A
  OPGAVE93.PAS       363 A
  OPGAVE94.PAS       501 A
  OPGAVE94.BAK       501 A
  MASTERMI.BAK       826 A
  MASTERMI.PAS       827 A
  PROEFC            1864 A
  PROEFD             978 A
  AUTO.BAK          1547 A
  AUTO.PAS          1534 A
  SCRIPINL          2070 A
  SCRIP2            1012 A
  SCRIP3            2474 A
  SCRIP4            1606 A
  SCRIP5            3999 A
  SCRIP6            5830 A
  MEET              1996 A
D VERSLAG              0 
  WPEXTRAO          2695 A
  NEDINH            2402 A
  NAT02            11069 A
  CIJFERS.WKQ       2395 A
  CIJFERS2.WKQ      2421 A
  CIJFERS.PIC       2955 A
  OPDRACHT.WKQ     10441 A
  ZOEKMAX1.PAS       421 A
  ZOEKMAX1.BAK       421 A
  ZOEKMIN.BAK        420 A
  ZOEKMIN.PAS        420 A
  ZOEKMAX2.PAS       523 A
  FACULTEI.PAS      1095 A
  FORMBLOK.WP5      1992 A
  LES1.WP5          3528 A
  FORMULE1.WP5      4038 A
  LES2.WP5          9414 A
  NEDRL             3897 A
  FACULTEI.BAK       921 A
  TURBO.PCK         1201 A
  GETAL.BAK          666 A
  FI.BAK               9 A
  FO.TXT              24 A
  GETAL.PAS          666 A
  FI.TXT              19 A
  NEDTIT            1742 A
D PASDATA              0 
(51 files, 122291 bytes)
`

**Comment by number42net** [comment]
I'm running into the same issue, both with IBM720 and IBM1440 format operations:

```
% fluxengine format ibm1440 -f drive:0
Measuring rotational speed...       Using FluxEngine 9A000208180C0614
200.0ms (300.0rpm)
Measuring rotational speed... 200.0ms (300.0rpm)
Error: invalid filesystem: sector 2881 is out of bounds

 % fluxengine format ibm720 -f drive:0
Measuring rotational speed...       Using FluxEngine 9A000208180C0614
200.0ms (300.0rpm)
Measuring rotational speed... 200.0ms (300.0rpm)
Error: invalid filesystem: sector 1441 is out of bounds
```

Reading and writing images works fine for both types. 

I build the firmware (on Windows) and client app (on Linux) directly from the master branch, cloned on 2022-10-17.

**Comment by davidgiven** [comment]
Okay, there's clearly something wrong here (it _used_ to work). Let me take a look.

**Comment by davidgiven** [comment]
I finally have some time to look into this... and it seems that this only manifests when compiling with optimisation enabled. Um, yay?
