### ISSUE TITLE
The --doc option is still broken

### ISSUE THREAD

**Issue by Yserra** [davidgiven/fluxengine#609]
Hi David, 

As mentioned in #598 the --doc option seems to be still broken. 

What I tried: 
`fluxengine read ibm720 --doc`

What I got: 
Infinite loop, no text printed on screen, until I press CTRL-C

What I expected:
Should show the available configuration options and halt.

Tested on:
Source code downloaded from Github Repository on October 18th, 2022
MacBook pro M1 with macOS 12.6
Python 3.10.8
libusb: stable 1.0.26
pkg-config: stable 0.29.2
sqlite: stable 3.39.4
protobuf: stable 21.7
truncate: stable 0.9 -> but this binary is NOT used. Because: "Disabled because it has a removed upstream repository! Conflicts with: coreutils (because both install `truncate` binaries), uutils-coreutils (because both install `truncate` binaries)"
coreutils: stable 9.1
wxwidgets: stable 3.2.1
fmt: stable 9.1.0
Greaseweazle F7 v3 "Thunderbolt", firmware 1.2

Might be of interest:
The options --help and --config are working as expected.

Many thanks for all your work.

**Comment by davidgiven** [comment]
Took long enough, but I've finally gotten around to fixing this. Thanks for the report.

**Comment by Yserra** [comment]
Many thanks. Tested. Works as expected now. Great job!
