### ISSUE TITLE
Is it possible to replace CY8CKIT-059 with other model boards?

### ISSUE THREAD

**Issue by OldMadMan** [davidgiven/fluxengine#612]
Hello developer,

I‘d like to ask if it is possible to replace CY8CKIT-059 with other model of boards. This is because CY8CKIT-059 is currently out of stock worldwide, and it is no longer possible to buy it on shopping websites at normal prices. If user must buy the spot, the price is often hyped to ten times the original price (about $170 USD for example). 

Not sure if there is an alternative solution, thank you very much.

**Comment by davidgiven** [comment]
Sorry for the delay, other projects...

No. Last I looked there was an 80-week order time. I have been wondering about cheap replacement hardware, but honestly I'd probably recommend getting a Greaseweazle. They do everything with FluxEngine does (except for hard sectored disks), and are rather better designed. They're more expensive but you don't have to build anything. See, for example: https://amigastore.eu/en/894-greaseweazle-v4.html
