### ISSUE TITLE
Building on windows

### ISSUE THREAD

**Issue by patzik** [davidgiven/fluxengine#62]
I am unable to build it on windows.
Installed cygwin and the 3 mentioned packages but get an error.

$ make
meson .obj
process_begin: CreateProcess(NULL, python3 C:\cygwin64\bin\meson .obj, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [.obj/build.ninja] Error 2

**Comment by patzik** [comment]
I had to install some more libraries, but now I am still stuck. It complains about sqlite3 not being installed, but it is.. Am I missing something?

$ make all
meson .obj
The Meson build system
Version: 0.49.2
Source dir: /home/Game PC
Build dir: /home/Game PC/.obj
Build type: native build
Project name: fluxclient
Project version: undefined
Native C compiler: cc (gcc 7.4.0 "cc (GCC) 7.4.0")
Native C++ compiler: c++ (gcc 7.4.0 "c++ (GCC) 7.4.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.6.0)
Dependency libusb-1.0 found: YES 1.0.21
Found CMake: /usr/bin/cmake (3.6.2)
Dependency sqlite3 found: NO (tried pkgconfig and cmake)

meson.build:5:0: ERROR:  Dependency "sqlite3" not found, tried pkgconfig and cmake

A full log can be found at /home/Game PC/.obj/meson-logs/meson-log.txt
make: *** [Makefile:6: .obj/build.ninja] Error 1

**Comment by davidgiven** [comment]
Did you install the sqlite3-devel package, or just the sqlite3 runtime library?

**Comment by patzik** [comment]
Installed some more libs which contained sqlite3 in the name and finally I got it to compile, don't know which library was required but it works now.

**Comment by patzik** [comment]
I don't have the FluxEngine programmed/connected yet. When running the exe's I get 'program stopped working' crash, is this normal behaviour without the FluxEngine connected?

**Comment by patzik** [comment]
I was running it in windows, I see I have to run it in cygwin, working now. Now just have to build it...

**Comment by patzik** [comment]
I built the fluxengine, and got it to work somewhat...
When reading an amiga disk, after reading all I get is XXXXX's line after line, and it keeps scrolling until I close Cygwin.
Also tried writing a raw flux file, but I get this error. Are there any parameters I need to add?
$ .obj/fe-writeflux
Error: two flags use the name '--high-density'

**Comment by patzik** [comment]
This is another error I get

$ .obj/fe-writetestpattern
Writing to: :d=0:s=0-1:t=0-81
  0.0: 200 ms in 100000 bytes
  0.1: Error: failed to receive command reply: Pipe error

**Comment by davidgiven** [comment]
Can you capture the entire output of the Amiga read and attach it here? (Run `script` before the command, do `exit` afterwards, and it'll log everything to a file called `typescript`.) It sounds like it's trying to read garbage and thinks your disk has far too many sectors, but I need the log to know more.

Regarding writing files: that doesn't actually work in any useful fashion for disks other than Brother word processors. I'm working on this --- it needs all the write layer to be refactored. `fe-writetestpattern` failing is odd, though, and suggests you don't have enough USB bandwidth. Could you try `fe-testbulktransport` and tell me what it reports?

**Comment by patzik** [comment]
Transferred 1048576 bytes in 1196 (855 kB/s)
I can't type exit afterwards, since the program never stops writing the XXX's
Hope you can add support for writing raw flux files soon!

**Comment by patzik** [comment]
You probable already know this site http://hxc2001.free.fr/, there is a tool on this site which allows you to convert all sorts of floppy formats maybe the guy that wrote this can help you in support for different formats like ipf and hfe. The tool allows you to convert for instance an ipf to raw flux format, wonder if I would be able to write this back to floppy.

**Comment by patzik** [comment]
I have quite a few floppy based retro systems. If you need someone for testing stuff let me know.

**Comment by davidgiven** [comment]
There are now precompiled Windows binaries for the client downloadable from GitHub, so this bug is obsolete --- closing for cleanup.
