### ISSUE TITLE
Issue extracting file from a cpmfs

### ISSUE THREAD

**Issue by brijohn** [davidgiven/fluxengine#635]
I'm getting the following error trying to copy a cpm file from an image: error: invalid filesystem: sector 1869768229 is out of bounds

So obviously that number is garbage, the file in question has three entries in the directory covering extents 0,1 and 2. The first 2 extents work fine however the third one is where the issue is. I tracked the bug to the following line of code. Namely `i` starts of as 32 for the third extent, the other two started at 0. This is obviously wrong as the allocation map is only 16 entries long.

https://github.com/davidgiven/fluxengine/blob/4922d1deb487ad0525e22b648b2c5a5a9f4b6348/lib/vfs/cpmfs.cc#L214-L215

I'm not sure what that line is trying to calculate but it seems to me you should always be starting at 0 for this loop so it will look through each entry of the allocation map? Regardless the initial value certainly should not start higher then the max size of the vector.

**Comment by davidgiven** [comment]
The CP/M filesystem is a masterpiece of minimalism, but intuitive it's not. Do you have a disk image I can test against?

**Comment by brijohn** [comment]
Yeah here is the disk image as well as the custom profile i'm using. The file in question is help.hlp, which is three extents long.

[nabu.zip](https://github.com/davidgiven/fluxengine/files/10252186/nabu.zip)

**Comment by davidgiven** [comment]
I think this could be as simple as removing the `~` from in front of `_logicalExtentMask`...

**Comment by davidgiven** [comment]
Looks like the CP/M code is extremely broken in several places.

**Comment by brijohn** [comment]
Works fine now, thanks for fixing this.
