### ISSUE TITLE
FB100

### ISSUE THREAD

**Issue by mkarel** [davidgiven/fluxengine#641]
I am trying to recover some of my mom's brother knitting machine disks. She had an FB100 drive but it looks to have bit the dust. I have built at Blue Pill GreaseWeasezle and using fluxengine, i am not able to open the disk images it creates. I would love to get this working if possible.

**Comment by davidgiven** [comment]
What are you trying to open it in? If I recall correctly, those knitting machines don't actually use a filesystem but instead just do raw sector access, so you won't be able to see anything like files on the disks. I have found https://github.com/adafruit/knitting_machine which may be of some help.

If you know of any documentation on the disk layout it may be possible to add FluxEngine support for reading data in some fashion which is easier to work with than just a hex dump --- there is some file system support which could be made to work. But I have very little knowledge of how the pattern data works.

**Comment by mkarel** [comment]
Thanks, that is very helpful. I figured there was some sort of file
structure.  I will review the adafuit project and see if I can get what
I need.

**Comment by davidgiven** [comment]
Good to know --- closing as stale.
