### ISSUE TITLE
Target macOS version 10.15 and later?

### ISSUE THREAD

**Issue by MDBenson** [davidgiven/fluxengine#651]
Hi,

I'm using macOS Catalina 10.15 on my walkabout Laptop (old MacBook) and I can't run FluxEngine as it's not compatible, I suspect your compile target doesn't go back far enough for 10.15. It'd be beneficial for those of us with older Macs to have a bit of legacy support :)

Thanks

**Comment by davidgiven** [comment]
This should just be a matter of adding it to the build matrix, which I've tried. Could you download the build artifact at the bottom of this page and let me know if it works?

https://github.com/davidgiven/fluxengine/actions/runs/4583192601

Note that the 10.15 build environment is deprecated on github, and once it goes away I'm not intending to try and work around it...

**Comment by davidgiven** [comment]
Looks like github has just turned off the 10.15 build environment. Sorry.
