### ISSUE TITLE
Wrong path for wxwidgets/README.md on Mac M1

### ISSUE THREAD

**Issue by Yserra** [davidgiven/fluxengine#653]
Hi David,
Building latest FluxEngine code (downloaded April,2 2023) on Mac M1 fails near one of the last step with the error:

cp: /usr/local/opt/wxwidgets/README.md: No such file or directory
gmake: *** [src/gui/build.mk:60: FluxEngine.app] Error 1

When wxwidgets is installed with Homebrew on a Mac M1, the correct path is:

/opt/homebrew/opt/wxwidgets/README.md

As far as I know, the /usr/local/... path is for Homebrew tools on Mac Intel only. 

Best,

**Comment by davidgiven** [comment]
Duplicate: #643
