### ISSUE TITLE
Apple II disk read problem

### ISSUE THREAD

**Issue by dk1spb** [davidgiven/fluxengine#66]
I can't read the AppleII disk:
`fe-readapple2.exe -s :t=0-79x2:s=0
66.0: 419 ms in 137984 bytes
      63 records, 32 sectors; 4.10us clock;
      Failed to read sector 12 (bad checksum);
      5 retries remaining
66.0: 419 ms in 137984 bytes
     0 [main] fe-readapple2 1380 cygwin_exception::open_stackdumpfile: Dumping stack trace to fe-readapple2.exe.stackdump'

Each time on different track.

Is it USB speed problem?
`fe-testbulktransport.exe
Transferred 1048576 bytes in 1401 (730 kB/s)`
I have trying on Lenovo T480s USB 3.0 port.

Also I have warning: "sta.M0019:Warning-1366: Setup time violation found in a path from clock.."
`

Clock | Domain | Nominal Frequency | Required Frequency | Maximum Frequency | Violation
-- | -- | -- | -- | -- | --
CounterClock(routed) | CounterClock(routed) | 12.800 MHz | 12.800 MHz | N/A |  
CyILO | CyILO | 100.000 kHz | 100.000 kHz | N/A |  
CyIMO | CyIMO | 24.000 MHz | 24.000 MHz | N/A |  
CyMASTER_CLK | CyMASTER_CLK | 64.000 MHz | 64.000 MHz | N/A |  
CyBUS_CLK | CyMASTER_CLK | 64.000 MHz | 64.000 MHz | 63.323 MHz | Frequency
CounterClock | CyMASTER_CLK | 12.800 MHz | 12.800 MHz | N/A |  
CyPLL_OUT | CyPLL_OUT | 64.000 MHz | 64.000 MHz | N/A |  
`
Is it OK?

No problem to read this disk with same USB port by KryoFlux :-(

**Comment by dk1spb** [comment]
I can increase USB speed to 950 kB/s with USBFS "DMA with Manual Buffer Management"
But often I got error "Error: data transfer failed: Pipe error".
And no "cygwin_exception::open_stackdumpfile: Dumping stack trace to fe-readapple2.exe.stackdump"

Still can't read track above 70 (physical at 80-track drive).

**Comment by dk1spb** [comment]
cygwin_exception coming in static void replace_sector function

_static void replace_sector(Sector*& replacing, Sector& replacement)
{
	if (replacing && conflictable(replacing->status) && conflictable(replacement.status))
	{
	printf(" point 1\n");
		if (replacement.data != replacing->data)
		{
	printf(" point 1.1\n");
			std::cout << std::endl
						<< "       multiple conflicting copies of sector " << replacing->logicalSector
						<< " seen; ";
	printf(" point 2\n");
			replacing->status = Sector::CONFLICT;
	printf(" point 3\n");
			return;
		}
	printf(" point 4\n");
	}
	if (!replacing || (replacing->status != Sector::OK))
		replacing = &replacement;
	std::cout << " Exit from  " << std::endl;
}_
result is :
 Exit from
 Exit from
 point 1
 point 4
 Exit from
 point 1
      1 [main] fe-readapple2 716 cygwin_exception::open_stackdumpfile: Dumping stack trace to fe-readapple2.exe.stackdump

stackdump is:
_Exception: STATUS_ACCESS_VIOLATION at eip=6F197BCA
eax=20202020 ebx=20202020 ecx=80018020 edx=800EE8E8 esi=800512E6 edi=0065CC82
ebp=0065C9F8 esp=0065C9F8 program=D:\cygwin\home\DK\flux\.obj\fe-readapple2.exe, pid 716, thread main
cs=0023 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame     Function  Args
0065C9F8  6F197BCA (20202020, 20202020, 0065CA88, 61165374)
0065CA18  6F194BC0 (800EE8E8, 0065CA30, 00000002, 00000000)
0065CA48  6F194C20 (800F37C8, 800EE8E8, 0000000C, 6F1975FF)
0065CA68  6F194C7C (800F37C8, 800EE8E8, 0000000E, 800F4028)
0065CA88  6F1818AE (8007F424, 800F37A0, 0065CB40, 0065CB34)
0065CBB8  6F181C35 (0065CBD4, 0065CBEC, 0065CBEB, 6F1831D2)
0065CBF8  0040122F (800512E6, 0065CC82, 0065CD18, 6100AAFA)
0065CD18  6100AAFA (00000000, 0065CD74, 61009A90, 00000000)
End of stack trace_

**Comment by davidgiven** [comment]
Was just about to ask you for the stacktrace --- you read my mind! It absolutely shouldn't be crashing. (730kB/s is a bit low, but you should be all right for low-density disks (which use less bandwidth). No promises, though. I don't think you're hitting that problem, though.)

I don't know how it's managing to fail there. It's obviously a bogus pointer but for it to reach that line it must already have dereferenced both `replacing` and `replacement`. So, the only thing I can think of that's failing is the comparison of the data itself. That's a `Bytes` object defined in `bytes.h`.

Could you edit the makefile to add `--buildtype=debug` on the meson command line, then delete the `.obj` directory, rebuild, and try again? This ought to produce a stack trace with line numbers in it.

The setup time violation error is normal, by which I mean I haven't figured out how to fix it but it doesn't seem to affect operation.

**Comment by dk1spb** [comment]
>Could you edit the makefile to add --buildtype=debug
Debug is already ON.

$ meson configure .obj
Core properties:
  Source dir /home/DK/flux
  Build dir  /home/DK/flux/.obj

Core options:
  Option          Current Value Possible Values                                          Description
  ------          ------------- ---------------                                          -----------
  auto_features   auto          [enabled, disabled, auto]                                Override value of all 'auto' features
  backend         ninja         [ninja, vs, vs2010, vs2015, vs2017, xcode]               Backend to use
  buildtype       debug         [plain, debug, debugoptimized, release, minsize, custom] Build type to use
...

**Comment by dk1spb** [comment]
I have tried cygwin and cygwin64 - same error (cygwin_exception)

**Comment by dk1spb** [comment]
I have tried to run fe-readapple2 under gdb:

54.0: 420 ms in 127808 bytes
       60 records, 30 sectors; 4.12us clock;
       Failed to read sector 1 (bad checksum);
       5 retries remaining
54.0: 420 ms in 127808 bytes

Thread 1 "fe-readapple2" received signal SIGSEGV, Segmentation fault.
0x6f197b5a in std::vector<unsigned char, std::allocator<unsigned char> >::operator[] (this=0xedd6969d, __n=2526451350) at /usr/lib/gcc/i686-pc-cygwin/7.4.0/include/c++/bits/stl_vector.h:798
798             return *(this->_M_impl._M_start + __n);

Could you advice me which version of gcc  you are use?
I will try it.

**Comment by davidgiven** [comment]
I just used whatever the default gcc was in Cygwin.

Did you get a backtrace from gdb?

**Comment by dk1spb** [comment]
>Did you get a backtrace from gdb?
*nix not so easy for me. 
if you mean bt full after error - 
[ff.txt](https://github.com/davidgiven/fluxengine/files/3318589/ff.txt)

**Comment by davidgiven** [comment]
Thanks!

That confirms the issue is comparing the two Bytes objects. However, I don't know _why_. I'll try and get back to you tomorrow about it --- let me think. I definitely want to get this fixed.

**Comment by dk1spb** [comment]
David, thank you for you support!!!

**Comment by davidgiven** [comment]
Could you read the disk with (something like):

`fe-readapple2.exe -s :t=0-79x2:s=0 --write-flux=apple2.flux --just-read`

...and then mail the resulting `apple2.flux` file to me at dg@cowlark.com? (Or send it to me some other way. I promise not to show the file to anyone else and delete it after fixing this issue.)

This will skip the decode stage completely, simply imaging the raw data from the disk. This is normally a very bad idea, as you need to do the decode to ensure that the disk has been read correctly, but in this instance it'll let me duplicate the error at my end.

**Comment by dk1spb** [comment]
>fe-readapple2.exe -s :t=0-79x2:s=0 --write-flux=apple2.flux --just-read
I will do it tomorrow (It's midnight now).

>as you need to do the decode to ensure that the disk has been read correctly
the error occurs not each time. For example, for 10 attempts (the same disk; fe-readapple2.exe -s :s=0:t=0-79x2) 2-3 times full disk can be read without any error, but 7-8 times errors occurs at the different tracks.
I will try again tomorrow

**Comment by dk1spb** [comment]
And the error occurs each time when need 2nd retry.

**Comment by dk1spb** [comment]
I have sent it by e-mail

**Comment by davidgiven** [comment]
Got it --- you gave me the clue I needed to reproduce it locally. Thanks very much!

Could you update from git and let me know whether it fixes your problem?
