### ISSUE TITLE
reading victor9k disks not working

### ISSUE THREAD

**Issue by pauldevine** [davidgiven/fluxengine#685]
I tried imaging a victor9k disk on the latest branch and this is the outcome:
```
% ./fluxengine read victor9k --1224 -s drive:1 -o vicky_kermit.img
      OPTION: 1224kB 80-track DSHD GCR
Measuring rotational speed...       Using GreaseWeazle GW135195034205400002CD9705 on /dev/cu.usbmodem1112401
166.5ms (360.3rpm)
 0.0: Error: hard sectors are currently unsupported on the GreaseWeazel
```
The victor disks aren't hard sectored. Did I miss something in the changes to the command settings?

**Comment by davidgiven** [comment]
That should have been fixed in https://github.com/davidgiven/fluxengine/commit/b4d8d569d261cd37012d4e213b31c7233e80c167. I've also fixed the logging formatting error when measuring the rotational speed, which suggests you're not up-to-date. PTAL?

**Comment by pauldevine** [comment]
Thanks David, you're correct. My apologies for the false alarm.
