### ISSUE TITLE
FluxEngine can't see my Greaseweazle F7 Plus (Windows)

### ISSUE THREAD

**Issue by misterblack1** [davidgiven/fluxengine#712]
Hi, I wanted to test our FluxEngine with my Greaseweazle F7 Plus but it doesn't seem to detect it. Reading the documentation it says it will auto detect either the FluxEngine or GW.  Perhaps I'm doing something wrong or maybe this is due to the new GW firmware? (Firmware: 1.4)

Thanks!

```
C:\Program Files\FluxEngine>fluxengine rpm
Error: cannot find the FluxEngine (is it plugged in?)
```
It will always report this error but the GW hardware is on COM13 and working properly with the GW software. 

```
C:\Program Files\greaseweazle>gw info
Host Tools: 1.15.1
Device:
  Port:     COM13
  Model:    Greaseweazle F7 Plus (Ant Goffart, v2)
  MCU:      216MHz, 256kB SRAM
  Firmware: 1.4
  Serial:   GW002D00363438510C36383538
  USB Rate: Full Speed (12 Mbit/s)
```

**Comment by davidgiven** [comment]
That error message doesn't exist in the client any more, which makes me think you're using an old version. Do you have the latest development version?

**Comment by misterblack1** [comment]
Ah sorry I was running "FluxEngine Windows client version 389"-- I'll try the dev build and report back.

**Comment by misterblack1** [comment]
Ok yes all is good with the latest dev built. Thanks!
