### ISSUE TITLE
Fluxengine GUI unable to open any any image for writing

### ISSUE THREAD

**Issue by misterblack1** [davidgiven/fluxengine#721]
Hi, when I try to select an image to write with FluxEngine GUI I always get "Error: cannot open input file"

I tested by creating a new image off a real 1.44mb MSDOS floppy using Fluxengine GUI, saving it as ibm.img. Then when trying to write it back to the disk, selecting the image I just created gives the error. (Or any other image.) 

I am above to use FluxEngine GUI to browse the 'ibm.img' file and see the contents, so I know this isn't a permission problem with reading the file.

Windows 10 64 + GreaseWeazle + using the latest automated build

![Screenshot 2023-10-23 135848](https://github.com/davidgiven/fluxengine/assets/16782710/514462f3-ef2f-4b99-a92f-98a7bff400eb)

**Comment by davidgiven** [comment]
Yes, that's a bug in the GUI which I'm looking at. The command line version works fine, though.

**Comment by misterblack1** [comment]
Ah ok thanks!

Indeed I was able to write with the command line -- although I'm also running into the write precompensation issue as well.  (I saw another open issue. I can't write IBM images to 3.5" disks with the greaseweazle, although 360k disks do seem to work OK, like Apple II floppies.)
