### ISSUE TITLE
make install gone?

### ISSUE THREAD

**Issue by VorpalBlade** [davidgiven/fluxengine#722]
It appears `make install` has been removed, which breaks the AUR package build.

Also `make binaries` is gone, and `make tests` apparently does nothing?

Note that AUR PKGBUILDS have the following general structure:

```bash
build() {
	cd "$srcdir/${pkgname%-git}"
	# Make all depends on tests, but we want to run them in check() instead.
	make binaries
}

check() {
	cd "$srcdir/${pkgname%-git}"
	make tests
}

package() {
	cd "$srcdir/${pkgname%-git}"
	make install PREFIX=/usr DESTDIR="$pkgdir/"
	install -Dm 644 COPYING.md "$pkgdir/usr/share/licenses/$pkgname/COPYING.md"
	# Installing docs is not yet supported in a reasonable way by upstream.
}
```

Since you have your own home grown build system it is kind of hard to figure out how to do this now after the recent changes.

**Comment by davidgiven** [comment]
Oh, whoops. I forgot you were using that. Will fix.

**Comment by VorpalBlade** [comment]
Hm, doesn't actually seem to work yet:

```
==> Starting package()...
INSTALL
'.obj/src+fluxengine/src+fluxengine' -> '/build/fluxengine-git/pkg/fluxengine-git//usr/bin/fluxengine'
install: cannot create regular file '/build/fluxengine-git/pkg/fluxengine-git//usr/bin/fluxengine': No such file or directory
make: *** [Makefile:59: install-bin] Error 1
```

Not sure if it is on my side or your side, but too late for me to look at it today.

**Comment by davidgiven** [comment]
Whoops. Forgot to add the `-D` to create the directory. Fixed (or will be as soon as the build completes).
