### ISSUE TITLE
Regression: commandline-only build no longer works

### ISSUE THREAD

**Issue by mistydemeo** [davidgiven/fluxengine#729]
The commandline build (added after #523) doesn't seem to be working anymore. In a current build, running `make fluxengine` still ends up trying to invoke `wx-config`. Build logs:

<details><pre>
loading build.py
loading build/c.py
loading build/protobuf.py
loading build/pkg.py
loading build/utils.py
loading config.py
loading src/build.py
loading dep/adflib/build.py
loading dep/agg/build.py
loading dep/fatfs/build.py
loading dep/hfsutils/build.py
loading dep/libusbp/build.py
loading dep/stb/build.py
loading lib/build.py
loading arch/build.py
loading src/formats/build.py
loading scripts/build.py
loading tests/build.py
loading src/gui/build.py
loading extras/build.py
loading src/gui/drivetypes/build.py
loading tools/build.py
loading dep/snowhouse/build.py
fluxengine-testdata not found; skipping corpus tests
.obj/build.mk:3125: *** Required binary 'wx-config' not found..  Stop.</pre></details>

I haven't had a chance to try bisecting yet, but the most recent successful build I did was on August 8th.

**Comment by davidgiven** [comment]
Yup, it was a build system limitation. It should be fixed now --- a simple `make fluxengine` will build just the command line tool.

**Comment by mistydemeo** [comment]
Confirmed, thanks!
