### ISSUE TITLE
fluxengine rpm 

### ISSUE THREAD

**Issue by gianrisa** [davidgiven/fluxengine#740]
Hi I'm trying to use your fantastic tool, I have two challenges, I did use the full windows precompiled setup and looks like as soon as I connect the programmed using the mini usb ( programming went well, successful programmed and all green ) kit to the PC I get in the control panel device manager an exclamation mark about the device driver not installed, what should be the device driver ? shall I install any additional drivers ? 

I did try to connect the usb mini to another pc with linux and I don't get this

[22720.093091] usb 1-1: new full-speed USB device number 14 using xhci_hcd
[22720.244882] usb 1-1: New USB device found, idVendor=1209, idProduct=6e00, bcdDevice= 0.01
[22720.244887] usb 1-1: New USB device strings: Mfr=2, Product=1, SerialNumber=128
[22720.244889] usb 1-1: Product: FluxEngine
[22720.244891] usb 1-1: Manufacturer: Cowlark Technologies
[22720.244892] usb 1-1: SerialNumber: EA00021615121324

trying to run fluxengie rpm I get this :

gianrisa@promaster:~/fluxengie/fluxengine$ sudo ./fluxengine rpm
Error: this only makes sense with a real disk drive
same I get in Windows.

I did check all the steps in the Doc 10 times and looking at the connections are done correctly. What am I missing ?
I'm using the latest version dowloaded from git.

Thanks for your help in advance

**Comment by davidgiven** [comment]
That's kinda weird. Try `fluxengine test bandwidth` --- that'll test communication to the hardware without needing an actual drive connected.

One thing which could be wrong is that you may not have permissions to access the USB device, resulting in it not being detected. You may need something like this in your /etc/udev/rules.d/local.rules:

```
SUBSYSTEM=="usb", ATTRS{idVendor}=="1209", ATTRS{idProduct}=="6e00", MODE="0666"
```

I'll add a command to list detected devices.

**Comment by gianrisa** [comment]
Servus David,

I did some try I'm directly root:
root@promaster:/home/gianrisa/fluxengie/fluxengine# ./fluxengine test bandwidth
      Using FluxEngine EA00021615121324
Reading data: transferred 1048576 bytes from device -> PC in 1070 ms (956 kB/s)
Writing data: transferred 1048576 bytes from PC -> device in 2298 ms (445 kB/s)

trying this:
root@promaster:/home/gianrisa/fluxengie/fluxengine# ./fluxengine rpm
Error: this only makes sense with a real disk drive

all commands execute with roots rights

With windows I gave up I get the device driver error in the control panned device manage ... strange ... 

Thanks
VG Gian

**Comment by gianrisa** [comment]
Hi David,

I have only one drive and It is attached to connector floppy:0 nearest to the controller board. can also attach it to the other connector, and It will work if I add drive:1 

root@promaster:/home/gianrisa/fluxengie/fluxengine# ./fluxengine rpm -s drive:0
      Using FluxEngine EA00021615121324
Rotational period is 200 ms (300 rpm)

I don't know seems that ./fluxengine rpm in my case doesn't detect the floppy.

What about the windows setup why is windows not recognizing the device ? 

Thanks a Million for your product and super direct support !

Bests Gian

**Comment by davidgiven** [comment]
Yes, this turned out to be an incredibly stupid bug at my end. Plus, I added that command --- get the latest version and then do `fluxengine test devices` and you'll get a dump of the detected devices.
