### ISSUE TITLE
Compile Help during 'Make'

### ISSUE THREAD

**Issue by Budghiss** [davidgiven/fluxengine#760]
Hi, I am not a programmer, so I apologize if this is obvious to some. During the 'make' session, it errors out:

lib/config.cc:147:1: error: could not convert ‘{{"FluxEngine (.flux)", std::__cxx11::basic_regex<char>(((const char*)"^(.*\\.flux)$"), (std::regex_constants::syntax_option_type)16), <lambda closure object><lambda(auto:3&, auto:4*)>{}, <lambda closure object><lambda(auto:5&, auto:6*)>{}}, {"Supercard Pro (.scp)", std::__cxx11::basic_regex<char>(((const char*)"^(.*\\.scp)$"), (std::regex_constants::syntax_option_type)16), <lambda closure object><lambda(auto:7&, auto:8*)>{}, <lambda closure object><lambda(auto:9&, auto:10*)>{}}, {"AppleSauce (.a2r)", std::__cxx11::basic_regex<char>(((const char*)"^(.*\\.a2r)$"), (std::regex_constants::syntax_option_type)16), <lambda closure object><lambda(auto:11&, auto:12*)>{}, <lambda closure object><lambda(auto:13&, auto:14*)>{}}, {"CatWeazle (.cwf)", std::__cxx11::basic_regex<char>(((const char*)"^(.*\\.cwf)$"), (std::regex_constants::syntax_option_type)16), <lambda closure object><lambda(auto:15&, auto:16*)>{}}, {"CatWeazle DMK directory", std::__cxx11::basic_regex<char>(((const char*)"^dmk:(.*)$"), (std::regex_constants::syntax_option_type)16), <lambda closure object><lambda(auto:17&, auto:18*)>{}}, {std::__cxx11::basic_regex<char>(((const char*)"^erase:$"), (std::regex_constants::syntax_option_type)16), <lambda closure object><lambda(auto:19&, auto:20*)>{}}, {"KryoFlux directory", std::__cxx11::basic_regex<char>(((const char*)"^kryoflux:(.*)$"), (std::regex_constants::syntax_option_type)16), <lambda closure object><lambda(auto:21&, auto:22*)>{}}, {std::__cxx11::basic_regex<char>(((const char*)"^testpattern:(.*)"), (std::regex_constants::syntax_option_type)16), <lambda closure object><lambda(auto:23&, auto:24*)>{}}, {std::__cxx11::basic_regex<char>(((const char*)"^drive:(.*)"), (std::regex_constants::syntax_option_type)16), <lambda closure object><lambda(auto:25&, auto:26*)>{}, <lambda closure object><lambda(auto:27&, auto:28*)>{}}, {"FluxCopy directory", std::__cxx11::basic_regex<char>(((const char*)"^flx:(.*)$"), (std::regex_constants::syntax_option_type)16), <lambda closure object><lambda(auto:29&, auto:30*)>{}}, {"Value Change Dump directory", std::__cxx11::basic_regex<char>(((const char*)"^vcd:(.*)$"), (std::regex_constants::syntax_option_type)16), <lambda closure object><lambda(auto:31&, auto:32*)>{}}, {"Audio file directory", std::__cxx11::basic_regex<char>(((const char*)"^au:(.*)$"), (std::regex_constants::syntax_option_type)16), <lambda closure object><lambda(auto:33&, auto:34*)>{}}}’ from ‘<brace-enclosed initializer list>’ to ‘const std::vector<FluxConstructor>’
 };
 ^
.obj//build.mk:2455: recipe for target '.obj//.sentinels/+lib/lib/config.cc.mark' failed
make: *** [.obj//.sentinels/+lib/lib/config.cc.mark] Error 1

Would anyone be willing to provide some insight into what I might need to do to get this to work?

Thanks in advance...

**Comment by davidgiven** [comment]
I think your C++ compiler is too old. What platform are you on?

**Comment by Budghiss** [comment]
Hi, thanks for the response. I am on Linux Mint 18 - I know it's legacy, and the writing is on the wall. Which version of gcc do I need - I'm currently on 7.5?

**Comment by Budghiss** [comment]
Ok, you were right - I upgraded to version gcc-9 and it went through - again, thanks for responding...

**Comment by Budghiss** [comment]
Upgraded python 3.9 and gcc-9 for compile.
