### ISSUE TITLE
Error when writing .SCP & .IMG files

### ISSUE THREAD

**Issue by Budghiss** [davidgiven/fluxengine#762]
./fluxengine rawwrite ~/wolf3d/testing/DISK1/DISK1.scp ibm --720_135
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format ConfigProto: 1:4: Invalid control characters encountered in text.
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format ConfigProto: 1:5: Interpreting non ascii codepoint 128.
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format ConfigProto: 1:5: Message type "ConfigProto" has no field named "SCP".
Error: couldn't load external config proto

Not real sure why this is doing this - any help would be greatly appreciated? Thanks in advance...

**Comment by davidgiven** [comment]
Try:

```
fluxengine rawwrite ibm --720_135 -s ~/wolf3d/testing/DISK1/DISK1.scp
```

However, bear in mind that you cannot use rawwrite to copy disks (the data's not formatted correctly).

**Comment by Budghiss** [comment]
Ok, thank you - that worked, but the image is bad and it errors.
