### ISSUE TITLE
Simple 'make' then 'make install' fails

### ISSUE THREAD

**Issue by emersonrp** [davidgiven/fluxengine#794]
This is with Manjaro Linux, up to date.  If I run 'make' everything proceeds apace with a few warnings and then succeeds.  'make install' then fails.  (In the paste below, I ran the 'make' previously;  just demonstrating that it thinks it's succeeded at that.)

```
❯ make
make: Nothing to be done for 'all'.
❯ make install
INSTALL
install: cannot stat '.obj/unix/src+fluxengine/src+fluxengine': No such file or directory
make: *** [Makefile:102: install-bin] Error 1
❯ ls .obj/unix
+all  arch  dep  extras  lib  +protocol_hdr  __pycache__  scripts  src  tests  tools  build.mk  README.00  README.01

```

It  seems not to be making various directories in .obj/unix that the 'install' lines in the Makefile think should be there.  The binaries all seem to have been dropped in the top-level fluxengine directory, so I'm not sure what the 'install' lines in the Makefile are looking for.

I'm aware of #750 but this is not inside a chroot, and the directory it's trying to stat does contain the 'unix' chunk that's missing in that bug report.

**Comment by davidgiven** [comment]
Hello --- the install rule is broken, but the rest of it should work. I have added a Docker test for Manjaro, so I know it builds:

https://github.com/davidgiven/fluxengine/blob/master/tests/docker/Dockerfile.manjaro

So I'm guessing it's something about your local environment. I have been doing a lot of work on the build system, so it could be confused by old build artifacts. Try deleting the `.obj` directory?

**Comment by emersonrp** [comment]
Ah yeah, I was just reporting on the broken 'make install' rule -- it does drop the binaries at the top level of the project, and they seem to work, at least at first glance.  Do they need to have been installed as per the 'make install' clause in order to work fully, or does it work just fine to run them directly from the project directory?  But yeah, everything else seems fine apart from the broken install rule, so since that's a known thing, please feel free to close this if it suits you.  Thanks for the quick reply!

**Comment by davidgiven** [comment]
No, the binaries are all standalone. I can't even remember what that rule was for, now.

**Comment by davidgiven** [comment]
Broken rule removed. Thanks for the bug report!
