### ISSUE TITLE
Help reading ADFS disks

### ISSUE THREAD

**Issue by davehope** [davidgiven/fluxengine#80]
I am trying to dump several Acorn Archimedes 3.5" disks for use in an emulator. I don't have physical hardware to test the condition of the disks, but did have some limited success getting data from them using OmniFlop on an old laptop.

I have built a flux engine, tied GND on the board to one of the two GND connectors on the floppy power cable. Power to the drive is via a PC power supply with ATX pins "jumped".

I've built the firmware from master and programmed the board. I'm using the latest provided windows "fluxengine" build.

I'm reading the disks as follows, during which the drive appears to make all the right noises.
fluxengine read adfs -s :d=0 -o victorian-4.img --write-flux=victorian-4.flux

Doing so yields this:

Reading from: :d=0:s=0-1:t=0-79
Writing a copy of the flux to victorian-4.flux
  0.0: 196 ms in 68800 bytes
       5 retries remaining
  0.0: 196 ms in 69440 bytes
       4 retries remaining
  0.0: 196 ms in 69056 bytes
       3 retries remaining
  0.0: 196 ms in 68992 bytes
       2 retries remaining
  0.0: 196 ms in 68864 bytes
       1 retries remaining
  0.0: 196 ms in 69184 bytes
       giving up
       0 bytes decoded.
  0.1: 196 ms in 70720 bytes
       5 retries remaining
  0.1: 196 ms in 70464 bytes
       4 retries remaining
  0.1: 196 ms in 69952 bytes
       3 retries remaining
  0.1: 196 ms in 70656 bytes
       2 retries remaining
  0.1: 196 ms in 70336 bytes
       1 retries remaining
  0.1: 196 ms in 70400 bytes
       giving up
       0 bytes decoded.
.. etc...

Ultimately resulting in

H.SS Tracks --->
No sectors in output; skipping analysis
0 tracks, 0 heads, 0 sectors, 0 bytes per sector, 0 kB total

I'm unsure where I'm going wrong. Disk drive is a TEAC FD-235HG.

Issue is likely user error, but would appreciate some assistance in finding where I'm going wrong.

**Comment by davidgiven** [comment]
It looks like it's read data (the '196 ms' is about right), but it's not decoding it, for whatever reason.

Could you either attach the flux file, or email it to dg@cowlark.com if it's private? Then I'll have a look and see what's in it.

**Comment by davidgiven** [comment]
(Oh, also, if you do `--retries=0` then it'll stop trying each track five times, which will give a much faster read in situations wheen the decode is failing.)

**Comment by davehope** [comment]
Thanks David. I've sent you an e-mail directly, as the disks I'm trying to read are subject to copyright and licensing.

**Comment by davidgiven** [comment]
I can see the faint shadow of data on that, nothing more, and certainly nothing readable. The statistical analysis (`fluxengine inspect -s egypt.flux:s=0:t=0`) shows three very smeary peaks in about the right place for MFM pulse intervals but it's mostly just random noise.

There is one thing to try: can you do the read with `--hd`? What this does is to tell the drive to switch to high density (or maybe, double density) mode. Most 3.5" drives ignore this, including all the drives I have access to, so I haven't really been able to test it --- and the documentation's inconsistent as to whether a high signal means HD or DD. If your drive _is_ honouring this signal, and is in DD mode, then that would explain the noise.

**Comment by davehope** [comment]
Thanks for taking a look so quickly. I have run the following:

fluxengine read adfs -s :d=0 -o egypt-hd.img --write-flux=egypt-hd.flux --hd --retries=0

This produced:

Reading from: :d=0:s=0-1:t=0-79
Writing a copy of the flux to egypt-hd.flux
  0.0: 196 ms in 69184 bytes
       giving up
       0 bytes decoded.
...etc...
H.SS Tracks --->
No sectors in output; skipping analysis
0 tracks, 0 heads, 0 sectors, 0 bytes per sector, 0 kB total

So, same result. Attempting with one of my less-sacrificial disks (and crossing some fingers) produced:

H.SS Tracks --->
0. 0 ................................................................................
0. 1 ................................................................................
0. 2 ................................................................................
0. 3 ................................................................................
0. 4 ................................................................................
1. 0 ................................................................................
1. 1 ................................................................................
1. 2 ................................................................................
1. 3 ................................................................................
1. 4 ................................................................................
Good sectors: 800/800 (100%)
Missing sectors: 0/800 (0%)
Bad sectors: 0/800 (0%)
80 tracks, 2 heads, 5 sectors, 1024 bytes per sector, 800 kB total

I've repeated the process without --hd on the non-sacrificial disk and got the same output.

I suppose this means my "sacrificial" disk is dead and effectively unrecoverable?

**Comment by davidgiven** [comment]
That sounds like `--hd` isn't helping you --- it was a long shot... I'm afraid that this probably means the disk is dead, at least with FluxEngine. You mentioned you could read it with OmniFlop, though. Was that this particular disk? Because I have no idea how it managed to extract anything off that, which in turn suggests I need to improve my decoding...

**Comment by davehope** [comment]
Thanks for all your help - greatly appreciated.
