### ISSUE TITLE
Apple: Support Applesauce A2R and WOZ

### ISSUE THREAD

**Issue by d235j** [davidgiven/fluxengine#86]
The Applesauce project (https://applesaucefdc.com) is a robust system for imaging Apple and Macintosh disks using the original drives. It uses a new format called WOZ for processed Apple II images. It also uses a format called A2R for flux images.

Both formats are specified here:
https://applesaucefdc.com/a2r/
https://applesaucefdc.com/woz/

Additionally, there is a Slack discussion board where the project (and working with Apple II and Macintosh disks and disk images in general) is discussed, which may be joined here: http://apple2.gs:3000

It would be great to support these formats, as they are quickly becoming the go-to for Apple II.

Example images in multiple formats may be found on the Internet Archive:
https://archive.org/details/flux_capacity

**Comment by davidgiven** [comment]
I agree, but converting Applesauce to FluxEngine files probably isn't possible due to the incredibly flexible Apple drives --- you could do things like read data during disk seeks, which normal PC drives don't. The other direction could work, though.

**Comment by d235j** [comment]
> you could do things like read data during disk seeks, which normal PC drives don't.

I'm pretty sure the Applesauce hardware does not do this sort of stuff. It does do quarter-track subsampling. The exact format is described in the "STRM Chunk" section of the A2R specification.

I don't think support for copy protected formats is necessary. However, support for non copy protected images would be nice. 4am has a Python program here to manipulate A2R files https://github.com/a2-4am/a2rchery, and 4am's passport.py can convert between A2R and WOZ (and handle some forms of copy protection): https://github.com/a2-4am/passport.py

Additionally there are plans to extend Applesauce to support non-Apple disks, with both Apple and non-Apple drives. The extremely user-friendly UI of the Applesauce software makes it very useful for a less technical audience that needs to image disks (e.g. archives and museums).
