### ISSUE TITLE
Improving reading of Commodore 1581 related 3.5" DD disks

### ISSUE THREAD

**Issue by hpingel** [davidgiven/fluxengine#95]
Hi,

If somebody opens an issue regarding a specific disk format, one would think:
1) This person owns the original disk drive (CBM 1581).
2) This person owns genuine media (3.5" disks) that was intended for the disk drive.
3) In the century where this disk drive was released there was a high number of commercial software on the market containing disks for this specific disk drive.

In my case all three assumptions are sadly wrong. But because of a little private project I'm working on I'm trying to learn about and work with disks for 1581. So how can I contribute?

For a start, I used the latest Windows-Build of FluxEngine with a standard 3.5" PC drive to read different disks and I am able to read different formats all right (Amiga DD, IBM HD).

Yesterday I used an old PC from 2002 running Debian 10 i386 with a built-in 3.5" PC drive connected to the mainboard. I took a DD disk and put a d81-Image onto the disk with the goal to create a "genuine" disk which would be readable in a genuine Commodore 1581 disk drive.

I am optimistic that this attempt was successful. At least I was able to create a new d81-image by dd-ing the real disk back onto my Linux HDD. That image then had the same hash (md5sum) as the original image.

My impression is that the disk I created could not at all be read with `fluxengine read ibm`: I got and endless amount of checksum errors displayed from fluxengine.

I assume there is some difference between standard IBM format and 1581 format. To make it easier to spot that difference I will try to summarize all I know about the format:

To enforce the 1581 format on my Linux OS I used `fdutils` and had do the following:

```
mknod /dev/fd0cbm1581 b 2 124
setfdprm /dev/fd0cbm1581 DD DS sect=10 cyl=80 swapsides
floppycontrol /dev/fd0 -A 31,7,8,4,25,28,22,21
```

Regarding the parameters, please also compare 
https://github.com/Distrotech/fdutils/blob/master/src/mediaprm
Quote:

> #Commodore 1581  (the 3 1/2 drive of the Commodore 128)
> "CBM1581":
>  DS DD sect=10 cyl=80 ssize=512 fmt_gap=35 gap=12 swapsides

Afterwards I was able to format the DD disk like this:
`fdformat /dev/fd0cbm1581`

Finally I used dd to put the d81 image on the real disk.

My assumption is that parameters like gap-related stuff or "swapsides" is not yet right when calling "fluxengine read ibm". Or even the sect=10 instead of sect=9.

This is as much info as I can give at the moment. I am happy to add more once I learn more.

**Comment by davidgiven** [comment]
So you've written and read back the disk image using a PC with the sadly now deprecated standard FDD driver; and then you're reading it back with FluxEngine in _the same drive_ and it fails? That sounds extremely suspicious.

Could you post a log of what FluxEngine says during a read? All of it, please. Also, add `--retries=0` to prevent it constantly seeking back and forwards across the disk due to read errors.

You might _also_, in a different run, try `--hd`. This asserts the media select line to the drive which chooses between HD and DD. I've yet to find a 3.5" drive which actually honours it, and the documentation is muddled as to what the signal actually means, but it's worth a try...

**Comment by hpingel** [comment]
I will post a log tomorrow. The drive I used with Fluxengine is a different drive from the one that sits in my ancient Linux PC. (I have 4-5 different models of 3.5" PC drives here to be exact.)

**Comment by hpingel** [comment]
This is the output of 
fluxengine read ibm --retries=0

[log.txt](https://github.com/davidgiven/fluxengine/files/3519094/log.txt)
It looks like every 10th sector is marked as "B".

The drive I used this morening with fluxengine is: Teac FD-235 HF

Remark: I tried to make fluxengine.exe ouput a version string so that I can paste a log together with a version number. I didn't find this option.

**Comment by davidgiven** [comment]
Ah, I know this one! Try `--revolutions=2`.

What's happening is that FluxEngine reads from one index hole pulse to the next, so one revolution of the disk. Most formats have their sectors lined up with the index hole. However, some 1980s cheap drives don't have an index hole sensor and the sectors aren't lined up. So, if a sector overlaps the index hole, FluxEngine won't read it (or, more accurately, it reads two partial sectors and discards them).

That option causes it to spin the disk twice, so it gets a complete copy of that sector, at the expense of taking twice as long to do a disk read.

I haven't seen this on IBM scheme disks yet. Interesting.

**Comment by hpingel** [comment]
`fluxengine read ibm --revolutions=2`
An enormous improvement!

> Good sectors: 1592/1600 (99%)
> Missing sectors: 0/1600 (0%)
> Bad sectors: 8/1600 (0%)
> writing 80 tracks, 2 heads, 10 sectors, 512 bytes per sector, 800 kB total
> 

[log4.txt](https://github.com/davidgiven/fluxengine/files/3521873/log4.txt)

**Comment by hpingel** [comment]
Because of the 8 bad sectors I was a little restless and connected a different drive to Fluxengine to see if the bad sectors would be at the same spots. Instead of the Teac FD-235 HF I used a SONY MPF920-E.

Results:
> Good sectors: 1590/1600 (99%)
> Missing sectors: 0/1600 (0%)
> Bad sectors: 10/1600 (0%)
> writing 80 tracks, 2 heads, 10 sectors, 512 bytes per sector, 800 kB total

The 10 bad sectors are in completely different positions. 
[log5.txt](https://github.com/davidgiven/fluxengine/files/3521911/log5.txt)

**Comment by hpingel** [comment]
I have increased the retries to 10 and that reduced the number of bad sectors to 3 (on SONY MPDF920-E):
```
Autodetecting output geometry
H.SS Tracks --->
0. 0 ................................................................................
0. 1 ................................................................................
0. 2 ................................................................................
0. 3 ................................................................................
0. 4 ................................................................................
0. 5 ................................................................................
0. 6 ................................................................................
0. 7 ................................................................................
0. 8 .......................B........................................................
0. 9 ................................................................................
1. 0 ................................................................................
1. 1 ................................................................................
1. 2 ................................................................................
1. 3 ................................................................................
1. 4 ................................................................................
1. 5 ................................................................................
1. 6 ................................................................................
1. 7 ................................................................................
1. 8 .......B...........................................................B............
1. 9 ................................................................................
Good sectors: 1597/1600 (99%)
Missing sectors: 0/1600 (0%)
Bad sectors: 3/1600 (0%)
writing 80 tracks, 2 heads, 10 sectors, 512 bytes per sector, 800 kB total

```

**Comment by hpingel** [comment]
Above you also mentioned to play with `--hd`. I just did that  (on SONY MPDF920-E) and the result looked similar to the try without `--revolutions=2`, so I don't think you are really interested in this case. I will attach the log anyway.
[log8.txt](https://github.com/davidgiven/fluxengine/files/3522284/log8.txt)

By the way: I really enjoy experimenting with your project and I hope I don't come across nagging or in any other way negative. Thank you for creating FluxEngine!

**Comment by hpingel** [comment]
Please tell me if you prefer me to edit my comments multiple times to prevent adding a many-comment-monologue to the issue.

I just tested here with different DD disks on my ancient Linux box and it seems that from four disks I tested there is not one disk really working reliably with any of my disk drives. What I am testing is: Writing a d81 image to a disk using my Linux box (described at beginning of this issue) and then reading it in my Linux box into a new d81 file (comparing hash values) and re-reading it multiple times. It seems the disk media I am using here has not the best quality. No surprises given the age but I was hoping to find one disk that works "flawlessly". I will find it - but that takes time...

**Comment by davidgiven** [comment]
I'd much rather see the progression of comments --- I don't like text which changes when I'm not looking at it...

You might also want to try adjusting the value of `--bit-error-threshold` (and `--pulse-debounce-threshold` and `--clock-interval-bias`, but they rarely help). The default is 0.2, but I've seen some reads get dramatically better by increasing it to 0.3 or 0.4. I've also seen some get worse, which is why the default is 0.2.

**Comment by hpingel** [comment]
I will try to change those parameters - but if they improve my situation: Does that also apply to other users in this situation? Would that be a characteristic of the 1581 format / DD floppy disks or is that only something that is limited to the hardware of my mancave?

**Comment by hpingel** [comment]
Another question: I see in your project that quite a few disks need the `--revolutions=2` parameter as their sectors may not align with the index hole pulse. In case of the 1581 it was the case that the drive would not so much care about individual sectors as it would read/write whole tracks into its memory and then access the sectors in memory (source: http://vice-emu.sourceforge.net/vice_16.html#SEC317).

Is it maybe the case that the tracks of the 1581 disks are aligned with the index hole pulse? If that would be true: Would there be a way to read this disk format track based to avoid the time penalty of  `--revolutions=2`? A cheeky questions, I know.

**Comment by davidgiven** [comment]
What the 1581 probably did was to start reading at a random point, parsing the sectors as it read them, until it had a complete track's worth. So, it would end up reading slightly _more_ than a complete track (as it would probably start reading in the middle of a sector, which would then be discarded and read again during the next revolution). (The Amiga did much the same.) However, the FluxEngine captures data without parsing it, so it can't tell where sectors start or stop during the capture.

Currently FluxEngine just captures all data between two index pulses (or more if you set `--revolutions`). It would probably be possible to add a delay of, say, 1/4 of a revolution so that it always reads slightly more than a complete revolution, to try and attempt to capture any sector which overlaps the index hole. I'll have to think about whether that's worth it...

**Comment by hpingel** [comment]
Yesterday night I discovered that increasing the value of `--revolutions` seems to help to read my DD disks (be it Commodore 1581 or Amiga (adf-based). I just set `--revolutions=4` and `--revolutions=8`. The latter helped me to get a sector table without any B's at the end. The obtained file still is not perfect but I would like to ask you to look into what "magic" is happening when using more than two revolutions. With value 8 I didn't need to tweak any threshold or bias.

Could you elaborate on what missing sectors (X) are?

**Comment by hpingel** [comment]
For the first time since I started experimenting with Fluxengine, I managed to read a DD disk with (hopefully) a 1581 filesystem completely and flawlessly and got the md5sum for the image file written by Fluxengine that I have wished for! So Fluxengine works in this case! I am quite happy at the moment and want to thank you!

`
Autodetecting output geometry
H.SS Tracks --->
0. 0 ................................................................................
0. 1 ................................................................................
0. 2 ................................................................................
0. 3 ................................................................................
0. 4 ................................................................................
0. 5 ................................................................................
0. 6 ................................................................................
0. 7 ................................................................................
0. 8 ................................................................................
0. 9 ................................................................................
1. 0 ................................................................................
1. 1 ................................................................................
1. 2 ................................................................................
1. 3 ................................................................................
1. 4 ................................................................................
1. 5 ................................................................................
1. 6 ................................................................................
1. 7 ................................................................................
1. 8 ................................................................................
1. 9 ................................................................................
Good sectors: 1600/1600 (100%)
Missing sectors: 0/1600 (0%)
Bad sectors: 0/1600 (0%)
writing 80 tracks, 2 heads, 10 sectors, 512 bytes per sector, 800 kB total
`
For this attempt I used my TEAC floppy drive all the way through - to format the disk, to put the d81 onto the disk (using my ancient Linux box) and to read the disk via Fluxengine on my modern Ryzen Linux box.

To read the whole disk without a single bad sector I was quiet generous on the retries:
`./fluxengine read ibm -o "unnamedComputerGame.d81" --revolutions=3 --retries=10`

But there was only one single bad sector coming up with `--retries=5`

**Comment by davidgiven** [comment]
Hmm. That's not brilliant. What do you get with `--retries=0`?

What's happening is that floppy disks are inherently noisy as they're extremely analogue devices. By reading the disk multiple times, any marginal bits have a certain percentage chance of being read correctly, by sheer chance. If you need lots of retries, that suggests lots of errors, which shouldn't happen. `--revolutions` is doing precisely the same thing, except faster; three revolutions means it's reading every sector three times, so there's more chance of getting it right.

As the Linux FDC is, pretty much by definition, correct, then this suggests something wrong at my end.

Does `--bit-error-threshold=0.3` make things better or worse?

**Comment by hpingel** [comment]
This is same disk / same disk drive / retries=0 / revolutions=2:
todetecting output geometry
```
H.SS Tracks --->
0. 0 ...........................B.............................B.........B.........B..
0. 1 ....B.........B...................B...................B.........B...............
0. 2 .B.........B.........B.........B.........B.........B.........B.........B........
0. 3 ......................................B.........B...................B.........B.
0. 4 .......................................................B...................B....
0. 5 ..B.........B.........B.........B.........B.........B.........B.........B.......
0. 6 .........B...................B.........B.........B.........B.........B..........
0. 7 ......B.........B...................B...................B...................B...
0. 8 ...B.............................B.........B.........B.........B................
0. 9 ........................................B.........B.........B...................
1. 0 .B.........B...................B...................B...................B........
1. 1 ........B.........B...................B...................B.........B...........
1. 2 .....B.........B.........B.............................B...................B....
1. 3 ..............................................................B.........B.......
1. 4 ...................B.........B.........B.........B...................B..........
1. 5 ......B.........B.............................B...................B.........B...
1. 6 ................................................................................
1. 7 B.........B...................B.........B.......................................
1. 8 .......B...................B.............................B.........B.........B..
1. 9 ..............B.......................................B.........B.........B.....
Good sectors: 1510/1600 (94%)
Missing sectors: 0/1600 (0%)
Bad sectors: 90/1600 (5%)
writing 80 tracks, 2 heads, 10 sectors, 512 bytes per sector, 800 kB total

```
More coming up as "the disk spins...."

**Comment by hpingel** [comment]
./fluxengine read ibm -o "bla.d81" --revolutions=2 --retries=0 --bit-error-threshold=0.3

```
Autodetecting output geometry
H.SS Tracks --->
0. 0 .......B.........B.........B.......................................B.........B..
0. 1 ....B...................B...................B.........B...................B.....
0. 2 .B.............................B...................B.........B.........B........
0. 3 ........B.........B.........B...................B...................B.........B.
0. 4 ...............B...................B.........B.........B.........B.........B....
0. 5 ............B.............................B.........B.........B.........B.......
0. 6 .........B.........B...................B.........B.............................B
0. 7 ......B...........................................................B.............
0. 8 ...B.........B.........B...................B.........B.........B................
0. 9 B.........B.........B.........B.............................B.........B.........
1. 0 .B.........B...................B.........B.........B.........B.........B........
1. 1 ........B.........B.........B...................B...................B.........B.
1. 2 .....B.........B.......................................B.........B.........B....
1. 3 ..B.........B.........B.............................B.........B.........B.......
1. 4 .........B.......................................B.........B.........B.........B
1. 5 ......B.........B.........B.............................B.........B.............
1. 6 .............B...................B...................B.........B.........B......
1. 7 B.........B.........B...................B.............................B.........
1. 8 .......B.............................B.........B.........B.........B.........B..
1. 9 ..............B.........B.............................B.........B.........B.....
Good sectors: 1494/1600 (93%)
Missing sectors: 0/1600 (0%)
Bad sectors: 106/1600 (6%)
writing 80 tracks, 2 heads, 10 sectors, 512 bytes per sector, 800 kB total

```

**Comment by davidgiven** [comment]
Wat.

Attach the flux file, please!

**Comment by hpingel** [comment]
I would like to comment:
- I have here a DD driver disk from an ancient HP DeskJet Printer (Printer Driver for DOS applications. This disk seems to be in a good condition and reads fine in Fluxengine with "read ibm". This means that reading DD disks as such is not broken. It's more something about the 1581 quirks I suppose.

**Comment by hpingel** [comment]
./fluxengine read ibm --revolutions=2 --just-read --retries=0 --write-flux=d81.flux

[d81.flux.rename.txt](https://github.com/davidgiven/fluxengine/files/3543160/d81.flux.rename.txt)

Is that an sqlite db?

If you need other parameters just tell me.

**Comment by davidgiven** [comment]
Yup, totally sqlite. It was the easiest and most overkill way of making a file containing an arbitrary collection of objects.

I've written a very prototype disk visualisation tool; if you want to check it out, look in the `visualiser` branch, and do `--write-svg=out.svg` when reading. For your disk, it looks like this:

![out](https://user-images.githubusercontent.com/100638/63729457-934d1580-c867-11e9-97c0-11d99eb73183.jpg)

Blue arcs indicate good sectors, red ones bad sectors. You can see that all the bad sectors line up physically on the disk. The visualiser's a bit buggy, as you can see the bad sectors overlap with the good ones, but it's definitely a clue.

Are these 5.25" disks? What does `fluxengine rpm` say?

**Comment by hpingel** [comment]
Nice SVG visualization! Have to look into that branch at some point.

These are 3,5" disks. (Although I own a couple of 1541 Commodore disk drives, they are using the IEC bus and not  for the Shugart bus - I can't connect them to Fluxengine hardware. I don't own a 5.25" drive usable with Fluxengine.)
```
hp@ryzentux:~/gitrepos/fluxengine$ ./fluxengine rpm -s ":d=0:t=0-79:s=0-1"
Rotational period is 200 ms (300 rpm)
```
My view is that when we talk about "bad sectors" in this case we talk about sectors that Fluxengine **considers** to be bad but if forced with many retries is happy to read completely fine.

**Comment by hpingel** [comment]
Some content for brainstorming on this issue:
- https://forum.kryoflux.com/viewtopic.php?t=639

**Comment by hpingel** [comment]
Me again. I tried your visualizer branch on my HP Deskjet Driver disk (DD, IBM, 720 KB). This is how it looks:

![hpdeskjet](https://user-images.githubusercontent.com/646865/63793884-e6bf7200-c900-11e9-9fd5-4b53f90570b6.png)

A standard IBM disk has only 9 sectors by track (not that I am telling you anything new here). I was surprised to see that according to the visualizer it is not evenly spaced. Is that due to the early dev stage of the visualizer branch?

**Comment by hpingel** [comment]
Just to gather something to compare with, I also read my amiga test disk. This is a bit unfair because this visualizer branch is only a couple of hours old and clearly it doesn't adapt to the number of sectors per track - amiga has 11. But my point is: All the red sectors are in a similar position compared to the 1581 diagram.

`./fluxengine read amiga -o "17+4check.adf" --write-svg=amiga174.svg`

![amiga](https://user-images.githubusercontent.com/646865/63794925-3bfc8300-c903-11e9-931b-ab1b2205883b.png)

**Comment by davidgiven** [comment]
Re the IBM disks: I was surprised too, but I think that's correct. There's a dead period around the index mark where a standard PC FDC can't write data (the pre-index and final gaps). (The index mark is dead right, BTW.) So I think that empty wedge is simply the part of the disk whereno data is stored. I wasn't expecting it to be so large.

Re the bad sectors: I'm coming to the conclusion that what we have here is a sampler bug. I think that, under some circumstances, data's getting corrupted or lost when the index mark appears. I've just scanned one of my Amiga disks, an original 1993 PD library disk, and it produces exactly what you're seeing (image attached). I also note that it's reporting 392ms of data for two revolutions, which isn't right (it should be almost precisely 400ms). This used to work, with this disk, so this is clearly a regression. Sorry.

(I hate that sampler code.)

![out](https://user-images.githubusercontent.com/100638/63803881-2e9cc400-c916-11e9-907a-06f39218fce4.jpg)

**Comment by hpingel** [comment]
Great that the "redness" of our diagrams matches at around 4'o clock - I was worried that I flashed wrong stuff onto the Cypress hardware. I still have to wrap my head around it that one can see stuff so easily on the diagram and not really see it on the ASCII summary. Although I wrote at some point "every 10th sector" or so.

Regarding a possible sampler regression: I haven't installed the Cypress SDK for nothing. :-)
If it's a regression you can at least move back to the point when it was still running?

Thanks for the explanation regarding the IBM "gap".

When reading your changes in the visualization branch I noticed you added --visualiser-period. I think all those three disk formats I'm testing are all at 300rpm so in my case I will not touch the default value.

**Comment by davidgiven** [comment]
Fixed. Turns out that index marks were being misreported as flux pulses, causing corrupted data.

You'll need to rebuild the firmware and reprogram, I'm afraid (or just use the Cypress Programmer to flash the precompiled firmware).

...in case you're interested in the sampler, open up PSoC Creator, load the project, select 'components' in the tab on the left, and it's the file called something like 'sampler.cyudb'. Good luck, you'll need it...

Here's the visualisation from the same Amiga disk. I believe those two dead sectors are genuinely dead, but the position is suspicious.

![out](https://user-images.githubusercontent.com/100638/63812645-4763a480-c92b-11e9-8e6c-7783a6449b9a.jpg)

**Comment by hpingel** [comment]
Thank you very much. By the way: I don't expect overnight solutions at the cost of your energy levels! :-) Keep me waiting and I will eventually become impatient and start to read more of the code.

I just tested with the new hex file (compiled it myself - only took me 2-3 attempts to get the new one on the device - but learning by repeating is good.)

I'm still on the visualiser branch but IMHO that's ok for now as the master changes were all regarding Cypress firmware.

Here are new diagrams - all with --retries=0:

IBM DD 720KB
![hpdeskjet3](https://user-images.githubusercontent.com/646865/63828635-7f88d880-c967-11e9-8158-43f2ad581507.png)

Amiga DD
![amiga174_2](https://user-images.githubusercontent.com/646865/63828655-8e6f8b00-c967-11e9-8e5e-9734962e24e8.png)

Commodore 1581 DD
![ultima4_1581_wednesday2](https://user-images.githubusercontent.com/646865/63828672-99c2b680-c967-11e9-888e-8a14b1de3dc5.png)

Looks much much better.

I'm happy that I could help to detect the issue!

**Comment by hpingel** [comment]
One addition to 1581 disks:

A kind person has sent me six authentic 1581 disks to experiment with. Fluxengine reads those disks flawlessly without the parameter --revolutions=2 being necessary at all.

So this means that my test disks that were written on my old Linux box trying to get as close as possible to real 1581 disks are not aligned to the index pulse but real 1581 disks are. Surprising!

**Comment by davidgiven** [comment]
Interesting: I'd have expected it to be the other way round. Maybe the 1581 _does_ pay attention to the index hole after all! And I'm very surprised the PC disks aren't aligned.

Were the PC disks actually formatted on a PC, or just _written_ on a PC and were formatted on another machine?

**Comment by hpingel** [comment]
I have formatted my two DD 1581-style test disks on the same PC in the same floppy drive (using fdformat) where I would afterwards call dd to write an image to the formatted disk.

As I am not an expert with fdutils and fdformat I was looking for parameters that I might have missed using to enforce index hole alignment (didn't find any so far).

What I could try is to just format a disk in 1581 style and not write a d81 image to it and check again with Fluxengine. This whole "hobby"/"obsession" seems to become a long-term thing so I might find out something relevant in the future that I don't know at the moment - which I will then add here.
