### ISSUE TITLE
"Error: unrecognised image filename extension" issued at the "bitter end"

### ISSUE THREAD

**Issue by hpingel** [davidgiven/fluxengine#96]
Hi David,

I called FlugEngine with
fluxengine read ibm --retries=10 --revolutions=2 --output="mydisk.d81"

I learned now that obviously I am not free to choose any arbitrary output file name extension. That is ok for me (d81 could be added later at some point).

What I found unusual is that the error message "Error: unrecognised image filename extension" is issued after all tracks of the disk were read. I would prefer to get it in the beginning before reading the tracks on the disk starts.

Cheers,
Henning

**Comment by davidgiven** [comment]
Yes, that should be fixed.

**Comment by davidgiven** [comment]
If you look in the 'extensions' branch (assuming the autobuild works), support for this should be there.
